<a href="https://colab.research.google.com/github/prpNn0p/machinetranslation/blob/main/simpletransformers_mt_th_en.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Original Note

In [ ]:
'''
How to Train an mT5 Model for Translation With Simple Transformers
The mT5 model is pre-trained on over a hundred different languages. 
Let’s see how we can leverage this to train a bilingual translation model 
for a low-resource language — Sinhalese.
'''






'''
mT5 is a multilingual Transformer model pre-trained on a dataset (mC4) containing text from 101 different languages. 
The architecture of the mT5 model (based on T5) is designed to support any Natural Language Processing task (classification, NER, question answering, etc.) by reframing the required task as a sequence-to-sequence task.

In other words — text goes in, and text comes out. For example, in a classification task, the input to the model can be the text sequence to be classified, 
and the output from the model will be the class label for the sequence. 
For translation, this is even more straight forward. The text that goes in is in one language, and the text that comes out is in another.

Considering the multilingual capabilities of mT5 and the suitability of 
the sequence-to-sequence format for language translation, let’s see how we can fine-tune an mT5 model for machine translation. 
For this article, we’ll be training a translation model to translate between Sinhalese (my native language!) and English. 
It’s quite challenging to train good translation models for low-resource languages like Sinhalese because of, well, the low availability of resources (training data). 

Hopefully, the multilingual pre-training on a huge dataset (which includes Sinhalese, 
although not a lot of it) will help the mT5 model compensate for inadequate training data in the form of direct Sinhalese-English (and vice versa) sequences.

We’ll be using the Simple Transformers library (built on the Huggingface Transformers library) to train the mT5 model. 
The training and testing data will be obtained from The Tatoeba Translation Challenge. 
The graphs and charts are generated from Weights & Biases, which is supported natively in Simple Transformers for experiment tracking and hyperparameter optimization.

Note: You can find all the code in this article in the examples/t5/mt5_translation directory (link) of the Simple Transformers Github repo.
'''


'''
Outline

    Installing Simple Transformers
    Downloading a dataset for translation
    Training the model
    Evaluating the model — Calculating the BLEU score
    Wrap up

'''

##Setup

You can find the most up-to-date installation instructions in the Simple Transformers documentation.

1. Install Anaconda or Miniconda Package Manager from here.

2. Create a new virtual environment and install packages.

In [ ]:
# conda create -n st python pandas tqdm sacrebleu
# conda activate st

3. If using CUDA:

In [ ]:
# conda install pytorch>=1.6 cudatoolkit=10.2 -c pytorch

else:

In [ ]:
# conda install pytorch cpuonly -c pytorch

4. Install simple transformers.

In [ ]:
!pip install simpletransformers

Collecting simpletransformers
  Downloading simpletransformers-0.63.4-py3-none-any.whl (248 kB)
     |████████████████████████████████| 248 kB 14.1 MB/s
Collecting transformers>=4.6.0
  Downloading transformers-4.17.0-py3-none-any.whl (3.8 MB)
     |████████████████████████████████| 3.8 MB 85.7 MB/s
Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (from simpletransformers) (1.21.5)
Requirement already satisfied: regex in /usr/local/lib/python3.7/dist-packages (from simpletransformers) (2019.12.20)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.7/dist-packages (from simpletransformers) (1.0.2)
Collecting wandb>=0.10.32
  Downloading wandb-0.12.11-py2.py3-none-any.whl (1.7 MB)
     |████████████████████████████████| 1.7 MB 58.6 MB/s
Collecting streamlit
  Downloading streamlit-1.7.0-py2.py3-none-any.whl (9.9 MB)
     |████████████████████████████████| 9.9 MB 53.0 MB/s
Collecting tokenizers
  Downloading tokenizers-0.11.6-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (6.5 MB)
     |████████████████████████████████| 6.5 MB 42.9 MB/s
Requirement already satisfied: pandas in /usr/local/lib/python3.7/dist-packages (from simpletransformers) (1.3.5)
Requirement already satisfied: scipy in /usr/local/lib/python3.7/dist-packages (from simpletransformers) (1.4.1)
Requirement already satisfied: tqdm>=4.47.0 in /usr/local/lib/python3.7/dist-packages (from simpletransformers) (4.63.0)
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from simpletransformers) (2.23.0)
Collecting sentencepiece
  Downloading sentencepiece-0.1.96-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.2 MB)
     |████████████████████████████████| 1.2 MB 54.3 MB/s
Collecting seqeval
  Downloading seqeval-1.2.2.tar.gz (43 kB)
     |████████████████████████████████| 43 kB 1.9 MB/s
Collecting datasets
  Downloading datasets-1.18.4-py3-none-any.whl (312 kB)
     |████████████████████████████████| 312 kB 53.3 MB/s
Requirement already satisfied: tensorboard in /usr/local/lib/python3.7/dist-packages (from simpletransformers) (2.8.0)
Collecting pyyaml>=5.1
  Downloading PyYAML-6.0-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (596 kB)
     |████████████████████████████████| 596 kB 70.6 MB/s
Collecting sacremoses
  Downloading sacremoses-0.0.47-py2.py3-none-any.whl (895 kB)
     |████████████████████████████████| 895 kB 55.7 MB/s
Requirement already satisfied: filelock in /usr/local/lib/python3.7/dist-packages (from transformers>=4.6.0->simpletransformers) (3.6.0)
Collecting huggingface-hub<1.0,>=0.1.0
  Downloading huggingface_hub-0.4.0-py3-none-any.whl (67 kB)
     |████████████████████████████████| 67 kB 5.7 MB/s
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.7/dist-packages (from transformers>=4.6.0->simpletransformers) (21.3)
Requirement already satisfied: importlib-metadata in /usr/local/lib/python3.7/dist-packages (from transformers>=4.6.0->simpletransformers) (4.11.2)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.7/dist-packages (from huggingface-hub<1.0,>=0.1.0->transformers>=4.6.0->simpletransformers) (3.10.0.2)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/local/lib/python3.7/dist-packages (from packaging>=20.0->transformers>=4.6.0->simpletransformers) (3.0.7)
Requirement already satisfied: Click!=8.0.0,>=7.0 in /usr/local/lib/python3.7/dist-packages (from wandb>=0.10.32->simpletransformers) (7.1.2)
Requirement already satisfied: python-dateutil>=2.6.1 in /usr/local/lib/python3.7/dist-packages (from wandb>=0.10.32->simpletransformers) (2.8.2)
Collecting docker-pycreds>=0.4.0
  Downloading docker_pycreds-0.4.0-py2.py3-none-any.whl (9.0 kB)
Collecting setproctitle
  Downloading setproctitle-1.2.2-cp37-cp37m-manylinux1_x86_64.whl (36 kB)
Requirement already satisfied: six>=1.13.0 in /usr/local/lib/python3.7/dist-packages (from wandb>=0.10.32->simpletransformers) (1.15.0)
Requirement already satisfied: psutil>=5.0.0 in /usr/local/lib/python3.7/dist-packages (from wandb>=0.10.32->simpletransformers) (5.4.8)
Collecting pathtools
  Downloading pathtools-0.1.2.tar.gz (11 kB)
Collecting yaspin>=1.0.0
  Downloading yaspin-2.1.0-py3-none-any.whl (18 kB)
Requirement already satisfied: promise<3,>=2.0 in /usr/local/lib/python3.7/dist-packages (from wandb>=0.10.32->simpletransformers) (2.3)
Collecting shortuuid>=0.5.0
  Downloading shortuuid-1.0.8-py3-none-any.whl (9.5 kB)
Requirement already satisfied: protobuf>=3.12.0 in /usr/local/lib/python3.7/dist-packages (from wandb>=0.10.32->simpletransformers) (3.17.3)
Collecting GitPython>=1.0.0
  Downloading GitPython-3.1.27-py3-none-any.whl (181 kB)
     |████████████████████████████████| 181 kB 56.8 MB/s
Collecting sentry-sdk>=1.0.0
  Downloading sentry_sdk-1.5.7-py2.py3-none-any.whl (144 kB)
     |████████████████████████████████| 144 kB 55.3 MB/s
Collecting gitdb<5,>=4.0.1
  Downloading gitdb-4.0.9-py3-none-any.whl (63 kB)
     |████████████████████████████████| 63 kB 1.6 MB/s
Collecting smmap<6,>=3.0.1
  Downloading smmap-5.0.0-py3-none-any.whl (24 kB)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->simpletransformers) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests->simpletransformers) (1.24.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests->simpletransformers) (2021.10.8)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->simpletransformers) (2.10)
Requirement already satisfied: termcolor<2.0.0,>=1.1.0 in /usr/local/lib/python3.7/dist-packages (from yaspin>=1.0.0->wandb>=0.10.32->simpletransformers) (1.1.0)
Collecting responses<0.19
  Downloading responses-0.18.0-py3-none-any.whl (38 kB)
Requirement already satisfied: dill in /usr/local/lib/python3.7/dist-packages (from datasets->simpletransformers) (0.3.4)
Requirement already satisfied: pyarrow!=4.0.0,>=3.0.0 in /usr/local/lib/python3.7/dist-packages (from datasets->simpletransformers) (6.0.1)
Collecting xxhash
  Downloading xxhash-3.0.0-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (212 kB)
     |████████████████████████████████| 212 kB 74.1 MB/s
Requirement already satisfied: multiprocess in /usr/local/lib/python3.7/dist-packages (from datasets->simpletransformers) (0.70.12.2)
Collecting fsspec[http]>=2021.05.0
  Downloading fsspec-2022.2.0-py3-none-any.whl (134 kB)
     |████████████████████████████████| 134 kB 64.5 MB/s
Collecting aiohttp
  Downloading aiohttp-3.8.1-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (1.1 MB)
     |████████████████████████████████| 1.1 MB 68.7 MB/s
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
  Downloading urllib3-1.25.11-py2.py3-none-any.whl (127 kB)
     |████████████████████████████████| 127 kB 20.5 MB/s
Collecting yarl<2.0,>=1.0
  Downloading yarl-1.7.2-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (271 kB)
     |████████████████████████████████| 271 kB 64.8 MB/s
Collecting frozenlist>=1.1.1
  Downloading frozenlist-1.3.0-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (144 kB)
     |████████████████████████████████| 144 kB 67.4 MB/s
Collecting aiosignal>=1.1.2
  Downloading aiosignal-1.2.0-py3-none-any.whl (8.2 kB)
Collecting multidict<7.0,>=4.5
  Downloading multidict-6.0.2-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (94 kB)
     |████████████████████████████████| 94 kB 2.9 MB/s
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.7/dist-packages (from aiohttp->datasets->simpletransformers) (21.4.0)
Collecting asynctest==0.13.0
  Downloading asynctest-0.13.0-py3-none-any.whl (26 kB)
Requirement already satisfied: charset-normalizer<3.0,>=2.0 in /usr/local/lib/python3.7/dist-packages (from aiohttp->datasets->simpletransformers) (2.0.12)
Collecting async-timeout<5.0,>=4.0.0a3
  Downloading async_timeout-4.0.2-py3-none-any.whl (5.8 kB)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata->transformers>=4.6.0->simpletransformers) (3.7.0)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas->simpletransformers) (2018.9)
Requirement already satisfied: joblib in /usr/local/lib/python3.7/dist-packages (from sacremoses->transformers>=4.6.0->simpletransformers) (1.1.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn->simpletransformers) (3.1.0)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.7/dist-packages (from streamlit->simpletransformers) (7.1.2)
Requirement already satisfied: tzlocal in /usr/local/lib/python3.7/dist-packages (from streamlit->simpletransformers) (1.5.1)
Requirement already satisfied: semver in /usr/local/lib/python3.7/dist-packages (from streamlit->simpletransformers) (2.13.0)
Collecting base58
  Downloading base58-2.1.1-py3-none-any.whl (5.6 kB)
Collecting validators
  Downloading validators-0.18.2-py3-none-any.whl (19 kB)
Requirement already satisfied: cachetools>=4.0 in /usr/local/lib/python3.7/dist-packages (from streamlit->simpletransformers) (4.2.4)
Collecting watchdog
  Downloading watchdog-2.1.6-py3-none-manylinux2014_x86_64.whl (76 kB)
     |████████████████████████████████| 76 kB 4.7 MB/s
Requirement already satisfied: tornado>=5.0 in /usr/local/lib/python3.7/dist-packages (from streamlit->simpletransformers) (5.1.1)
Collecting toml
  Downloading toml-0.10.2-py2.py3-none-any.whl (16 kB)
Requirement already satisfied: astor in /usr/local/lib/python3.7/dist-packages (from streamlit->simpletransformers) (0.8.1)
Collecting pydeck>=0.1.dev5
  Downloading pydeck-0.7.1-py2.py3-none-any.whl (4.3 MB)
     |████████████████████████████████| 4.3 MB 64.5 MB/s
Collecting blinker
  Downloading blinker-1.4.tar.gz (111 kB)
     |████████████████████████████████| 111 kB 68.0 MB/s
Requirement already satisfied: altair>=3.2.0 in /usr/local/lib/python3.7/dist-packages (from streamlit->simpletransformers) (4.2.0)
Collecting pympler>=0.9
  Downloading Pympler-1.0.1-py3-none-any.whl (164 kB)
     |████████████████████████████████| 164 kB 66.3 MB/s
Requirement already satisfied: jinja2 in /usr/local/lib/python3.7/dist-packages (from altair>=3.2.0->streamlit->simpletransformers) (2.11.3)
Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.7/dist-packages (from altair>=3.2.0->streamlit->simpletransformers) (4.3.3)
Requirement already satisfied: toolz in /usr/local/lib/python3.7/dist-packages (from altair>=3.2.0->streamlit->simpletransformers) (0.11.2)
Requirement already satisfied: entrypoints in /usr/local/lib/python3.7/dist-packages (from altair>=3.2.0->streamlit->simpletransformers) (0.4)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in /usr/local/lib/python3.7/dist-packages (from jsonschema>=3.0->altair>=3.2.0->streamlit->simpletransformers) (0.18.1)
Requirement already satisfied: importlib-resources>=1.4.0 in /usr/local/lib/python3.7/dist-packages (from jsonschema>=3.0->altair>=3.2.0->streamlit->simpletransformers) (5.4.0)
Requirement already satisfied: traitlets>=4.3.2 in /usr/local/lib/python3.7/dist-packages (from pydeck>=0.1.dev5->streamlit->simpletransformers) (5.1.1)
Requirement already satisfied: ipywidgets>=7.0.0 in /usr/local/lib/python3.7/dist-packages (from pydeck>=0.1.dev5->streamlit->simpletransformers) (7.6.5)
Collecting ipykernel>=5.1.2
  Downloading ipykernel-6.9.1-py3-none-any.whl (128 kB)
     |████████████████████████████████| 128 kB 82.5 MB/s
Requirement already satisfied: debugpy<2.0,>=1.0.0 in /usr/local/lib/python3.7/dist-packages (from ipykernel>=5.1.2->pydeck>=0.1.dev5->streamlit->simpletransformers) (1.0.0)
Requirement already satisfied: jupyter-client<8.0 in /usr/local/lib/python3.7/dist-packages (from ipykernel>=5.1.2->pydeck>=0.1.dev5->streamlit->simpletransformers) (5.3.5)
Collecting ipython>=7.23.1
  Downloading ipython-7.32.0-py3-none-any.whl (793 kB)
     |████████████████████████████████| 793 kB 84.0 MB/s
Requirement already satisfied: matplotlib-inline<0.2.0,>=0.1.0 in /usr/local/lib/python3.7/dist-packages (from ipykernel>=5.1.2->pydeck>=0.1.dev5->streamlit->simpletransformers) (0.1.3)
Requirement already satisfied: nest-asyncio in /usr/local/lib/python3.7/dist-packages (from ipykernel>=5.1.2->pydeck>=0.1.dev5->streamlit->simpletransformers) (1.5.4)
Collecting prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0
  Downloading prompt_toolkit-3.0.28-py3-none-any.whl (380 kB)
     |████████████████████████████████| 380 kB 83.0 MB/s
Requirement already satisfied: pygments in /usr/local/lib/python3.7/dist-packages (from ipython>=7.23.1->ipykernel>=5.1.2->pydeck>=0.1.dev5->streamlit->simpletransformers) (2.6.1)
Requirement already satisfied: backcall in /usr/local/lib/python3.7/dist-packages (from ipython>=7.23.1->ipykernel>=5.1.2->pydeck>=0.1.dev5->streamlit->simpletransformers) (0.2.0)
Requirement already satisfied: jedi>=0.16 in /usr/local/lib/python3.7/dist-packages (from ipython>=7.23.1->ipykernel>=5.1.2->pydeck>=0.1.dev5->streamlit->simpletransformers) (0.18.1)
Requirement already satisfied: decorator in /usr/local/lib/python3.7/dist-packages (from ipython>=7.23.1->ipykernel>=5.1.2->pydeck>=0.1.dev5->streamlit->simpletransformers) (4.4.2)
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.7/dist-packages (from ipython>=7.23.1->ipykernel>=5.1.2->pydeck>=0.1.dev5->streamlit->simpletransformers) (57.4.0)
Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.7/dist-packages (from ipython>=7.23.1->ipykernel>=5.1.2->pydeck>=0.1.dev5->streamlit->simpletransformers) (4.8.0)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.7/dist-packages (from ipython>=7.23.1->ipykernel>=5.1.2->pydeck>=0.1.dev5->streamlit->simpletransformers) (0.7.5)
Requirement already satisfied: nbformat>=4.2.0 in /usr/local/lib/python3.7/dist-packages (from ipywidgets>=7.0.0->pydeck>=0.1.dev5->streamlit->simpletransformers) (5.1.3)
Requirement already satisfied: ipython-genutils~=0.2.0 in /usr/local/lib/python3.7/dist-packages (from ipywidgets>=7.0.0->pydeck>=0.1.dev5->streamlit->simpletransformers) (0.2.0)
Requirement already satisfied: widgetsnbextension~=3.5.0 in /usr/local/lib/python3.7/dist-packages (from ipywidgets>=7.0.0->pydeck>=0.1.dev5->streamlit->simpletransformers) (3.5.2)
Requirement already satisfied: jupyterlab-widgets>=1.0.0 in /usr/local/lib/python3.7/dist-packages (from ipywidgets>=7.0.0->pydeck>=0.1.dev5->streamlit->simpletransformers) (1.0.2)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in /usr/local/lib/python3.7/dist-packages (from jedi>=0.16->ipython>=7.23.1->ipykernel>=5.1.2->pydeck>=0.1.dev5->streamlit->simpletransformers) (0.8.3)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.7/dist-packages (from jinja2->altair>=3.2.0->streamlit->simpletransformers) (2.0.1)
Requirement already satisfied: pyzmq>=13 in /usr/local/lib/python3.7/dist-packages (from jupyter-client<8.0->ipykernel>=5.1.2->pydeck>=0.1.dev5->streamlit->simpletransformers) (22.3.0)
Requirement already satisfied: jupyter-core>=4.6.0 in /usr/local/lib/python3.7/dist-packages (from jupyter-client<8.0->ipykernel>=5.1.2->pydeck>=0.1.dev5->streamlit->simpletransformers) (4.9.2)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.7/dist-packages (from pexpect>4.3->ipython>=7.23.1->ipykernel>=5.1.2->pydeck>=0.1.dev5->streamlit->simpletransformers) (0.7.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.7/dist-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=7.23.1->ipykernel>=5.1.2->pydeck>=0.1.dev5->streamlit->simpletransformers) (0.2.5)
Requirement already satisfied: notebook>=4.4.1 in /usr/local/lib/python3.7/dist-packages (from widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->pydeck>=0.1.dev5->streamlit->simpletransformers) (5.3.1)
Requirement already satisfied: Send2Trash in /usr/local/lib/python3.7/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->pydeck>=0.1.dev5->streamlit->simpletransformers) (1.8.0)
Requirement already satisfied: terminado>=0.8.1 in /usr/local/lib/python3.7/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->pydeck>=0.1.dev5->streamlit->simpletransformers) (0.13.1)
Requirement already satisfied: nbconvert in /usr/local/lib/python3.7/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->pydeck>=0.1.dev5->streamlit->simpletransformers) (5.6.1)
Requirement already satisfied: pandocfilters>=1.4.1 in /usr/local/lib/python3.7/dist-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->pydeck>=0.1.dev5->streamlit->simpletransformers) (1.5.0)
Requirement already satisfied: bleach in /usr/local/lib/python3.7/dist-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->pydeck>=0.1.dev5->streamlit->simpletransformers) (4.1.0)
Requirement already satisfied: testpath in /usr/local/lib/python3.7/dist-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->pydeck>=0.1.dev5->streamlit->simpletransformers) (0.6.0)
Requirement already satisfied: mistune<2,>=0.8.1 in /usr/local/lib/python3.7/dist-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->pydeck>=0.1.dev5->streamlit->simpletransformers) (0.8.4)
Requirement already satisfied: defusedxml in /usr/local/lib/python3.7/dist-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->pydeck>=0.1.dev5->streamlit->simpletransformers) (0.7.1)
Requirement already satisfied: webencodings in /usr/local/lib/python3.7/dist-packages (from bleach->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->pydeck>=0.1.dev5->streamlit->simpletransformers) (0.5.1)
Requirement already satisfied: werkzeug>=0.11.15 in /usr/local/lib/python3.7/dist-packages (from tensorboard->simpletransformers) (1.0.1)
Requirement already satisfied: wheel>=0.26 in /usr/local/lib/python3.7/dist-packages (from tensorboard->simpletransformers) (0.37.1)
Requirement already satisfied: google-auth<3,>=1.6.3 in /usr/local/lib/python3.7/dist-packages (from tensorboard->simpletransformers) (1.35.0)
Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in /usr/local/lib/python3.7/dist-packages (from tensorboard->simpletransformers) (1.8.1)
Requirement already satisfied: tensorboard-data-server<0.7.0,>=0.6.0 in /usr/local/lib/python3.7/dist-packages (from tensorboard->simpletransformers) (0.6.1)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.7/dist-packages (from tensorboard->simpletransformers) (3.3.6)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in /usr/local/lib/python3.7/dist-packages (from tensorboard->simpletransformers) (0.4.6)
Requirement already satisfied: absl-py>=0.4 in /usr/local/lib/python3.7/dist-packages (from tensorboard->simpletransformers) (1.0.0)
Requirement already satisfied: grpcio>=1.24.3 in /usr/local/lib/python3.7/dist-packages (from tensorboard->simpletransformers) (1.44.0)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.7/dist-packages (from google-auth<3,>=1.6.3->tensorboard->simpletransformers) (4.8)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.7/dist-packages (from google-auth<3,>=1.6.3->tensorboard->simpletransformers) (0.2.8)

## Data Preparation

The training and test can be obtained from the Tatoeba Translation Challenge data page. You’ll also find datasets for a whole host of other languages there (including Sindarin, a language spoken by Elves in The Lord of the Rings 😀).

If you want to try training a translation model for another language, you can download the dataset for that language instead of Sinhalese. All the other steps in this article apply to any language dataset.

If you are too lazy to search for the dataset, here’s the direct link. 😜

1. Download the (compressed) translation dataset and extract the archive.
2. Extract the train.trg.gz and train.src.gz archives (yes, the training data is in archives inside archives).
3. Check whether you have thetrain.trg, train.src, test.trg, test.src files in the data/eng-sin/ directory. (If not, it’s probably easiest to move the files to this location as the code examples will assume that these files can be found here)

Now, let’s build the tsv files that we will use to train and test our mT5 model.

In [ ]:
pip install -U --no-cache-dir gdown --pre

Requirement already satisfied: gdown in /usr/local/lib/python3.7/dist-packages (4.2.2)
Collecting gdown
  Downloading gdown-4.4.0.tar.gz (14 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: tqdm in /usr/local/lib/python3.7/dist-packages (from gdown) (4.63.0)
Requirement already satisfied: six in /usr/local/lib/python3.7/dist-packages (from gdown) (1.15.0)
Requirement already satisfied: requests[socks] in /usr/local/lib/python3.7/dist-packages (from gdown) (2.23.0)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.7/dist-packages (from gdown) (4.6.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.7/dist-packages (from gdown) (3.6.0)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests[socks]->gdown) (1.25.11)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests[socks]->gdown) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests[socks]->gdown) (2021.10.8)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests[socks]->gdown) (2.10)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /usr/local/lib/python3.7/dist-packages (from requests[socks]->gdown) (1.7.1)
Building wheels for collected packages: gdown
  Building wheel for gdown (PEP 517) ... done
  Created wheel for gdown: filename=gdown-4.4.0-py3-none-any.whl size=14774 sha256=413ecc676e4d5b9286d6d93e567611a1063e9c700df94690fbeeaf66e3f012e8
  Stored in directory: /tmp/pip-ephem-wheel-cache-zrsi_xf_/wheels/fb/c3/0e/c4d8ff8bfcb0461afff199471449f642179b74968c15b7a69c
Successfully built gdown
Installing collected packages: gdown
  Attempting uninstall: gdown
    Found existing installation: gdown 4.2.2
    Uninstalling gdown-4.2.2:
      Successfully uninstalled gdown-4.2.2
Successfully installed gdown-4.4.0

In [ ]:
!gdown --id 1T6CtK1x00ffMfNvAzpTL6Ka0_3Wuevhm

/usr/local/lib/python3.7/dist-packages/gdown/cli.py:131: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  category=FutureWarning,
Downloading...
From: https://drive.google.com/uc?id=1T6CtK1x00ffMfNvAzpTL6Ka0_3Wuevhm
To: /content/scb-mt-en-th-2020.zip
100% 106M/106M [00:00<00:00, 152MB/s]

In [ ]:
# !gdown --id 1m0PRbjnn1xGE0SoE4REhi6R9NQ2bkvap

In [ ]:
!gdown --id 18J1a6YEIUFWUHtW9T6uS0h7gBJOZqxOS

/usr/local/lib/python3.7/dist-packages/gdown/cli.py:131: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  category=FutureWarning,
Downloading...
From: https://drive.google.com/uc?id=18J1a6YEIUFWUHtW9T6uS0h7gBJOZqxOS
To: /content/Official_TrainningDataset_Machine Translation.zip
100% 238M/238M [00:01<00:00, 159MB/s]

In [ ]:
%mv /content/Official_TrainningDataset_Machine\ Translation.zip /content/Official_Dataset_Machine_Translation.zip

In [ ]:
#!unzip -qq /content/scb-mt-en-th-2020.zip

In [ ]:
!unzip -qq /content/Official_Dataset_Machine_Translation.zip

In [ ]:
import os
import pandas as pd

In [ ]:
# train_df, eval_df = prepare_translation_datasets("data/eng-sin")

In [ ]:
def extract_data(file):
  f = open(file)
  x = f.read()

# # Put data in to the variable predict_x
# predict_x = x.replace("\n", " _ ")
# predict_x = predict_x.replace("\n", " ")
  output = x.split("\n")
  return output

## LST_ENTH680K Datasets

In [ ]:
path_en = '/content/TrainSet/LST_ENTH680K/lowercase/lang.en'
path_th = '/content/TrainSet/LST_ENTH680K/lowercase/lang.th'
lower_case_df = pd.DataFrame(extract_data(path_en), columns = ['en_text'])
lower_case_df['th_text'] = extract_data(path_th)
lower_case_df = lower_case_df[:681539]
lower_case_df

,en_text,th_text
0,thank you but i don't have enough time,ขอบคุณ แต่ ฉัน ไม่ มี เวลา พอ
1,"oh, you know, when i get up i usually do my st...","โอ้ , คุณ รู้ , เมื่อ ฉัน ตื่น ฉัน จะ ออกไป เด..."
2,the duty of a policeman is to safeguard people .,หน้าที่ ของ ตำรวจ คือ การ ปกป้อง ประชาชน
3,it's female vanity.,มัน เป็นความ โอหัง ของ เพศ หญิง .
4,please keep a sharp lookout .,โปรด คอย ดู อย่า เผลอ
...,...,...
681534,"when wijai talked to me on the phone , his voi...",ตอน วิจัย พูด โทรศัพท์ กับ ดิฉัน เสียง เขา แตก...
681535,the bus terminal is on the west side of the ci...,สถานี รถ โดยสาร ทาง ตะวันตก ของ เมือง
681536,encapsulate,ลักษณะ ภาย นอก
681537,"death frightens me , specifically my own death .",ความ ตาย ทำ ให้ ผม กลัว โดย เฉพาะอย่างยิ่ง การ...
681538,i weigh sixty kilograms.,ฉัน หนัก หก สิบ กิโลกรัม .

# Unused Datasets

## Bible Datasets

In [ ]:
path_en = '/content/TrainSet/OPUS_BiTextCollections/Bible/bible-uedin.en-th.en'
path_th = '/content/TrainSet/OPUS_BiTextCollections/Bible/bible-uedin.en-th.th'
Bible_df = pd.DataFrame(extract_data(path_en), columns = ['en_text'])
Bible_df['th_text'] = extract_data(path_th)
Bible_df

,en_text,th_text
0,In the beginning God created the heavens and t...,ในเริ่มแรกนั้นพระเจ้าทรงเนรมิตสร้างฟ้าและแผ่นด...
1,Now the earth was formless and empty. Darkness...,แผ่นดินโลกนั้นก็ปราศจากรูปร่างและว่างเปล่าอยู่...
2,"God said, ""Let there be light,"" and there was ...",วัน ที่ หนึ่ง ปรากฏ มีค วาม สว่าง เกิด ขึ้น พร...
3,"God saw the light, and saw that it was good. G...",พระเจ้า ทรง เห็น ว่าความ สว่าง นั้น ดี และ พระ...
4,"God called the light ""day,"" and the darkness h...",พระเจ้า ทรง เรียก ความ สว่าง นั้น ว่า วัน และ ...
...,...,...
124382,For I testify unto every man that heareth the ...,ข้าพเจ้าเป็นพยานแก่ทุกคนที่ได้ยินคำพยากรณ์ในหน...
124383,And if any man shall take away from the words ...,และถ้าผู้ใดตัดข้อความออกจากหนังสือพยากรณ์นี้ พ...
124384,"He which testifieth these things saith, Surely...",คำทรงเตือนและพระสัญญาว่าพระคริสต์จะเสด็จมาพระอ...
124385,The grace of our Lord Jesus Christ be with you...,ขอให้พระคุณแห่งพระเยซูคริสต์องค์พระผู้เป็นเจ้า...
124386,,

## GNOME Datasets

In [ ]:
path_en = '/content/TrainSet/OPUS_BiTextCollections/GNOME/GNOME.en-th.en'
path_th = '/content/TrainSet/OPUS_BiTextCollections/GNOME/GNOME.en-th.th'
GNOME_df = pd.DataFrame(extract_data(path_en), columns = ['en_text'])
GNOME_df['th_text'] = extract_data(path_th)
GNOME_df

,en_text,th_text
0,Accerciser,Accerciser
1,Give your application an accessibility workout,ช่วยพัฒนาสิ่งอำนวยความสะดวกในโปรแกรมของคุณ
2,Accerciser Accessibility Explorer,Accerciser: เครื่องมือสำรวจสิ่งอำนวยความสะดวก
3,The default plugin layout for the bottom panel,การจัดวางปลั๊กอินสำหรับช่องด้านล่าง
4,The default plugin layout for the top panel,การจัดวางปลั๊กอินสำหรับช่องด้านบน
...,...,...
74,Rows,จำนวนแถว
75,Table Information,ข้อมูลตาราง
76,"name (x,y)","ชื่อ (x,y)"
77,Header:,หัวตาราง:
78,,

## JW300 Datasets

In [ ]:
path_en = '/content/TrainSet/OPUS_BiTextCollections/JW300/jw300.en'
path_th = '/content/TrainSet/OPUS_BiTextCollections/JW300/jw300.th'
JW300_df = pd.DataFrame(extract_data(path_en), columns = ['en_text'])
JW300_df['th_text'] = extract_data(path_th)
JW300_df

,en_text,th_text
0,,อนาคต ​ ของ ​ ศาสนา ​ จาก ​ การ ​ พิจารณา ​ ศา...
1,Religion’s Future in View of Its Past,ตอน ​ ที่ 13 : จาก ส .
2,Part 13 ​ — 476 C.E . onward ​ — Out of Darkne...,ศ . 476 เป็น ​ ต้น ​ มา — สิ่ง ​ ที่ ​ ถือ ​ ว...
3,“ Sins committed in the dark are seen in Heave...,“ บาป ​ ซึ่ง ​ ได้ ​ กระทำ ​ ใน ​ ที่ ​ มืด ​ ...
4,IN APRIL 1988 the Church in the Soviet Union r...,เดือน ​ เมษายน 1988 คริสต์ ​ จักร ​ ใน ​ สหภาพ...
...,...,...
818625,Summarize key points in the material to help y...,คุณ ​ เห็น ​ อะไร ได้ ​ ยิน ​ อะไร และ ​ ได้ ​...
818626,Is there something you can use in your ministr...,ลอง ​ สมมุติ ​ ว่า ​ คุณ ​ เป็น ​ ตัว ​ ละคร ​...
818627,,ใช้ ​ เครื่อง ​ มือ ​ ของ ​ องค์การ ​ เพื่อ ​ ...
818628,,สรุป ​ จุด ​ สำคัญ การ ​ ทำ ​ อย่าง ​ นี้ ​ จะ...
818629,,

## OpenSubtitles Datasets

In [ ]:
path_en = '/content/TrainSet/OPUS_BiTextCollections/OpenSubtitles/OpenSubtitles.en-th.en'
path_th = '/content/TrainSet/OPUS_BiTextCollections/OpenSubtitles/OpenSubtitles.en-th.th'
opensub_df = pd.DataFrame(extract_data(path_en), columns = ['en_text'])
opensub_df['th_text'] = extract_data(path_th)
opensub_df

,en_text,th_text
0,"Slave in the Magic Mirror, come from the farth...","ทาสในกระจกวิเศษ, มาจากพื้นที่ที่ไกลที่สุด"
1,"Through wind and darkness, I summon thee.",ผ่านลมและความมืดฉันเรียกเจ้า
2,Speak!,พูด!
3,Let me see thy face.,ให้ฉันเห็นพระพักตร์ของ พระองค์
4,"What wouldst thou know, my Queen?",สิ่งที่เจ้าจะรู้ว่าสมเด็จพระราชินี ของฉันได้อย...
...,...,...
3281529,MY LADIES BY SHIN MICHIMA,(เหล่าสุภาพสตรีของผม โดย มิชิมะ ชิน)
3281530,THIS DRAMA IS FICTIONAL.,(ภาพยนตร์ชุดนี้เป็นเรื่องแต่ง)
3281531,ALL CHARACTERS AND ORGANIZATIONS IN IT ARE FIC...,(ตัวละครและองค์กรในเรื่อง ล้วนเป็นเรื่องแต่ง)
3281532,Subtitle translation by Brian Athey,คำบรรยายโดย:
3281533,,

## QED Datasets

In [ ]:
path_en = '/content/TrainSet/OPUS_BiTextCollections/QED/QED.en-th.en'
path_th = '/content/TrainSet/OPUS_BiTextCollections/QED/QED.en-th.th'
qed_df = pd.DataFrame(extract_data(path_en), columns = ['en_text'])
qed_df['th_text'] = extract_data(path_th)
qed_df

,en_text,th_text
0,This is the same problem that we had in the la...,นี่คือปัญหาข้อเดิมที่เราทำในวิดีโอที่แล้ว
1,But instead of trying to figure out whether th...,แต่แทนที่จะหาว่าข้อมูล ที่ได้มาเป็นหลักฐานเพีย...
2,So you could ignore the question right here.,คุณลืมคำถามที่แล้วไปได้
3,You can ignore all of this.,คุณทิ้งทั้งหมดนี่ไป
4,I'm just using that same data to come up with ...,ผมแค่ใช้ข้อมูลเดิมที่มี เพื่อสร้างช่วง ความมั่...
...,...,...
264673,"So anyway, I didn't want to appear defensive, ...",เอาล่ะ ผมไม่อยากปกป้องตัวเอง แต่ผม อยากทำให้ทุ...
264674,Because I don't want to in any way blame those...,เพราะผมอยากให้ใครว่าคนที่คิดว่า บทพิสูจน์เดิมข...
264675,It's my fault because I didn't explain it prop...,ผมผิดเองที่ไม่ได้อธิบายให้ชัด
264676,So hopefully this should provide a little bit ...,งั้นหวังว่านี่คงช่วย ให้เรื่องนี้กระจ่างขึ้น -
264677,,

## Tanzil Datasets

In [ ]:
path_en = '/content/TrainSet/OPUS_BiTextCollections/Tanzil/Tanzil.en-th.en'
path_th = '/content/TrainSet/OPUS_BiTextCollections/Tanzil/Tanzil.en-th.th'
tanzil_df = pd.DataFrame(extract_data(path_en), columns = ['en_text'])
tanzil_df['th_text'] = extract_data(path_th)
tanzil_df

,en_text,th_text
0,"In the name of Allah, most benevolent, ever-me...",ด้วยพระนามของอัลลอฮฺ ผู้ทรงกรุณาปราณี ผู้ทรงเม...
1,"ALL PRAISE BE to Allah, Lord of all the worlds,",การสรรเสริญทั้งหลายนั้น เป็นสิทธิของอัลลอฮฺผู้...
2,"Most beneficent, ever-merciful,",ผู้ทรงกรุณาปราณี ผู้ทรงเมตตาเสมอ
3,King of the Day of Judgement.,ผู้ทรงอภิสิทธิ์แห่งวันตอบแทน
4,"You alone we worship, and to You alone turn fo...",เฉพาะพระองค์เท่านั้นที่พวกข้าพระองค์เคารพอิบาด...
...,...,...
93536,"The god (or judge) of Mankind,-",พระเป็นเจ้าแห่งมนุษย์ชาติ
93537,"From the mischief of the Whisperer (of Evil), ...",ให้พ้นจากความชั่วร้ายของผู้กระซิบกระซาบที่หลอกล่อ
93538,(The same) who whispers into the hearts of Man...,ที่กระซิบกระซาบในหัวอกของมนุษย์
93539,Among Jinns and among men.,จากหมู่ญินและมนุษย์
93540,,

## Tatoeba

In [ ]:
path_en = '/content/TrainSet/OPUS_BiTextCollections/Tatoeba/Tatoeba.en-th.en'
path_th = '/content/TrainSet/OPUS_BiTextCollections/Tatoeba/Tatoeba.en-th.th'
tatoeba_df = pd.DataFrame(extract_data(path_en), columns = ['en_text'])
tatoeba_df['th_text'] = extract_data(path_th)
tatoeba_df

,en_text,th_text
0,Let's try something.,ลองทำดู!
1,Let's try something.,มาลองบางอย่างกันเถอะ
2,Let's try something.,ลองทำอะไรสักอย่างกัน
3,I have to go to sleep.,ฉันต้องไปนอนแล้ว
4,Today is June 18th and it is Muiriel's birthday!,วันนี้วันที่ 18 มิถุนายน และมันก็เป็นวันเกิดขอ...
...,...,...
1077,Who does your laundry for you?,ใครซักเสื้อผ้าของคุณให้คุณ
1078,How much would you charge me to do my laundry ...,คุณคิดค่าบริการฉันเท่าไรสำหรับการซักรีดให้ฉัน
1079,Do you do your own laundry?,คุณซักรีดเสื้อผ้าของตัวเองหรือไม่?
1080,I'm looking for someone to do my laundry for me.,ฉันกำลังมองหาคนซักเสื้อผ้าสำหรับฉัน
1081,,

## Ubuntu Datasets

In [ ]:
path_en = '/content/TrainSet/OPUS_BiTextCollections/Ubuntu/Ubuntu.en-th.en'
path_th = '/content/TrainSet/OPUS_BiTextCollections/Ubuntu/Ubuntu.en-th.th'
Ubuntu_df = pd.DataFrame(extract_data(path_en), columns = ['en_text'])
Ubuntu_df['th_text'] = extract_data(path_th)
Ubuntu_df

                                  en_text                   th_text
0                           locale noexpr             locale noexpr
1                          locale yesexpr            locale yesexpr
2                  --help" and "--version    --help" and "--version
3                     AisleRiot Solitaire          ถอดไพ่ AisleRiot
4     Play many different solitaire games    เล่นเกมถอดไพ่สารพัดแบบ
...                                   ...                       ...
3781              Set a horizontal layout        ใช้การจัดวางแนวนอน
3782                     _Vertical Layout            จัดวางแนว_ตั้ง
3783                Set a vertical layout       ใช้การจัดวางแนวตั้ง
3784         Click to close the side pane  คลิกเพื่อปิดช่องด้านข้าง
3785

[3786 rows x 2 columns]

## SCB MT DATASETS

In [ ]:
apdf_df =pd.read_csv('/content/scb-mt-en-th-2020/apdf.csv')
apdf_df

,en_text,th_text
0,FAR LEFT: Indonesian National Police Chief Tit...,(ซ้ายสุด) นายติโต คาร์นาเวียน ผู้บัญชาการตำรวจ...
1,(Pictured: A rocket believed to be a Hwasong m...,(ภาพ: จรวดซึ่งเชื่อว่าเป็นขีปนาวุธฮวาซองเช่นเด...
2,"(Pictured: From left, Indian Air Commander Ak ...",(ภาพ: จากซ้าย นายอัค โชราเชีย ผู้บัญชาการทางอา...
3,"(Pictured: Left to right, Australia’s Defence ...",(ภาพ: จากซ้ายไปขวา นางมารีส เพย์น รัฐมนตรีว่าก...
4,(Pictured: A man watches the live-stream trans...,(ภาพ: ชายคนหนึ่งชมการแพร่ภาพออกอากาศสดการปล่อย...
...,...,...
13498,“It is not easy because we are 10 different co...,“ไม่ใช่เรื่องง่ายเลย เพราะเราเป็น 10 ประเทศที่...
13499,“It is not always that we’ve had the privilege...,“ไม่ได้มีบ่อยครั้งที่เรามีโอกาสพิเศษที่จะได้ให...
13500,"“There haven’t been many problems so far,” Kim...",“ไม่ได้มีปัญหามากนักจนถึงขณะนี้” นายคิมกล่าวสร...
13501,"“To fill the gap, more NCOs and COs can be a g...",” การเพิ่มจำนวนนายทหารชั้นประทวนและนายทหารสัญญ...
13502,"• At a huge military parade in October 2015, K...",• ระหว่างการเดินแปรขบวนทางทหารที่ยิ่งใหญ่ในเดื...

In [ ]:
assgov_df =pd.read_csv('/content/scb-mt-en-th-2020/assorted_government.csv')
assgov_df

,en_text,th_text
0,Reinvigorating Technical Cooperation for Susta...,เสริมสร้างความร่วมมือทางวิชาการสำหรับการพัฒนาอ...
1,Strengthening Cooperation for Peace and Security,เสริมสร้างความร่วมมือเพื่อสันติภาพและความมั่นคง
2,Engaging the Region and the World,ปฏิสัมพันธ์กับภูมิภาคและโลก
3,Advancing Thailand – Viet Nam Strategic Partne...,ส่งเสริมความเป็นหุ้นส่วนทางยุทธศาสตร์ระหว่างไท...
4,4. Further inquiries can be directed to:,๔. หากมีข้อสอบถามเพิ่มเติม โปรดติดต่อได้ที่
...,...,...
25393,If offender in accordance with first paragraph...,ถ้าผู้กระทำความผิดตามวรรคแรกหรือวรรคสองเป็นผู้...
25394,Offences Relating to Cause Public Dangers as p...,(1) ความผิดเกี่ยวกับการก่อให้เกิดภยันตรายต่อปร...
25395,If the offence being committed under any of th...,ถ้าความผิดนั้นมีลักษณะประการหนึ่งประการใดดังที...
25396,In determination of period of the hour time on...,ในการกำหนดระยะเวลาทำงานแทนค่าปรับตามวรรคสาม ให...
25397,If the commission of the offence as mentioned ...,ถ้าการกระทำความผิดดังกล่าวในวรรคแรก เป็นเหตุให...

Warning: total number of rows (25398) exceeds max_rows (20000). Limiting to first (20000) rows.

In [ ]:
wiki_df = pd.read_csv('/content/scb-mt-en-th-2020/wikipedia.csv')
wiki_df

,en_text,th_text
0,Palestine at the 2004 Summer Olympics,ปาเลสไตน์ในโอลิมปิกฤดูร้อน 2004
1,Palestine competed at the 2004 Summer Olympics...,ปาเลสไตน์ในโอลิมปิกฤดูร้อน 2004 ปาเลสไตน์ เข้า...
2,Pakistan at the 2004 Summer Olympics,ประเทศปากีสถานในโอลิมปิกฤดูร้อน 2004
3,Pakistan competed at the 2004 Summer Olympics ...,ประเทศปากีสถานในโอลิมปิกฤดูร้อน 2004 ประเทศปาก...
4,Sri Lanka at the 2004 Summer Olympics,ประเทศศรีลังกาในโอลิมปิกฤดูร้อน 2004
...,...,...
33751,1968 in Portugal Events in the year 1968 in Po...,ประเทศโปรตุเกสใน ค.ศ. 1968 เหตุการณ์ที่เกิดขึ้...
33752,The following lists events that happened durin...,ประเทศโปรตุเกสใน ค.ศ. 2000 เหตุการณ์ที่เกิดขึ้...
33753,1994 in Portugal Events in the year 1994 in Po...,ประเทศโปรตุเกสใน ค.ศ. 1994 เหตุการณ์ที่เกิดขึ้...
33754,1998 in Portugal Events in the year 1998 in Po...,ประเทศโปรตุเกสใน ค.ศ. 1998 เหตุการณ์ที่เกิดขึ้...
33755,Hemiorchis is a genus of plants in the ginger ...,Hemiorchis เป็นสกุลของพืชในวงศ์ขิง มีสมาชิก 3 ...

In [ ]:
thweb_df = pd.read_csv('/content/scb-mt-en-th-2020/thai_websites.csv')
thweb_df

,en_text,th_text
0,CLARINS This intensive replenishing cream hel...,คืนความยืดหยุ่นให้ผิวที่ร่วงโรยตามวัย จากการเป...
1,ONLY@CENTRAL Color : Almond Size : 32 A UK Ca...,ONLY@CENTRAL สี : เบจไซส์ : 32 A UK หมายเหตุ:...
2,ONLY@CENTRAL Color : Almond Size : 32 B UK Ca...,ONLY@CENTRAL สี : เบจไซส์ : 32 B UK หมายเหตุ:...
3,ONLY@CENTRAL Color : Almond Size : 32 C UK Ca...,ONLY@CENTRAL สี : เบจไซส์ : 32 C UK หมายเหตุ:...
4,ONLY@CENTRAL Color : Almond Size : 34 A UK Ca...,ONLY@CENTRAL สี : เบจไซส์ : 34 A UK หมายเหตุ:...
...,...,...
120275,・Clear Lotion：After face washing apply an appr...,・เคลียร์โลชั่น：ใช้หลังล้างหน้า เทลงบนสำลีแผ่นพ...
120276,﻿﻿﻿Here is a charming take-along castle perfec...,ชุดปราสาทเจ้าหญิง จาก MELISSA & DOUG ที่มาพร้อ...
120277,﻿﻿﻿﻿﻿Give little builders all the tools they n...,ช่างก่อสร้างตัวน้อยกับไอเดียสุดเจ๋ง จะทำให้งาน...
120278,﻿﻿﻿﻿﻿﻿Everyone likes getting letters! Sending ...,เล่นสวมบทบาทเป็นบุรุษไปรษณีย์ ด้วยชุดของเล่นส่...
120279,＊Applicants from certain countries may be requ...,ประเภทวีซ่า รวมถึงค่าธรรมเนียม และข้อกำหนดในกา...

In [ ]:
tskmaster_df = pd.read_csv('/content/scb-mt-en-th-2020/task_master_1.csv')
tskmaster_df

,en_text,th_text
0,"Hi, I'm looking to book a table for Korean fod.",สวัสดีค่ะ ช่วยจองร้านอาหารเกาหลีให้หน่อยได้มั้...
1,"Ok, what area are you thinking about?",ได้เลยค่ะ แถวไหนดีคะ?
2,"Somewhere in Southern NYC, maybe the East Vill...",แถว ๆ นิวยอร์คทางใต้ก็ได้ค่ะ แถวอีสต์วิลเลจอะไ...
3,"Ok, great. There's Thursday Kitchen, it has gr...",โอเคค่ะ ดีเลย มีร้านเธอร์เดย์คิทเช่นอยู่ รีวิว...
4,That's great. So I need a table for tonight at...,เยี่ยมค่ะ อยากได้โต๊ะแปดคนตอนทุ่มนึงค่ะ นั่งตร...
...,...,...
222728,did you want thick crust for all 3 pizzas?,ขอบหนาทั้ง 3 ถาดเลยมั้ยคะ
222729,"you said you want to order 3 large pizzas, all...",สรุปเป็นพิซซ่าไซส์ใหญ่สามถาดนะคะ ทุกถาดพิเศษชี...
222730,the total for your order is $56.44.,ราคาทั้งหมด 56.44 เหรียญค่ะ
222731,"Yes, can you make that for pickup, please?",ค่ะ เป็นออเดอร์สำหรับไปรับที่ร้านนะคะ
222732,"great, i've submitted your order for pick up. ...",โอเคค่ะ ส่งออเดอร์สำหรับรับที่ร้านเรียบร้อยแล้...

In [ ]:
paracrawl_df = pd.read_csv('/content/scb-mt-en-th-2020/paracrawl.csv')
paracrawl_df

,en_text,th_text
0,We are open to new proposals.,เราจะเปิดให้ข้อเสนอใหม่
1,Big lottery jackpots in the rear,รางวัลจับสลากใหญ่ในด้านหลัง
2,Car rental tips for Bangkok Airport,เคล็ดลับการเช่ารถสำหรับ กรุงเทพมหานคร ท่าอากาศยาน
3,visible structure moving along the wall.,โครงสร้างที่มองเห็นได้ย้ายตามผนัง
4,Price List by Duration of Stay,รายการค่าใช้จ่ายตามระยะเวลาของคอร์ส
...,...,...
60034,Where are the last two weeks in advance? Our t...,ที่ไหนในสองสัปดาห์ที่ผ่านมาจะออก? เวลาของเราใน...
60035,"After a good night we set her on the van, invi...","หลังจากที่พักผ่อนสบายตลอดคืนที่เราไปมาทั่วแวน,..."
60036,"The question is, what is better - or granite t...",คำถามคือสิ่งที่ดีกว่า - หินแกรนิตหรือกระเบื้อง...
60037,Matches Fashion Luxury Shopping in the event y...,ตรงกับแฟชั่นหรูหราชอปปิ้งอยู่ในเหตุการณ์คุณยัง...
60038,2020 Fine Food Australia is the largest F&B ex...,2020 Fine Food Australia เป็นงานแสดงสินค้าอาหา...

In [ ]:
nussms_df = pd.read_csv('/content/scb-mt-en-th-2020/nus_sms.csv')
nussms_df

,en_text,th_text
0,"He is out for work, donot disturb. kindly call...",เขาไปทำธุระข้างนอก กรุณาโทรหาเขา 5 นาทีหลังจาก...
1,Huh u still doing yest tut... I tot u finish l...,นี่ นายทำไปถีงไหนแล้ว ฉันคิดว่านายทำเสร็จแล้วซ...
2,No need 2 b paisei w me lar... U mus eat more ...,ไม่ต้องมาทำเป็นอายอะไรกับฉันนักหรอก แกกินเข้าไ...
3,Yar lor... U not ard then i v lonely lor... He...,กินเถอะ เธอไม่กิน ฉันก็เหงาแย่สิ นี่ เธอไม่กิน...
4,Of course got use lah. U must jia you k. 2 mor...,ตกลงตามนั้นน่ะ นายจะสนุกมาก ถ้าเพิ่มอีกสัก 2 วัน
...,...,...
43745,mornin. u n jessen on rite? i mean on chris ev...,หวัดดีตอนเช้า เธอกับเจนเซ่นยังมาใช่ไหม ฉันหมาย...
43746,"you always talk-cock, so black-listed",เธอชอบพูดไร้สาระ เลยโดนขึ้นบัญชีดำ
43747,re 8th out of 16 teams,ลำดับที่ 8 จากทั้งหมด 16 ทีม
43748,"s great man,you keep up the good work yeah",นายยอดมาก ยังรักษาผลงานได้ดีเสมอ
43749,Haha... Ez rite... At yio chu kang?,ฮ่าฮ่าฮ่า...พิธีกรรมแสนง่ายที่สถานีรถไฟในสิงคโ...

In [ ]:
msr_df = pd.read_csv('/content/scb-mt-en-th-2020/msr_paraphrase.csv')
msr_df

,en_text,th_text
0,"Just as before, it will be up to the Council t...",เช่นเดียวกับเมื่อก่อน สภาเป็นผู้ที่จะตัดสินใจท...
1,"In December, he had predicted a 5 percent grow...",ในเดือนธันวาคม เขาคาดว่าจะมีอัตราการเติบโต 5 เ...
2,"Character actor Hume Cronyn, 91, died Sunday a...",นักแสดงระดับตำนาน ฮูม โครนีน เสียชีวิตในวัย 91...
3,"On May 22, 2002, a man walking his dog came ac...",เมื่อวันที่ 22 พฤษภาคม 2002 ชายคนหนึ่งพบกระดูก...
4,The bodies of 18 illegal Mexican immigrants wh...,ร่างของผู้อพยพชาวเม็กซิกัน 18 คนที่เสียชีวิตเน...
...,...,...
10366,"""Events on our system, in and of themselves, c...",“สิ่งที่เกิดขึ้นในระบบของเรา ทั้งในและด้วยตัวข...
10367,"Handset market share for the second quarter, i...",ส่วนแบ่งการตลาดของอุปกรณ์พกพาในไตรมาสที่สอง มั...
10368,An attempt last month in the Senate to keep th...,ความพยายามในเดือนที่ผ่านมาในวุฒิสภาเพื่อให้กอง...
10369,"Writing for the minority, Justice John Paul St...",เขียนเพื่อชนกลุ่มน้อย ผู้พิพากษา John Paul Ste...
10370,Apple Computer Inc. said Monday it exceeded re...,Apple Computer Inc. เปิดเผยเมื่อวันจันทร์ว่า ไ...

In [ ]:
mcv_df = pd.read_csv('/content/scb-mt-en-th-2020/mozilla_common_voice.csv')
mcv_df

,en_text,th_text
0,"The fool wanders, the wise man travels.",คนโง่พเนจร คนฉลาดท่องเที่ยว
1,One of these days is none of these days.,หนึ่งในวันเหล่านี้คือไม่มีวันเหล่านี้เลย
2,"Necessity is a hard nurse, but she raises stro...","ความจำเป็นเป็นสิ่งที่ยาก, แต่เธอสามารถเลี้ยงลู..."
3,In one ear and out the other.,เข้าหู้ข้างหนึ่งและออกอีกข้างหนึ่ง
4,It can't happen here is number one on the list...,ไม่สามารถเกิดขึ้นที่นี่ได้คือคำพูดสุดท้ายที่ดั...
...,...,...
33792,"If you can't help, don't hinder.",หากคุณไม่สามารถช่วยได้อย่าขัดขวาง
33793,It's all in a days work.,ทำงานทั้งวัน
33794,Laziness travels so slowly that poverty soon o...,ความเกียจคร้านเดินทางช้ามากจนความยากจนมาถึงในไ...
33795,Pushchairs can be folded when the toddler want...,สามารถพับเก็บเก้าอี้ลงได้เมื่อทารกต้องการเดิน
33796,Quantum computing machines are rare and hard t...,เครื่องคำนวณควอนตัมทั้งนั้นหายากและผลิตได้ยาก

In [ ]:
gen_yn = pd.read_csv('/content/scb-mt-en-th-2020/generated_reviews_yn.csv')
gen_yn

,en_text,th_text
0,We are trying to use them on our Samsung Smart...,เรากำลังพยายามใช้พวกเขาบน Samsung Smart TV ของเรา
1,This thing will not work with Mac OSX 10.4.7.1.,สิ่งนี้จะไม่ทำงานกับ Mac OSX 10.4.7.1
2,We are very happy with our Dyson DC25.,เรามีความสุขมากกับ Dyson DC25 ของเรา
3,It doesn't work with Skype.,มันไม่ทำงานกับ Skype
4,I'll be looking at Cisco next.,ฉันจะดู Cisco ต่อไป
...,...,...
280203,Disappointed also when my credit card company ...,ผิดหวังเมื่อ บริษัท บัตรเครดิตของฉันปฏิเสธการค...
280204,"No explanation, just no response.",ไม่มีคําอธิบายไม่มีคําตอบ
280205,Not happy at all with this experience.,ไม่มีความสุขเลยกับประสบการณ์นี้
280206,Will stay away from ordering books on Amazon i...,จะอยู่ห่างจากการสั่งซื้อหนังสือใน Amazon ในอนาคต
280207,My husband is a mechanic so he has worked for ...,สามีของฉันเป็นช่างเขาจึงทํางานให้กับผู้ผลิตรถย...

In [ ]:
gen_trans = pd.read_csv('/content/scb-mt-en-th-2020/generated_reviews_translator.csv')
gen_trans

,en_text,th_text
0,These are a terrible product from China.The li...,สินค้าพวกนี้เป็นสินค้าห่วยๆที่มาจากประเทศจีน ท...
1,They can't be used for anything other than par...,ไม่สามารถใช้ทำอะไรได้มากกว่าใช้ประดับในงานเลี้ยง
2,"And yes, I followed directions exactly as they...",และแน่นอนว่าฉันได้ทำตามแนวทางที่เขาเขียนไว้อย่...
3,What kind of trash can cannot survive simple h...,กระป๋องขยะประเภทไหนกันที่ไม่สามารถใช้งานง่ายๆใ...
4,I'm returning them.,ฉันจะส่งสินค้าพวกนี้กลับค่ะ
...,...,...
133325,The songs are well known and the sound quality...,เพลงเป็นที่รู้จักกันดีและคุณภาพเสียงก็ยอดเยี่ยม
133326,I think it might be more important these days ...,ฉันคิดว่ามันอาจจะสำคัญกว่าในทุกวันนี้ที่จะกลับ...
133327,"If that's not what you want, buy this CD.",ถ้านั่นไม่ใช่สิ่งที่คุณต้องการซื้อซีดีนี้
133328,It brings me back 20 years when we used to lis...,มันทำให้ฉันย้อนกลับไป 20 ปีเมื่อเราเคยฟัง John...
133329,My friends can't stop asking where they can bu...,ดีใจมากที่หาซื้อได้ เพื่อน ๆ ถามกันใหญ่เลยค่ะว...

In [ ]:
gen_crowd = pd.read_csv('/content/scb-mt-en-th-2020/generated_reviews_crowd.csv')
gen_crowd

,en_text,th_text
0,Doesn't snap together well.,เข้ากันไม่ค่อยดี
1,Charged it after every use as directed for abo...,เรียกเก็บเงินหลังจากใช้งานทุกครั้งตามที่กำกับไ...
2,"My son wanted this movie so badly, that he sai...",ลูกชายของฉันต้องการภาพยนตร์เรื่องนี้เพื่อไม่ดี...
3,But his writing has degenerated in later books.,แต่หนังสือเล่มที่ผ่านมาของเขามันดูด้อยคุณภาพลง
4,"It was supposed to be a good bag, well you get...",มันควรที่จะเป็นกระเป๋าที่ดี เอ้อ เธอได้ในสิ่งท...
...,...,...
24582,This stuff just tastes awful.,สินค้าชิ้นนี้แย่มาก
24583,I would not have bought this if my son hadn't ...,ฉันไม่ชอบซื้อเวลาที่ลูกชายทำไม่เสร็จ
24584,But when you end up with a tape full of shows ...,แต่เมื่อคุณจบลงด้วยเทปเต็มรูปแบบของการแสดงเช่น...
24585,"But the ""e-version"" is very hard to use.",แต่เวอร์ชั่น E ใช้งานยาก
24586,This is not for beginners.,นี่ไม่ใช่สำหรับมือใหม่

Running the code above will write the two files, train.tsv and eval.tsv, to the data/ directory.

# Convert to MT5 STF Format Function

## All Data

In [ ]:
frames = [lower_case_df] #Ubuntu_df , qed_df, tanzil_df, tatoeba_df,  Bible_df, GNOME_df, JW300_df, opensub_df
all_df = pd.concat(frames)

In [ ]:
def convert_df_to_format(input_df):
  data = []
  for row, series in input_df.iterrows():
    data.append(["translate thai to english", series['th_text'], series['en_text']])
    # data.append(["translate english to thai", series['en_text'], series['th_text']])
  output_df = pd.DataFrame(data, columns=["prefix", "input_text", "target_text"])
  return output_df

In [ ]:
# Test convert function
all_formatted = convert_df_to_format(all_df)
all_formatted

,prefix,input_text,target_text
0,translate thai to english,ขอบคุณ แต่ ฉัน ไม่ มี เวลา พอ,thank you but i don't have enough time
1,translate thai to english,"โอ้ , คุณ รู้ , เมื่อ ฉัน ตื่น ฉัน จะ ออกไป เด...","oh, you know, when i get up i usually do my st..."
2,translate thai to english,หน้าที่ ของ ตำรวจ คือ การ ปกป้อง ประชาชน,the duty of a policeman is to safeguard people .
3,translate thai to english,มัน เป็นความ โอหัง ของ เพศ หญิง .,it's female vanity.
4,translate thai to english,โปรด คอย ดู อย่า เผลอ,please keep a sharp lookout .
...,...,...,...
681534,translate thai to english,ตอน วิจัย พูด โทรศัพท์ กับ ดิฉัน เสียง เขา แตก...,"when wijai talked to me on the phone , his voi..."
681535,translate thai to english,สถานี รถ โดยสาร ทาง ตะวันตก ของ เมือง,the bus terminal is on the west side of the ci...
681536,translate thai to english,ลักษณะ ภาย นอก,encapsulate
681537,translate thai to english,ความ ตาย ทำ ให้ ผม กลัว โดย เฉพาะอย่างยิ่ง การ...,"death frightens me , specifically my own death ."
681538,translate thai to english,ฉัน หนัก หก สิบ กิโลกรัม .,i weigh sixty kilograms.

In [ ]:
# all_formatted1 = all_formatted
# all_formatted1

## Model Load

In [ ]:
import logging
import pandas as pd
from simpletransformers.t5 import T5Model, T5Args


logging.basicConfig(level=logging.INFO)
transformers_logger = logging.getLogger("transformers")
transformers_logger.setLevel(logging.WARNING)

# Model Training

Once we have the data files, we are ready to start training the model.

First, we’ll import the necessary stuff and set up logging.

Next, we set up our training and evaluation data.

Here, we remove the prefix values from the datasets because we expect the model to infer the required task based on the input. If the input is in English, then it should be translated to Sinhalese. If it’s in Sinhalese, then it should be translated to English. The model shouldn’t need a prefix to figure this out after the training!

You can use a prefix value to tell an mT5 (or T5) to perform a specific task. This is quite useful to train a model which can perform multiple tasks, as shown in the article below.

**Sidenote on GPU memory usage**

The amount of GPU memory required to train a Transformer model depends on many different factors (maximum sequence length, number of layers, number of attention heads, size of the hidden dimensions, size of the vocabulary, etc.). Out of these, the maximum sequence length of the model is one of the most significant.

For the self-attention mechanisms used in the mT5 model, the memory requirement grows quadratically with the input sequence length (O(n²) space complexity). I.e., When the sequence length doubles, the memory required quadruples.

Also, mT5 has a much larger vocabulary than T5 (~250,000 tokens to ~32,000 tokens), contributing to mT5 being quite punishing in terms of GPU memory required.

The takeaway from all this is that the number of tokens we can input to the model (the maximum sequence length) comes at a hefty premium. Based on this, it’s wasteful to use even a small number of tokens on the prefix if the model can do without.

Now, let’s get back to training the model!

In [ ]:
from google.colab import drive
drive.mount('/content/mydrive/')

Drive already mounted at /content/mydrive/; to attempt to forcibly remount, call drive.mount("/content/mydrive/", force_remount=True).

In [ ]:
model_args = T5Args()
model_args.max_seq_length = 96
model_args.train_batch_size = 8
#model_args.eval_batch_size = 4
model_args.num_train_epochs = 1
model_args.evaluate_during_training = False
#model_args.evaluate_during_training_steps = 200
model_args.use_multiprocessing = False
model_args.fp16 = False
model_args.save_steps = -1
model_args.save_eval_checkpoints = False
model_args.no_cache = True
model_args.reprocess_input_data = True
model_args.overwrite_output_dir = True
model_args.preprocess_inputs = False
model_args.num_return_sequences = 1
#model_args.wandb_project = "MT5 Sinhala-English Translation"

model = T5Model("mt5", "google/mt5-base", args=model_args)

Downloading:   0%|          | 0.00/702 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/2.17G [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/4.11M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/65.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/376 [00:00<?, ?B/s]

Here, we specify how we want the model to be set up and initialize the pre-trained mT5 model according to model_args.

I’m using a maximum sequence length (max_seq_length) of 96 and a train/eval batch sizes of 20. Generally, larger batch sizes mean better GPU utilization, and therefore, shorter training times. As mentioned earlier, longer sequences require more GPU memory, which means smaller batch sizes and longer training times. The maximum sequence length of 96 allows the model to work with reasonably long text (typically a few sentences) while also keeping the training time practical.

Note that you may need to tweak these values to train the model on your own GPU. If you run out of GPU memory (CUDA memory error), try reducing the batch sizes and/or the maximum sequence length.

If you want to try the fine-tuned model, you can find it here on the Huggingface model hub.

Now, to run the training, we just need to call the train_model() method.

In [ ]:
type(train_df)

pandas.core.frame.DataFrame

In [ ]:
# Train the modelllllll
%%timeit
model.train_model(all_formatted)  #(train_df, eval_data=eval_df)

INFO:simpletransformers.t5.t5_utils: Creating features from dataset file at cache_dir/

  0%|          | 0/681539 [00:00<?, ?it/s]

/usr/local/lib/python3.7/dist-packages/transformers/tokenization_utils_base.py:3524: FutureWarning:
`prepare_seq2seq_batch` is deprecated and will be removed in version 5 of HuggingFace Transformers. Use the regular
`__call__` method to prepare your inputs and the tokenizer under the `as_target_tokenizer` context manager to prepare
your targets.

Here is a short example:

model_inputs = tokenizer(src_texts, ...)
with tokenizer.as_target_tokenizer():
    labels = tokenizer(tgt_texts, ...)
model_inputs["labels"] = labels["input_ids"]

See the documentation of your specific tokenizer for more details on the specific arguments to the tokenizer of choice.
For a more complete example, see the implementation of `prepare_seq2seq_batch`.

  warnings.warn(formatted_warning, FutureWarning)
INFO:simpletransformers.t5.t5_model: Training started

Epoch:   0%|          | 0/1 [00:00<?, ?it/s]

Running Epoch 0 of 1:   0%|          | 0/85193 [00:00<?, ?it/s]

INFO:simpletransformers.t5.t5_model: Training of google/mt5-base model complete. Saved to outputs/.
INFO:simpletransformers.t5.t5_utils: Creating features from dataset file at cache_dir/

  0%|          | 0/681539 [00:00<?, ?it/s]

INFO:simpletransformers.t5.t5_model: Training started

Epoch:   0%|          | 0/1 [00:00<?, ?it/s]

Running Epoch 0 of 1:   0%|          | 0/85193 [00:00<?, ?it/s]

KeyboardInterrupt: ignored

In [ ]:
!zip -r /content/best_model_th_en.zip /content/outputs/

In [ ]:
!cp /content/best_model_th_en.zip /content/mydrive/MyDrive/MT-Hackathon/best_model_th_en.zip

## Train another epochs

In [ ]:
model_args = T5Args()
model_args.max_seq_length = 96
model_args.train_batch_size = 8
#model_args.eval_batch_size = 4
model_args.num_train_epochs = 2
model_args.evaluate_during_training = False
#model_args.evaluate_during_training_steps = 200
model_args.use_multiprocessing = False
model_args.fp16 = False
model_args.save_steps = -1
model_args.save_eval_checkpoints = False
model_args.no_cache = True
model_args.reprocess_input_data = True
model_args.overwrite_output_dir = True
model_args.preprocess_inputs = False
model_args.num_return_sequences = 1
#model_args.wandb_project = "MT5 Sinhala-English Translation"

model = T5Model("mt5", "/content/content/outputs/", args=model_args)

In [ ]:
%%timeit
model.train_model(all_formatted)  #(train_df, eval_data=eval_df)

INFO:simpletransformers.t5.t5_utils: Creating features from dataset file at cache_dir/

  0%|          | 0/681539 [00:00<?, ?it/s]

/usr/local/lib/python3.7/dist-packages/transformers/tokenization_utils_base.py:3524: FutureWarning:
`prepare_seq2seq_batch` is deprecated and will be removed in version 5 of HuggingFace Transformers. Use the regular
`__call__` method to prepare your inputs and the tokenizer under the `as_target_tokenizer` context manager to prepare
your targets.

Here is a short example:

model_inputs = tokenizer(src_texts, ...)
with tokenizer.as_target_tokenizer():
    labels = tokenizer(tgt_texts, ...)
model_inputs["labels"] = labels["input_ids"]

See the documentation of your specific tokenizer for more details on the specific arguments to the tokenizer of choice.
For a more complete example, see the implementation of `prepare_seq2seq_batch`.

  warnings.warn(formatted_warning, FutureWarning)
INFO:simpletransformers.t5.t5_model: Training started

Epoch:   0%|          | 0/2 [00:00<?, ?it/s]

INFO:simpletransformers.t5.t5_model:   Continuing training from checkpoint, will skip to saved global_step
INFO:simpletransformers.t5.t5_model:   Continuing training from epoch 1
INFO:simpletransformers.t5.t5_model:   Continuing training from global step 85193
INFO:simpletransformers.t5.t5_model:   Will skip the first 0 steps in the current epoch

Running Epoch 0 of 2:   0%|          | 0/85193 [00:00<?, ?it/s]

In [ ]:
!zip -r /content/best_model_th_en2.zip /content/outputs/

In [ ]:
!cp /content/best_model_th_en2.zip /content/mydrive/MyDrive/MT-Hackathon/best_model_th_en2.zip

# Loading Model

In [ ]:
!pip install --upgrade --no-cache-dir gdown

Requirement already satisfied: gdown in /usr/local/lib/python3.7/dist-packages (4.2.2)
Collecting gdown
  Downloading gdown-4.4.0.tar.gz (14 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: tqdm in /usr/local/lib/python3.7/dist-packages (from gdown) (4.63.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.7/dist-packages (from gdown) (3.6.0)
Requirement already satisfied: six in /usr/local/lib/python3.7/dist-packages (from gdown) (1.15.0)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.7/dist-packages (from gdown) (4.6.3)
Requirement already satisfied: requests[socks] in /usr/local/lib/python3.7/dist-packages (from gdown) (2.23.0)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests[socks]->gdown) (1.25.11)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests[socks]->gdown) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests[socks]->gdown) (2021.10.8)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests[socks]->gdown) (2.10)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /usr/local/lib/python3.7/dist-packages (from requests[socks]->gdown) (1.7.1)
Building wheels for collected packages: gdown
  Building wheel for gdown (PEP 517) ... done
  Created wheel for gdown: filename=gdown-4.4.0-py3-none-any.whl size=14774 sha256=31017d14ff8f55fddbff081e2388ad21bd82c69d61c39b9aa867cfc647cf6aa2
  Stored in directory: /tmp/pip-ephem-wheel-cache-_4pepnkj/wheels/fb/c3/0e/c4d8ff8bfcb0461afff199471449f642179b74968c15b7a69c
Successfully built gdown
Installing collected packages: gdown
  Attempting uninstall: gdown
    Found existing installation: gdown 4.2.2
    Uninstalling gdown-4.2.2:
      Successfully uninstalled gdown-4.2.2
Successfully installed gdown-4.4.0

In [ ]:
!gdown --id 1gbPxvhhRmfYWl3AAu1gWtibetFAUF-7P

/usr/local/lib/python3.7/dist-packages/gdown/cli.py:131: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  category=FutureWarning,
Downloading...
From: https://drive.google.com/uc?id=1gbPxvhhRmfYWl3AAu1gWtibetFAUF-7P
To: /content/best_model_th_en.zip
100% 3.74G/3.74G [00:17<00:00, 214MB/s]

In [ ]:
!unzip -qq /content/best_model_th_en.zip

In [ ]:
model_args = T5Args()
model_args.max_seq_length = 96
model_args.train_batch_size = 8
#model_args.eval_batch_size = 4
model_args.num_train_epochs = 1
model_args.evaluate_during_training = False
#model_args.evaluate_during_training_steps = 200
model_args.use_multiprocessing = False
model_args.fp16 = False
model_args.save_steps = -1
model_args.save_eval_checkpoints = False
model_args.no_cache = True
model_args.reprocess_input_data = True
model_args.overwrite_output_dir = True
model_args.preprocess_inputs = False
model_args.num_return_sequences = 1
model_args.use_cuda = False
#model_args.wandb_project = "MT5 Sinhala-English Translation"

model = T5Model("mt5", "/content/content/outputs/checkpoint-85193-epoch-1/", args=model_args)

ValueError: ignored

# Validation

## Evaluating the Model

The standard metric used to evaluate and compare machine translation models is the BLEU score, specifically, the BLEU scheme used by the annual Conference on Machine Translation (WMT). The SacreBLEU library can be used to calculate this score.

For more information on the BLEU score, please refer to this paper by Matt Post.

Since The Tatoeba Challenge also provides the BLEU scores for the benchmark translation models, we can easily compare our model to the benchmark model.

Now, let’s load our fine-tuned model and see how it stacks up!

In [ ]:
!pip install sacrebleu

Collecting sacrebleu
  Downloading sacrebleu-2.0.0-py3-none-any.whl (90 kB)
     |████████████████████████████████| 90 kB 8.8 MB/s
Requirement already satisfied: tabulate>=0.8.9 in /usr/local/lib/python3.7/dist-packages (from sacrebleu) (0.8.9)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.7/dist-packages (from sacrebleu) (1.21.5)
Requirement already satisfied: regex in /usr/local/lib/python3.7/dist-packages (from sacrebleu) (2019.12.20)
Collecting portalocker
  Downloading portalocker-2.4.0-py2.py3-none-any.whl (16 kB)
Collecting colorama
  Downloading colorama-0.4.4-py2.py3-none-any.whl (16 kB)
Installing collected packages: portalocker, colorama, sacrebleu
Successfully installed colorama-0.4.4 portalocker-2.4.0 sacrebleu-2.0.0

In [ ]:
import logging
# import sacrebleu
import pandas as pd
from simpletransformers.t5 import T5Model, T5Args


logging.basicConfig(level=logging.INFO)
transformers_logger = logging.getLogger("transformers")
transformers_logger.setLevel(logging.WARNING)


model_args = T5Args()
model_args.max_length = 96
model_args.length_penalty = 1
model_args.num_beams = 10
model_args.use_cuda = False

model = T5Model("mt5", "/content/content/outputs/", args=model_args)

ValueError: ignored

We import the necessary stuff (note the sacrebleu library) and initialize the model just as we did for training, except that we load the fine-tuned model from outputs/ rather than the pre-trained model.

We also set some parameters for generating text (decoding) with the model. Here, the max_length is the maximum length for the output from the model rather than the input.

If you’d like to learn more about the decoding process, please refer to the decoding algorithms section in this article and this excellent notebook by Huggingface.

Next, we’ll prepare the data for evaluation.

## Validation Datasets

In [ ]:
path_en = '/content/ValidationSet/Valid1+2/dev.en'
path_th = '/content/ValidationSet/Valid1+2/dev.th'
valid1_df = pd.DataFrame(extract_data(path_en), columns = ['en_text'])
valid1_df['th_text'] = extract_data(path_th)
valid1_df

,en_text,th_text
0,It has been confirmed that eight thoroughbred ...,ได้ เป็น ที่ ยืนยัน แน่นอน แล้ว ว่า ม้า แข่ง พ...
1,"Randwick has been locked down, and is expected...",สนาม แข่ง ม้า แร ็นด์ วิค ถูก ปิด และ คาด ว่า ...
2,It is expected that the virulent flu will affe...,คาด ว่า ไข้ หวัด ใหญ่ ร้ายแรง นี้ จะ กระทบ ต่อ...
3,NSW Minister for Primary Industries said the f...,รัฐมนตรี อุตสาหกรรม พื้นฐาน นอง รัฐNSW กล่าว ว...
4,The cases are the first infections of race hor...,เหตุการณ์ นี้ คือ การ ติด เชื้อ ครั้ง แรก ใน ม...
...,...,...
1014,They are reported to have verified her identit...,มี รายงาน แจ้ง ว่า พวก เขา ทราบ ตัว ตน ของ เธอ...
1015,TMZ.com reports that police were checking to s...,TMZ.com รายงาน ว่า ทาง ตำรวจ ได้ ตรวจสอบ ใบ อน...
1016,Spears was not charged with anything and despi...,Spears ไม่ ถูก ปรับ ใน ข้อ หา ใด ๆ และ แม้ ว่า...
1017,"""Britney Spears was part of the group, but was...",SaraFaden โฆษก หญิง ของ กรมตำรวจ LosAngeles กล...
1018,,

In [ ]:
path_en = '/content/ValidationSet/Valid1+2/dev2.en'
path_th = '/content/ValidationSet/Valid1+2/dev2.th'
valid2_df = pd.DataFrame(extract_data(path_en), columns = ['en_text'])
valid2_df['th_text'] = extract_data(path_th)
valid2_df

,en_text,th_text
0,Did you get that thesis from the Dude?,คุณได้ข้อเสนอนี้ จากเพื่อนคนนั้นเหรอ?
1,Police! Get your hands up!,มันเป็นช่วงนาทีที่ ดึงคุณออกจากตัวคุณเอง
2,"We should eat. You hungry, buddy? Yeah.",กินกันเถอะ หิวแล้วใช่มั้ย
3,I'd watch myself if I were you. (Coughs) Ok.,ถ้าฉันเป็นนาย จะคอยระวังตัวไว้ โอเค ที่นี่ล่ะ
4,Anyhow ... it appears you left a favorable imp...,ยังไงก็ตามดูเหมือนว่าคุณทำให้ที่ประชุมวันนี้ ป...
...,...,...
1996,We must close the gate.,เราจะต้องปิดประตู.
1997,You said I was free to come and go.,คุณพูดเองว่าฉันมีสิทธิ์ที่จะไปไหนมาไหนก็ได้
1998,"Well, we're on pins and needles.",เหน็บกินแล้วนะ
1999,"Kjetil, we have to get up. We have to get up.",เชทิล ตื่นเถอะ
2000,,

In [ ]:
frames = [valid1_df]  # valid2_df # valid1_df
valid_df = pd.concat(frames, ignore_index = True)
valid_df = valid_df[:1018]
valid_df

,en_text,th_text
0,It has been confirmed that eight thoroughbred ...,ได้ เป็น ที่ ยืนยัน แน่นอน แล้ว ว่า ม้า แข่ง พ...
1,"Randwick has been locked down, and is expected...",สนาม แข่ง ม้า แร ็นด์ วิค ถูก ปิด และ คาด ว่า ...
2,It is expected that the virulent flu will affe...,คาด ว่า ไข้ หวัด ใหญ่ ร้ายแรง นี้ จะ กระทบ ต่อ...
3,NSW Minister for Primary Industries said the f...,รัฐมนตรี อุตสาหกรรม พื้นฐาน นอง รัฐNSW กล่าว ว...
4,The cases are the first infections of race hor...,เหตุการณ์ นี้ คือ การ ติด เชื้อ ครั้ง แรก ใน ม...
...,...,...
1013,Police also say that at least one of cars foll...,ตำรวจ ยัง เสริม ว่า มี รถ อย่าง น้อย หนึ่ง คัน...
1014,They are reported to have verified her identit...,มี รายงาน แจ้ง ว่า พวก เขา ทราบ ตัว ตน ของ เธอ...
1015,TMZ.com reports that police were checking to s...,TMZ.com รายงาน ว่า ทาง ตำรวจ ได้ ตรวจสอบ ใบ อน...
1016,Spears was not charged with anything and despi...,Spears ไม่ ถูก ปรับ ใน ข้อ หา ใด ๆ และ แม้ ว่า...
1017,"""Britney Spears was part of the group, but was...",SaraFaden โฆษก หญิง ของ กรมตำรวจ LosAngeles กล...

In [ ]:
# eval_df = pd.read_csv("data/eval.tsv", sep="\t").astype(str)

# thai_truth = [valid_df.loc[valid_df["prefix"] == "translate english to thai"]["target_text"].tolist()]
# to_thai = valid_df.loc[valid_df["prefix"] == "translate english to english"]["input_text"].tolist()

english_truth = valid_df['en_text'].tolist()
to_english = valid_df['th_text'].tolist()

Here, we load the evaluation data and prepare separate lists of inputs and true translations (for English to Sinhalese and vice versa).

With the model and evaluation data loaded and ready, we can go ahead and do the translations. With Simple Transformers, we just call model.predict() with the input data. Then, we use the sacrebleu tool to calculate the BLEU score.

The sacrebleu library should be installed in your virtual environment if you followed the setup instructions. If not, you can install it with pip install sacrebleu.

In [ ]:
english_truth

In [ ]:
to_english

In [ ]:
def post_process(pred):
  post_eng_preds = []
  for sentence in pred:
    post_eng_pred = sentence.replace("&apos;", "'")
    post_eng_preds.append(post_eng_pred)

  return post_eng_preds

In [ ]:
len(english_preds)

3019

In [ ]:
len(english_truth)

3019

In [ ]:
english_preds = model.predict(to_english)

Generating outputs:   0%|          | 0/128 [00:00<?, ?it/s]

/usr/local/lib/python3.7/dist-packages/transformers/tokenization_utils_base.py:3524: FutureWarning:
`prepare_seq2seq_batch` is deprecated and will be removed in version 5 of HuggingFace Transformers. Use the regular
`__call__` method to prepare your inputs and the tokenizer under the `as_target_tokenizer` context manager to prepare
your targets.

Here is a short example:

model_inputs = tokenizer(src_texts, ...)
with tokenizer.as_target_tokenizer():
    labels = tokenizer(tgt_texts, ...)
model_inputs["labels"] = labels["input_ids"]

See the documentation of your specific tokenizer for more details on the specific arguments to the tokenizer of choice.
For a more complete example, see the implementation of `prepare_seq2seq_batch`.

  warnings.warn(formatted_warning, FutureWarning)

Decoding outputs:   0%|          | 0/1018 [00:00<?, ?it/s]

In [ ]:
english_preds

['eight good racing horses are certainly immune to a big cold in manchester.',
 "radwick's horse racing arena was closed and expected to remain close to two months.",
 'it is supposed that this bad cold could affect a large number of seven large horses in the stables.',
 'ns ministers, nsa state, said, will be confined for five days after the last symptoms of a cold.',
 'this incident is the first infection in racing horses, including infections in horses, ns and queens and queens.',
 'this cold fever has an acute opportunity of infection, but could not breed humans.',
 "the country's horse racing costs several million dollars every day.",
 'the president of the horse\'s last weekend was blocked, while, was a day, " sorrow and gloomy horses.',
 "it's supposed to be there's a horse race around every australian states except ns and queens this weekend.",
 "sydney's new year's carnival racing festival was cancelled, but at melbourne was supposed to start this weekend.",
 'this tournament will be equipped with a special caution in the area, trying to preserve the safety of the area.',
 'in addition to horses, many public people will be allowed in other states, including johnson, and hannibal, who has lived in other states, are not allowed in other states.',
 'the federal agriculture minister, mr. macdonald\'s medium government, said, " the growing season in melbourne, however, was said, " the largest racing season in melbourne, said.',
 'rio, brazilian, once in the middle east, a group of smuggling drugs, while december 6, 2006, there were few of the survivors of the rio thailand.',
 'the famous area says in the control of a pair of gangs ( red camp ), which does not allow other gangs to sell drugs.',
 "concouver's gang members launched an attack on a group's opponent to defend their territory.",
 "when friday evening, a largest electronics plant in china's world, however, is a largest electronics plant in china's world, and's a largest electronics plant in china's world, a largest electronics plant in china's world, however, the largest electronics plant in china's world,",
 'the explosion was caused by a bad ventilation, which resulted in a very easily flammable exposure.',
 'explosions occurred at 7 o ’ clock in the evening when the workers shifted their workers.',
 'few people suffered a loss of three lives, three, and five wounded.',
 'all actions at a factory, they said, " all actions at the impacted factory, however, the production of all other factories, however, they kept the production, and the production of all other factories, however, they ’ ll still stop, and the production of all other factories, however, they\'re kept',
 '" \',\'however, \',\'however, \', \', \', \', \',\'however, \', \', \', \',\'however, \', \', \', \', \', \', \'',
 "the city's officials reported a dust of dust in the air at the factory.",
 'they reported that they had reported a problem of labor conservation in hong kong.',
 'the department\'s air ventilation was very bad, "',
 'a lot of air, "',
 '" they\'re always wearing an aluminum dust, even if they\'re going to put their nose, " said they. "',
 '" when the workers pulled out cotton gloves in their hands, " when the workers pulled the cotton gloves in their hands, "',
 '" however, ", said, ", however, ", however, ", however, ", however, ", however, ", however, ", however, ", however, ", however, ", however, ", however, ", however,',
 'this year, a bombing cause could lead to a failure in the production of a 5, 10 of the year.',
 'they said there was a larger factory in china, but it could not compensate this damage.',
 'a huge earthquake was caused by a 5.58 earthquake, where earthquakes were very small, but when it happened, a huge earthquake.',
 "u.s., u.s. explorer's u.s.a.d.a.m. earthquakes were reported in the u.s.a.s.a.w.a.d.a.w.a.d.a.w.a.d.a.d.a.w.a.d.a.w.a.d.a.m",
 '7.5 kilometers, but u.s.a.s.a.s.a.s.a.s.a.s.a.s.a.s.a.s.a.s.a.s.a.s.a.s.a.s.a.s.a.s.a.s.a.s.a.s.a.s.a.s.a.s.',
 'no matter whether the ice cover is covered in ice, the u.s.a.s.a.s.a., " damages, u.s.a.s.a.s.a.s.a.s.a.s.a.s.a.s.a.s.a.s.a.s.a.s.a.s.a.',
 'antarctica had experienced the largest earthquake earthquake earthquake emperor, when the 5th olympic island, was born in the nearest atlantic island in antarctica.',
 "the russian press said that khun waron, thailand's president, thailand said, thailand's president, thailand said, thailand's president, thailand's president, thailand said, thailand's president, thailand's president, thailand said, thailand's president, thailand's president",
 'iraq\'s secretary\'s secretary, which represents armed weapons, and armed weapons, " winai\'s secretary, which represents the armed weapons and armed weapons, " winai\'s secretary, which represents the armed weapons and armed weapons, " winai\'s',
 'they \'d like to ask a explanation from those people who did not wish to solve the border, and they had to ask a explanation from those people, " the control of russians over the border is clear, and they had to ask a explanation from those people, " the control of russian russia over the border, and they \'d like',
 'when being asked, the british president, thailand said, it would have armed weapons from the province.',
 'the president emphasized the political yoke of thailand\'s government, " the president said.',
 'thailand has proved that thailand could prove that thailand armed iraq.',
 'this article is being examined by the cambodians, " he said.',
 'this region\'s a political alliance, the russian weapons suffered a political interference, to protect political rules. "',
 "thailand's brought a series of documents to russia about the deeds of the three military military organizations.",
 'thailand\'s king\'s former russian military minister, thailand, said, " the armed russian army in thailand, " said, " the king of thailand\'s former russian army, thailand\'s military minister, thailand\'s former russian army, thailand\'s king\'s',
 "a british football coach from mcdonald's, however,, however,, however, is supposed to be a british football coach, however, however, is supposed to be a british football coach, however, however, is supposed to be a british football coach, however, however",
 'when he asked for a job, a man who had given himself a former candidate for this position, when he had given himself a former candidate, however, when he had given himself a former candidate, however, when he had given himself a former candidate, however, when he had',
 'this appointment in england is the height of his job, e.g. williams, and romania.',
 'this could be served, among the italian, italy, former italian, former german coach, former german coach, former german coach, former german coach, former german coach, former german coach, former german coach, former german coach, former german coach, former german coach, former german coach, former german coach,',
 "it's about ten dollars when he's appointed a president, however, he said.",
 'the crude oil price moved to a dollars last week before turning it down again.',
 "some observers think there's a possibility that the oil price is going to plunge dollars.",
 'during a two-day negotiations, supposed to be exported to " the king\'s declaration, the oil price has risen up to 80 cents in new york market and 6 cents in london market.',
 'the un un united nations government called on thursday to investigate the case of murder and kidnappers.',
 'the king\'s king\'s spokesman\'s murder on august 8, 1991, and the evacuation of unkind reporters, said, " only three days ago in northern nations.',
 'nine people were killed in pakistan this year, and few people were killed in the killings.',
 'no investigation of any murder case has been satisfactory.',
 'the united nations said that the united nations wanted to see the pakistan government made a review of all the events.',
 'the pakistan government immediately asked the pakistan government to investigate these human rights, and we asked the pakistan government to investigate these cases. "',
 'international safety organizations also requested the pakistan government to ensure safety and protect reporters and workers in the country.',
 'pakistan has also claimed to investigate the case of attacking reporters and conducted a case of human rights.',
 "it's not usual for reporters during the past pakistan and many reporters reported that pakistan was one of the most dangerous countries to do their job.",
 'a group of racial protests were fired after having destroyed a group of racial protests.',
 "king's chief editor of the news network news network, said murder was involved in a reporter's job.",
 'a reporter\'s job in barcelona has become a threatening career. "',
 'a group of irreconciled reporters ( rw ) demanded a punishment for the murder.',
 'the reporters felt unable to publish the news article freely in bulgaria, however, the reporters felt unable to give their own subscriptions.',
 'the remains of a smuggled derailment on august 10th.',
 'the organization for freedom of the world, said the pakistan government had to do everything possible to catch him.',
 'the company said, " this is unacceptable for local reporters, and investigate the matter by using their own sources, "',
 'the committee for human rights of pakistan ( hrc ) denounced the two events.',
 '" there was a warning among each reporters, "  warned, ".',
 'a case of violence caused by a few years ago, however, there was no identification or punishment against the terrorists.',
 'the committee said " hrc " called the pakistan government to respond to the situation, however, that the government could not be a practical, while the reporters were killed.',
 "the u.s.a.'s ecological surveyers had a serious earthquake on the u.s.a.s.a.",
 'for two minutes, a shock to many communities near the seashore.',
 "the officials's reported injury, but the sea level has risen to 4 metres in certain areas.",
 'unless the information of the earthquakes, the u.s.a.s.a.d.a.s. earthquake, u.s.a.s.a.s. earthquake, the u.s.a.s.a.s.a.s. earthquake, u.s.a.s.a.s.a.s.a.',
 'the local ecological agencies reported that the earthquake was caused at the depth of 3 kilometers ( 3 miles ) under the florida sea.',
 "on wednesday's wednesday, mrs saddam's innocence.",
 'the court has suspended the case for six weeks, and then they will prepare their immunity.',
 'during the trial, he argued that the judge was not appointed by him, so he did not like it.',
 "five etiquette judges, where a king's king's judgment shall be given a sentence of death.",
 "britain's parliamentary council members have a relationship with the ex-president hockey hockeyers.",
 'she refuses to answer questions directly about her personal life.',
 "when october ninth october 6th,'s first,'s political, ', ', ', ', ', ', ', ', ', ', ', ', ', ', ', ', ',",
 'this interview has no formal announcements, but can be seen from the video sources below.',
 "the new year's rights of mankind and un united nations reported by the federal rights of human rights and un united nations reported by the federal rights of mankind and un united nations's united nations's united nations's united nations's united nations's united nations's united nations's",
 "the afghanistan's government, however, has not given a copy of the women's rights, such as giving their husband's rights, however, unless they say.",
 'three casualties were nursed in the hospital after the explosions were found in a gas station in texas.',
 'the oxygen oxygen tank, calcium, oxygen, and azymes started to explode, after the irregular connectors of a connector between the tons of gas.',
 'explosions filled the air of buildings and specialities.',
 'the black smoke from the factory could see many miles away from the factory.',
 'the fireworks started at 9 : 5 a.m.s.a.d.p.a.d.a.d.a.d.a.d.a.d.a.d.a.d.a.d.a.d.a.d.a.d.a.d.a.d.a.d.a.d.a.d.a.d.a.m.',
 'the officers immigrate people in a half-metre fence ( about 2,000 metres ).',
 'some parts of the highway, linked to the no 5 and 5, were closed.',
 'a slight smell ignited a fire against the road.',
 'the gas tank has reported that the gas tank has plunged to four blocks.',
 'environmental workers, surrounding environmental workers, and the state has considered that the quality of air is acceptable after the bomb.',
 'the dangerous material workers blocked the fire which used to extinguish the fire.',
 '" i\'ve just introduced my colleagues. "',
 '" once again, " said the explosion, "',
 '\' however, \', however,, however, when there were no survivors of the bombs, they seemed to be successfully performed. "',
 'this happened in the area, " steve, ", but we \'d like to examine the cause of such events, " but we \'d like to give the city council members.',
 'two wounded dollars, a five-year-old, and a five-year-old man, a five-year-old and a five-year-old dentist, a five-year-old and a five-year-old man, a five-year-old and a five-year-old man, a five-year-old and a five-year',
 'the third injured driver who was a third driver, which was a third driver, which was a third driver, which was a third driver, which was a third driver, which was a third driver, which was a third driver, which was a third driver, which was a third driver,',
 'when he jumped out of the trunk of his wagon.',
 "his elderly boy mohammy's eight-year-old enthusiastic boy was sent to the united states army for many years.",
 'dr. oxford dewey was encountered with the trial of killing the u.s. soldiers of the united states in africa.',
 "drs saddam and three of her three children have disappeared after leaving her parents'home in karaoke on march fifth.",
 "she's married a prince of chulalongkorn who was accused of being an attacker on september 10th",
 "her husband's husband was arrested in 2003 and is now confined to a detention center.",
 "thailand's a spy and a spy, which shows a secret, a spy, a spy, a spy, a spy, a spy, a spy, a spy, a spy, a spy, a spy, a spy, a spy, a spy, a spy, and",
 'a boy mohammy was only six years old when his mother and his sister were kidnapped out of cambodia in the year and then he was sent to the united states officials.',
 'dr. hayai told the reporter after the boy was sent to her by the officials of the bangkok ministry of defense and filter intelligence.',
 "the boy mohammy boys arrived at the plaza airport in istanbul, a fly of a p a and was sent to the dormitory's dormitory.",
 "the president of the pakistani human rights council president, mr. baker's daughter lived in afghanistan.",
 '" however, the united states government, however, he wouldn ’ t do anything to leave the united states\'s citizens, but the u.s.a.s.a.s.a.s.a.s.a.s.a.s.a.s.a.s.a.s.a.s.a.s.a',
 'the mohammy boy went home in cambodia where he lost five years, ready for his family.',
 'dr. philadelphia and her family hope that two children are able to go home early in the province of pakistan.',
 'a couple of parties, the palestinians were dismissed from home on week after the enquiry they sued for being dismissed.',
 'the evacuation was caused by the stress of the nation to israeli, and stopped the extradition.',
 'israeli security forces invaded the 6 : hour ( local time ) and forced families and domestic activists.',
 'the alligator television station reported that the family would be hit with a tin when they tried to go home.',
 'jfa reported that the jewish families moved home immediately after the palestinians were dismissed.',
 "israeli's premier israeli's designed a project based on king's chulalongkorn and declared that the jewish people were able to live in this town.",
 'even jerusalem is well known as a crowned empire, however, is considered as a crowned empire, however, is considered as a crowned empire, however, is considered as a crowned empire, however, is known as a crowned empire, however, is known as a',
 'israeli has planned to create a new five new apartment apartments in jerio saloon.',
 'the united united united nations united nations united nations for peace in the middle east, mr. robert said, " unacceptable ".',
 'the united nations association, including the united states, asked israelis to stop their immigration, and allow them to create a pollution.',
 "five five children were killed in the police's fire which ended in a car accident in london california on august 6th week.",
 'a eight-year-old, a eight-year-old victim of car accident.',
 'four children in seven children were killed in the chase when the police told them to stop and hit with two adults and five children.',
 'this family was on the way to a football match for adults when the car crashed.',
 'four children bounced out of the wagon and lost their lives.',
 'two adults and one child were delivered to the central media center where located in bonn.',
 'two roads stuck in lemon plantations at the crossroads, and a flat road in china.',
 "three of the three suspected suspects were in a five-man's car, the suspects were killed in the stolen car.",
 'their personal information is not known as no one carrys a identity card.',
 'another child has a name as tanya sasaki is one-year-old, michael is three years old, and boys are seven years old.',
 'two adults, george warr, 2 adults, george george, 2 adults, george warr, 2 adults, george warr, 2 adults, george warr, 2 adults, george warr, 2 adults, george warr, 2 adults, george warr, 2 adults, george',
 'the news news reported, there were no baits in a safety belt.',
 "the new year's general election results of new year's general election in new year, it has shown that the liberalism party has been elected again.",
 'the liberalism party is a four year government, to become a large government government.',
 "england's first cabinet minister has been maintained by wichit hamburg's second standing.",
 'the elapsed from hamburg government, consists of a two-way and a monkey bridge to new york falls.',
 "the king chulalongkorn ii of thailand's coptics, thailand's coptics, thailand's coptics, thailand's coptics, thailand's coptics, thailand's coptics, thailand's coptics, thailand's coptics, thailand '",
 "his funeral was held in cairo's temple, which was filled with people.",
 'the funeral includes singing, prayers, prayers, prayers, prayers, prayers, prayers, prayers, prayers, prayers, prayers, prayers, prayers, prayers, prayers, prayers, prayers, prayers,',
 'many policemen were stuck in their cryings.',
 'the general, who is now a leading general of egypt, is today a day of mourning.',
 'coptics, coptics is one of the oldest religions in the world, and trace their history back to the mark in the first century.',
 "it took four years as a coptic king's king's king's king's king's king's king's king's king's king's king's king's king's king's king's king's king's",
 'most of his maids were used to tranquilize his maid after violence and discrimination during their work with large muslims.',
 "when the president's problem, he spent three years imprisoned in the temple, after the accusation of the problem of the president in the year.",
 'many democratic parties were probably a hard time for their religions.',
 'the baptism of the fourth century\'s temple, the priest told us as a leader, " he told a christian group of christians at the cathedral of the fourth century.',
 '" brothers of our muslims ", "',
 "it's very crowded around the temples, while prayers are still going on today.",
 'the crown crowned with gold crowns.',
 'his body was brought to the military airport to bring to the shrine temples in the desert to buried.',
 'thousands of people suffered the deaths of the king ramada praised him.',
 '" u.s. president, u.s.a. president, u.s.a. president, u.s.a. president, u.s.a. u.s.a. president, u.s.a. u.s.a. president, u.s.a. u.s.a. president, u.s.',
 'when people from all religions and belief, " his enthusiasm of egypt. "',
 "thailand's capital in thailand's capital city capital.",

In [ ]:
th_eng_bleu = sacrebleu.corpus_bleu(english_preds, english_truth)
print("English to Thai: ", th_eng_bleu.score)

English to Thai:  0.10052311972059963

In [ ]:
english_preds_new = post_process(english_preds)

In [ ]:
english_preds_new

['eight good racing horses are certainly immune to a big cold in manchester.',
 "radwick's horse racing arena was closed and expected to remain close to two months.",
 'it is supposed that this bad cold could affect a large number of seven large horses in the stables.',
 'ns ministers, nsa state, said, will be confined for five days after the last symptoms of a cold.',
 'this incident is the first infection in racing horses, including infections in horses, ns and queens and queens.',
 'this cold fever has an acute opportunity of infection, but could not breed humans.',
 "the country's horse racing costs several million dollars every day.",
 'the president of the horse\'s last weekend was blocked, while, was a day, " sorrow and gloomy horses.',
 "it's supposed to be there's a horse race around every australian states except ns and queens this weekend.",
 "sydney's new year's carnival racing festival was cancelled, but at melbourne was supposed to start this weekend.",
 'this tournament will be equipped with a special caution in the area, trying to preserve the safety of the area.',
 'in addition to horses, many public people will be allowed in other states, including johnson, and hannibal, who has lived in other states, are not allowed in other states.',
 'the federal agriculture minister, mr. macdonald\'s medium government, said, " the growing season in melbourne, however, was said, " the largest racing season in melbourne, said.',
 'rio, brazilian, once in the middle east, a group of smuggling drugs, while december 6, 2006, there were few of the survivors of the rio thailand.',
 'the famous area says in the control of a pair of gangs ( red camp ), which does not allow other gangs to sell drugs.',
 "concouver's gang members launched an attack on a group's opponent to defend their territory.",
 "when friday evening, a largest electronics plant in china's world, however, is a largest electronics plant in china's world, and's a largest electronics plant in china's world, a largest electronics plant in china's world, however, the largest electronics plant in china's world,",
 'the explosion was caused by a bad ventilation, which resulted in a very easily flammable exposure.',
 'explosions occurred at 7 o ’ clock in the evening when the workers shifted their workers.',
 'few people suffered a loss of three lives, three, and five wounded.',
 'all actions at a factory, they said, " all actions at the impacted factory, however, the production of all other factories, however, they kept the production, and the production of all other factories, however, they ’ ll still stop, and the production of all other factories, however, they\'re kept',
 '" \',\'however, \',\'however, \', \', \', \', \',\'however, \', \', \', \',\'however, \', \', \', \', \', \', \'',
 "the city's officials reported a dust of dust in the air at the factory.",
 'they reported that they had reported a problem of labor conservation in hong kong.',
 'the department\'s air ventilation was very bad, "',
 'a lot of air, "',
 '" they\'re always wearing an aluminum dust, even if they\'re going to put their nose, " said they. "',
 '" when the workers pulled out cotton gloves in their hands, " when the workers pulled the cotton gloves in their hands, "',
 '" however, ", said, ", however, ", however, ", however, ", however, ", however, ", however, ", however, ", however, ", however, ", however, ", however, ", however,',
 'this year, a bombing cause could lead to a failure in the production of a 5, 10 of the year.',
 'they said there was a larger factory in china, but it could not compensate this damage.',
 'a huge earthquake was caused by a 5.58 earthquake, where earthquakes were very small, but when it happened, a huge earthquake.',
 "u.s., u.s. explorer's u.s.a.d.a.m. earthquakes were reported in the u.s.a.s.a.w.a.d.a.w.a.d.a.w.a.d.a.d.a.w.a.d.a.w.a.d.a.m",
 '7.5 kilometers, but u.s.a.s.a.s.a.s.a.s.a.s.a.s.a.s.a.s.a.s.a.s.a.s.a.s.a.s.a.s.a.s.a.s.a.s.a.s.a.s.a.s.a.s.',
 'no matter whether the ice cover is covered in ice, the u.s.a.s.a.s.a., " damages, u.s.a.s.a.s.a.s.a.s.a.s.a.s.a.s.a.s.a.s.a.s.a.s.a.s.a.',
 'antarctica had experienced the largest earthquake earthquake earthquake emperor, when the 5th olympic island, was born in the nearest atlantic island in antarctica.',
 "the russian press said that khun waron, thailand's president, thailand said, thailand's president, thailand said, thailand's president, thailand's president, thailand said, thailand's president, thailand's president, thailand said, thailand's president, thailand's president",
 'iraq\'s secretary\'s secretary, which represents armed weapons, and armed weapons, " winai\'s secretary, which represents the armed weapons and armed weapons, " winai\'s secretary, which represents the armed weapons and armed weapons, " winai\'s',
 'they \'d like to ask a explanation from those people who did not wish to solve the border, and they had to ask a explanation from those people, " the control of russians over the border is clear, and they had to ask a explanation from those people, " the control of russian russia over the border, and they \'d like',
 'when being asked, the british president, thailand said, it would have armed weapons from the province.',
 'the president emphasized the political yoke of thailand\'s government, " the president said.',
 'thailand has proved that thailand could prove that thailand armed iraq.',
 'this article is being examined by the cambodians, " he said.',
 'this region\'s a political alliance, the russian weapons suffered a political interference, to protect political rules. "',
 "thailand's brought a series of documents to russia about the deeds of the three military military organizations.",
 'thailand\'s king\'s former russian military minister, thailand, said, " the armed russian army in thailand, " said, " the king of thailand\'s former russian army, thailand\'s military minister, thailand\'s former russian army, thailand\'s king\'s',
 "a british football coach from mcdonald's, however,, however,, however, is supposed to be a british football coach, however, however, is supposed to be a british football coach, however, however, is supposed to be a british football coach, however, however",
 'when he asked for a job, a man who had given himself a former candidate for this position, when he had given himself a former candidate, however, when he had given himself a former candidate, however, when he had given himself a former candidate, however, when he had',
 'this appointment in england is the height of his job, e.g. williams, and romania.',
 'this could be served, among the italian, italy, former italian, former german coach, former german coach, former german coach, former german coach, former german coach, former german coach, former german coach, former german coach, former german coach, former german coach, former german coach, former german coach,',
 "it's about ten dollars when he's appointed a president, however, he said.",
 'the crude oil price moved to a dollars last week before turning it down again.',
 "some observers think there's a possibility that the oil price is going to plunge dollars.",
 'during a two-day negotiations, supposed to be exported to " the king\'s declaration, the oil price has risen up to 80 cents in new york market and 6 cents in london market.',
 'the un un united nations government called on thursday to investigate the case of murder and kidnappers.',
 'the king\'s king\'s spokesman\'s murder on august 8, 1991, and the evacuation of unkind reporters, said, " only three days ago in northern nations.',
 'nine people were killed in pakistan this year, and few people were killed in the killings.',
 'no investigation of any murder case has been satisfactory.',
 'the united nations said that the united nations wanted to see the pakistan government made a review of all the events.',
 'the pakistan government immediately asked the pakistan government to investigate these human rights, and we asked the pakistan government to investigate these cases. "',
 'international safety organizations also requested the pakistan government to ensure safety and protect reporters and workers in the country.',
 'pakistan has also claimed to investigate the case of attacking reporters and conducted a case of human rights.',
 "it's not usual for reporters during the past pakistan and many reporters reported that pakistan was one of the most dangerous countries to do their job.",
 'a group of racial protests were fired after having destroyed a group of racial protests.',
 "king's chief editor of the news network news network, said murder was involved in a reporter's job.",
 'a reporter\'s job in barcelona has become a threatening career. "',
 'a group of irreconciled reporters ( rw ) demanded a punishment for the murder.',
 'the reporters felt unable to publish the news article freely in bulgaria, however, the reporters felt unable to give their own subscriptions.',
 'the remains of a smuggled derailment on august 10th.',
 'the organization for freedom of the world, said the pakistan government had to do everything possible to catch him.',
 'the company said, " this is unacceptable for local reporters, and investigate the matter by using their own sources, "',
 'the committee for human rights of pakistan ( hrc ) denounced the two events.',
 '" there was a warning among each reporters, "  warned, ".',
 'a case of violence caused by a few years ago, however, there was no identification or punishment against the terrorists.',
 'the committee said " hrc " called the pakistan government to respond to the situation, however, that the government could not be a practical, while the reporters were killed.',
 "the u.s.a.'s ecological surveyers had a serious earthquake on the u.s.a.s.a.",
 'for two minutes, a shock to many communities near the seashore.',
 "the officials's reported injury, but the sea level has risen to 4 metres in certain areas.",
 'unless the information of the earthquakes, the u.s.a.s.a.d.a.s. earthquake, u.s.a.s.a.s. earthquake, the u.s.a.s.a.s.a.s. earthquake, u.s.a.s.a.s.a.s.a.',
 'the local ecological agencies reported that the earthquake was caused at the depth of 3 kilometers ( 3 miles ) under the florida sea.',
 "on wednesday's wednesday, mrs saddam's innocence.",
 'the court has suspended the case for six weeks, and then they will prepare their immunity.',
 'during the trial, he argued that the judge was not appointed by him, so he did not like it.',
 "five etiquette judges, where a king's king's judgment shall be given a sentence of death.",
 "britain's parliamentary council members have a relationship with the ex-president hockey hockeyers.",
 'she refuses to answer questions directly about her personal life.',
 "when october ninth october 6th,'s first,'s political, ', ', ', ', ', ', ', ', ', ', ', ', ', ', ', ', ',",
 'this interview has no formal announcements, but can be seen from the video sources below.',
 "the new year's rights of mankind and un united nations reported by the federal rights of human rights and un united nations reported by the federal rights of mankind and un united nations's united nations's united nations's united nations's united nations's united nations's united nations's",
 "the afghanistan's government, however, has not given a copy of the women's rights, such as giving their husband's rights, however, unless they say.",
 'three casualties were nursed in the hospital after the explosions were found in a gas station in texas.',
 'the oxygen oxygen tank, calcium, oxygen, and azymes started to explode, after the irregular connectors of a connector between the tons of gas.',
 'explosions filled the air of buildings and specialities.',
 'the black smoke from the factory could see many miles away from the factory.',
 'the fireworks started at 9 : 5 a.m.s.a.d.p.a.d.a.d.a.d.a.d.a.d.a.d.a.d.a.d.a.d.a.d.a.d.a.d.a.d.a.d.a.d.a.d.a.d.a.m.',
 'the officers immigrate people in a half-metre fence ( about 2,000 metres ).',
 'some parts of the highway, linked to the no 5 and 5, were closed.',
 'a slight smell ignited a fire against the road.',
 'the gas tank has reported that the gas tank has plunged to four blocks.',
 'environmental workers, surrounding environmental workers, and the state has considered that the quality of air is acceptable after the bomb.',
 'the dangerous material workers blocked the fire which used to extinguish the fire.',
 '" i\'ve just introduced my colleagues. "',
 '" once again, " said the explosion, "',
 '\' however, \', however,, however, when there were no survivors of the bombs, they seemed to be successfully performed. "',
 'this happened in the area, " steve, ", but we \'d like to examine the cause of such events, " but we \'d like to give the city council members.',
 'two wounded dollars, a five-year-old, and a five-year-old man, a five-year-old and a five-year-old dentist, a five-year-old and a five-year-old man, a five-year-old and a five-year-old man, a five-year-old and a five-year',
 'the third injured driver who was a third driver, which was a third driver, which was a third driver, which was a third driver, which was a third driver, which was a third driver, which was a third driver, which was a third driver, which was a third driver,',
 'when he jumped out of the trunk of his wagon.',
 "his elderly boy mohammy's eight-year-old enthusiastic boy was sent to the united states army for many years.",
 'dr. oxford dewey was encountered with the trial of killing the u.s. soldiers of the united states in africa.',
 "drs saddam and three of her three children have disappeared after leaving her parents'home in karaoke on march fifth.",
 "she's married a prince of chulalongkorn who was accused of being an attacker on september 10th",
 "her husband's husband was arrested in 2003 and is now confined to a detention center.",
 "thailand's a spy and a spy, which shows a secret, a spy, a spy, a spy, a spy, a spy, a spy, a spy, a spy, a spy, a spy, a spy, a spy, a spy, a spy, and",
 'a boy mohammy was only six years old when his mother and his sister were kidnapped out of cambodia in the year and then he was sent to the united states officials.',
 'dr. hayai told the reporter after the boy was sent to her by the officials of the bangkok ministry of defense and filter intelligence.',
 "the boy mohammy boys arrived at the plaza airport in istanbul, a fly of a p a and was sent to the dormitory's dormitory.",
 "the president of the pakistani human rights council president, mr. baker's daughter lived in afghanistan.",
 '" however, the united states government, however, he wouldn ’ t do anything to leave the united states\'s citizens, but the u.s.a.s.a.s.a.s.a.s.a.s.a.s.a.s.a.s.a.s.a.s.a.s.a',
 'the mohammy boy went home in cambodia where he lost five years, ready for his family.',
 'dr. philadelphia and her family hope that two children are able to go home early in the province of pakistan.',
 'a couple of parties, the palestinians were dismissed from home on week after the enquiry they sued for being dismissed.',
 'the evacuation was caused by the stress of the nation to israeli, and stopped the extradition.',
 'israeli security forces invaded the 6 : hour ( local time ) and forced families and domestic activists.',
 'the alligator television station reported that the family would be hit with a tin when they tried to go home.',
 'jfa reported that the jewish families moved home immediately after the palestinians were dismissed.',
 "israeli's premier israeli's designed a project based on king's chulalongkorn and declared that the jewish people were able to live in this town.",
 'even jerusalem is well known as a crowned empire, however, is considered as a crowned empire, however, is considered as a crowned empire, however, is considered as a crowned empire, however, is known as a crowned empire, however, is known as a',
 'israeli has planned to create a new five new apartment apartments in jerio saloon.',
 'the united united united nations united nations united nations for peace in the middle east, mr. robert said, " unacceptable ".',
 'the united nations association, including the united states, asked israelis to stop their immigration, and allow them to create a pollution.',
 "five five children were killed in the police's fire which ended in a car accident in london california on august 6th week.",
 'a eight-year-old, a eight-year-old victim of car accident.',
 'four children in seven children were killed in the chase when the police told them to stop and hit with two adults and five children.',
 'this family was on the way to a football match for adults when the car crashed.',
 'four children bounced out of the wagon and lost their lives.',
 'two adults and one child were delivered to the central media center where located in bonn.',
 'two roads stuck in lemon plantations at the crossroads, and a flat road in china.',
 "three of the three suspected suspects were in a five-man's car, the suspects were killed in the stolen car.",
 'their personal information is not known as no one carrys a identity card.',
 'another child has a name as tanya sasaki is one-year-old, michael is three years old, and boys are seven years old.',
 'two adults, george warr, 2 adults, george george, 2 adults, george warr, 2 adults, george warr, 2 adults, george warr, 2 adults, george warr, 2 adults, george warr, 2 adults, george warr, 2 adults, george',
 'the news news reported, there were no baits in a safety belt.',
 "the new year's general election results of new year's general election in new year, it has shown that the liberalism party has been elected again.",
 'the liberalism party is a four year government, to become a large government government.',
 "england's first cabinet minister has been maintained by wichit hamburg's second standing.",
 'the elapsed from hamburg government, consists of a two-way and a monkey bridge to new york falls.',
 "the king chulalongkorn ii of thailand's coptics, thailand's coptics, thailand's coptics, thailand's coptics, thailand's coptics, thailand's coptics, thailand's coptics, thailand's coptics, thailand '",
 "his funeral was held in cairo's temple, which was filled with people.",
 'the funeral includes singing, prayers, prayers, prayers, prayers, prayers, prayers, prayers, prayers, prayers, prayers, prayers, prayers, prayers, prayers, prayers, prayers, prayers,',
 'many policemen were stuck in their cryings.',
 'the general, who is now a leading general of egypt, is today a day of mourning.',
 'coptics, coptics is one of the oldest religions in the world, and trace their history back to the mark in the first century.',
 "it took four years as a coptic king's king's king's king's king's king's king's king's king's king's king's king's king's king's king's king's king's",
 'most of his maids were used to tranquilize his maid after violence and discrimination during their work with large muslims.',
 "when the president's problem, he spent three years imprisoned in the temple, after the accusation of the problem of the president in the year.",
 'many democratic parties were probably a hard time for their religions.',
 'the baptism of the fourth century\'s temple, the priest told us as a leader, " he told a christian group of christians at the cathedral of the fourth century.',
 '" brothers of our muslims ", "',
 "it's very crowded around the temples, while prayers are still going on today.",
 'the crown crowned with gold crowns.',
 'his body was brought to the military airport to bring to the shrine temples in the desert to buried.',
 'thousands of people suffered the deaths of the king ramada praised him.',
 '" u.s. president, u.s.a. president, u.s.a. president, u.s.a. president, u.s.a. u.s.a. president, u.s.a. u.s.a. president, u.s.a. u.s.a. president, u.s.',
 'when people from all religions and belief, " his enthusiasm of egypt. "',
 "thailand's capital in thailand's capital city capital.",

In [ ]:
th_eng_bleu_new = sacrebleu.corpus_bleu(english_preds_new, english_truth)
print("Thai to English after Post-process: ", th_eng_bleu_new.score)

Thai to English after Post-process:  0.10052311972059963

In [ ]:
# #a_list = ["abc", "def", "ghi"]

# textfile = open("/content/th2en", "w")

# for element in english_preds:

#     textfile.write(element + "\n")

# textfile.close()

# Submission Testset

In [ ]:
!gdown --id 1khuxHPjTTR5d2tL356i8qd-M8JFK2gFu

/usr/local/lib/python3.7/dist-packages/gdown/cli.py:131: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  category=FutureWarning,
Downloading...
From: https://drive.google.com/uc?id=1khuxHPjTTR5d2tL356i8qd-M8JFK2gFu
To: /content/testset_v1_3fnd5.zip
100% 106k/106k [00:00<00:00, 84.2MB/s]

In [ ]:
!unzip -qq /content/testset_v1_3fnd5.zip

In [ ]:
# path_en = '/content/TestSet_ForSuperAI_Release01/test.en'
path_th = '/content/TestSet_ForSuperAI_Release01/test.th'
test_df = pd.DataFrame(extract_data(path_th), columns = ['th_text'])
test_df = test_df[:1520]
test_df

                                                th_text
0                              เขา ทั้ง เตี้ย ทั้ง อ้วน
1                             พวก เขา บอก ให้ ฉัน เงียบ
2                                   คุณ มี แผน อะไร ไหม
3                                    แสง ไฟ มืด ลง แล้ว
4                   คุณ ต้อง ยืนหยัด ดำเนิน การ ตาม แผน
...                                                 ...
1515  ตามที่ Henry Akpan หัวหน้านักระบาดวิทยาที่กระท...
1516  ข้อพิพาทในครอบครัวนำไปสู่การหย่าร้างของนาง Moo...
1517  และ Federal Environment Minister ได้รายงานว่า:...
1518  ภาพยนตร์จะนำเสนอภาพเบื้องหลังการซ้อมในช่วงไม่ก...
1519  ECC ของอัฟกานิสถาน ได้ตีพิมพ์รายงานเกี่ยวกับกา...

[1520 rows x 1 columns]

In [ ]:
to_english = test_df['th_text'].tolist()

In [ ]:
english_preds = model.predict(to_english)

NameError: ignored

In [ ]:
english_preds

["he's both short and fat",
 'they told me to be quiet',
 'do you have any plans',
 'the lights are darkened.',
 'you must insist on the plan.',
 'she needs attention and loving care.',
 'this nurse takes care of the patient with love and patience.',
 "our house doesn 't install air conditioner.",
 'there is milk in this glass.',
 'whose book is this book?',
 'her friend is a liar.',
 'let &apos;s quit school and let &apos;s go to a movie',
 'i have a fortune of 3 baht.',
 'help me with my newspapers.',
 'this winter is colder than last year.',
 'how do other people have any ideas',
 'let &apos;s take those old clothes away',
 "many of our class's classes are very young women boys",
 "i'm moving this box",
 "there's no other way to do it.",
 'she always comes to ask me to help.',
 'is christmas gift finished yet?',
 'the weather of the north is colder.',
 'his nose is big and red.',
 "let's see the traditions of two nations.",
 'i &apos;ve got to go',
 'beijing has changed a lot recently',
 "a heavy audience's performance",
 'this hotel is fully booked.',
 'a monthly rent of 500 yuan does not include the cost of heating.',
 'i assure you i could arrive at the station on time',
 "sorry i didn't mean to hurt you",
 'marathons i signed for a marathon.',
 'the boys keep their books.',
 'she graduated from oxford university.',
 "these products don 't come to the mark.",
 'this form has already been completed, he has completely finished this form.',
 'he ate three pieces of cookies at a time.',
 "my master's advice went smoothly.",
 'a little hurt, a few days are missing.',
 "this night's best friend's wedding party i couldn't attend a party",
 "this carpet is not only a good quality, but it's very cheap.",
 'why are you so sure?',
 "in front of an old friend, there's no need to brag.",
 'he went through a visa for a visa to the united states.',
 'the blue clouds in the sky are very beautiful.',
 'this communication is a secret data.',
 'her blouse is as thin as paper.',
 "the enemy's army has a detailed information on the removal of the enemy troops.",
 'keep your cards well',
 'luckily, he has a health illness.',
 'why are you looking at the evil world?',
 'he stood forward to the door.',
 'he touched her very softly.',
 'i used a blanket to wrap her.',
 "it's quite easy to practice skills, and the competition will be quite easy.",
 'men and women are unbalanced.',
 'they love each other.',
 'the children really know how high your ability to take photographs',
 'the woman is certainly involved in the death of the woman.',
 'a campaign against corruption is essential.',
 "every old year's eve went toge ther and a lot of sparks.",
 'i don &apos;t want to argue with you for this problem',
 "grandfather's hands have a lot of wrinkles, he often says these are signs of age.",
 'he had a strange face when he looked around, he had a strange face.',
 'the third group athletes went up.',
 'he has a dangerous antimicrobial virus.',
 'my throat was bitten by an insect yesterday',
 'the population is increasingly raised.',
 'he answered her asking very hard.',
 'i hurriedly said...',
 'this shock could not be explained.',
 'really sorry to have kept you waiting long',
 'my heart beats unavoidably.',
 "i'm good for him",
 'he always attends the meetings of the department.',
 'her rhythm is too fast.',
 'this kind of vegetables should not be eaten raw.',
 'would you like to have some tea?',
 "take a taxi, there's no need for a tip.",
 'they sang dancing to music.',
 'come out now!',
 'when we were seated, we were taking off this night.',
 'he loves her from the bottom of the heart.',
 'he has just played the internet.',
 'could i see the menu?',
 'there are three deer in front of us.',
 'these shoes are in bad quality.',
 'i &apos;ll go and buy milk at the supermarket',
 'his study results were very good.',
 'why are you late?',
 'mom cooks cooking in the kitchen.',
 'mr ping &apos;s four season weather is like spring so it &apos;s called the city of spring',
 'she &apos;s as smart as you',
 'this house is hers.',
 "i'm collecting information for thesis.",
 'these two fabrics are very different.',
 "i 'd like to have a chinese tofu, i 'd like to taste it.",
 "the longest river of china's river is jiangjie river",
 'on a leaf, nobody is over 30 years old.',
 "it's too loud outside, i couldn 't hear what she was saying.",
 'his experiments were successful.',
 'the sunshine enrich the fruits.',
 'he received respect for his honesty.',
 'can i smoke here a smoke?',
 "we have to leave at 6 o 'clock.",
 'i have faxed the documents to him.',
 'this dictionary is better than any other dictionary.',
 'mistakes were caused by ignorance.',
 'when dancing, i stepped on his feet.',
 'the government chose emergency measures to stop the spread of a virus.',
 "i 'd like some references.",
 'amanda opened a vegetarian restaurant.',
 'you should be ashamed of what you shown last evening.',
 'his wife is concerned about every man in the house.',
 "the hotel's toilet is at the exit.",
 'india used to become a city in england.',
 'the prices of these two houses are very different.',
 "the fly's wings were disbanded.",
 "those workwork didn 't do any good.",
 'a little knowledge can certainly prevent this happening.',
 'they plunged to the beach shore.',
 'i like to eat fried vegetables fried',
 "i've been swamping the car all afternoon",
 'their parents are extremely opposed to marriage proposals.',
 'she spent a few strokes when the shop staff were not interested in buying a few cigarettes.',
 'the violinist thanked the visitors of the hill.',
 'five five times five times five times five times five equals five.',
 "she wouldn 't accept her carelessness.",
 'he knows the seriousness of his own illness.',
 "he's a computer programmer",
 'this type of material is water and carbon.',
 'our headquarters were founded in the united states.',
 "a man's life includes growth and mortality.",
 'they were defeated in negotiations.',
 'the boy quickly took off his clothes and jumped into the pond.',
 'the burmese bird whistled almost once a second.',
 "i telephoned all my telephones and couldn 't find it in a sad face.",
 'his speech was full of self-confidence.',
 'all new pets should be examined by the doctors.',
 'love is a no-nonsense, and cannot be seen.',
 "the cow's cattle are very smelly, because the cows sneeze.",
 'he quickly ran off at the exit.',
 "he's very good at making a guitar.",
 "the school's primary elementary school's teaching is very good.",
 'unless jenny has been to shanghai?',
 "unless she's a stranger, she's a stranger here, don 't think of getting through this road.",
 'people found that mosquitoes could spread disease.',
 'aids infections generally cannot be detected by grips.',
 "hongyang's traditionally going to a hill.",
 "i'm going, he burst into.",
 'the sea was blown through her loving hair.',
 "all the songs i've already bought a cd player, and i've given all the songs.",
 'there were only a few clothes inside the drawer, but there were nothing.',
 "the government's project stimulates the development of economy.",
 'when there were accidents, his body suffered a bad illness, he could walk when there were feet.',
 'once a long time ago, a beautiful princess lives at this place.',
 'he has been doing a job in translation for years.',
 'these three kinds of tobacco can help reconstruction.',
 'he couldn ’ t keep him talking.',
 'during the emergency, a deposit of money has been provided for the use of money.',
 'the manager criticized his mistake.',
 'how much is beijing largest beijing largest beijing than bangkok?',
 'he ordered tomato fried tomatoes.',
 'my grandmother is learning how to use computers',
 'let &apos;s go to a movie this night',
 'every member and all his members attended a meeting.',
 'i &apos;m taking second-class university now',
 'they might have spent too many years in the year.',
 "basketball, too, i don 't like to kick a ball, when i don 't like to kick a ball, however, like playing basketball again.",
 'this reply is not bad, but it is not right.',
 'you really did a good job',
 "my brother's brothers started playing the piano from 4.",
 "it's all the same to him that he doesn 't understand.",
 'what do you plan to do tomorrow?',
 'he always carries a gun with him.',
 "she doesn 't work hard, nor good, it's certainly.",
 'my mother i turned on the lights in the garage',
 "you're not suitable for a place like this",
 'i bought a map of one map and a compass',
 "until now they haven't answered my e-mail",
 "she's an unfamiliar southern winter weather.",
 'the rope is too short.',
 'she often exercises in the morning.',
 'however, we must have a reply from her.',
 "don't bother me",
 'all the electrical appliances in all department stores are on sale.',
 'they stopped watching the map for a moment.',
 'i have about a million yuan',
 'the representatives of the ecological culture.',
 'the baby had a fever, and he hurried to the doctor.',
 "he didn 't know that he had mistaken the rule.",
 'my friend is a tour guide in japan',
 'i really have to apologize to her',
 'want to succeed, you must endure the fighting.',
 'construction should be done at the end of the year.',
 'the moon revolves around the earth.',
 'the leaves dropped from a tree.',
 "where i can 't find my only keys i've lost i've lost i've lost i've lost i've lost i've lost i've lost i've lost i've lost i've lost i've lost i've lost i've lost when i",
 "because it's a traffic jam, i'm late today.",
 "the pearl's neck's pearl's neck's pearl's neck's pearl's neck's pearl's neck's pearl's neck's neck's pearl's neck's pearl's neck's pearl's neck's pearl's neck's",
 'they would like me to write a conversation, and two sentences.',
 "let's have a meal on friday.",
 'she had promised to send an email to me.',
 'he goes to a job every saturday.',
 'sneeze is not the only channel for cold infection.',
 'when they arrived, he greeted warmly.',
 'elephants are symbols of thailand.',
 'we went to our grandparents for a while.',
 'he made a loan from a bank bank.',
 'she looks like innocent, but actually she is very adults.',
 'i could manage this matter alone',
 'which chinese culture courses are we getting to?',
 'the fly was delayed.',
 'did he call me a timid man now?',
 'this is the best modern art museum of the city',
 'phuket island is the largest island in thailand.',
 'his dream is to be a director.',
 'could i pour you a cup of tea?',
 'when he returned his car, he bumped into the parking meter.',
 'my grandmother is a tall man of high morals.',
 'please show me your passport and air-mail tickets.',
 'could you register a client account here',
 'the train cards told them to wait here',
 'i dropped him a few drops of eye drops',
 'the enemy made a fiery offensive.',
 'his chinese language is really fluent',
 'they are far from the centre of the city.',
 'i have to carpet this room',
 'the only survivor of the earthquake.',
 'what dishes do you order on the menu?',
 'i feel happy.',
 'carrots are sliced into a cubicle.',
 'he wore a green hat and wears white t-shirt.',
 'this cold weather freezes your hands.',
 'some children believe that monsters in comics are genuine.',
 'my mother went to the supermarket early in the morning to buy tofu tofu.',
 "it's not like anyone to assure guests.",
 'when i do work don &apos;t often give me a message',
 'i usually buy a cheaper one',
 'a woman while in love, the woman does not carry the faults of the opponent.',
 'jerry is always a target for laughter.',
 'for this article, every man understands the same.',
 "sitting on a razor's feet, the legs were numb.",
 'he dropped the bag out of the window to hide himself.',
 'the museum visits the museum.',
 'the ears of her ears were stunned.',
 'the sweet smell of this kind of perfume is strong, but not too strong.',
 'bad weather has cancelled the game.',
 'this jet flies directly from tianjin to nanjing.',
 'who lives in your room next to you?',
 'the employees of the restaurant greeted the customers enthusiastically.',
 "i feel you shouldn't be interested",
 'chinese transportation is very comfortable',
 "let's be trusted, no one dared you.",
 "we don 't live around.",
 "i'm still fond of giving me a telegram.",
 'however, he pretended nothing to happen.',
 "each country's law is not the same.",
 "i'm using a sleep to rid my conscience.",
 'the problem has been reported to a technical manager.',
 'traditional methodologies have no efficiency.',
 'he has changed his directions and views.',
 'he has deserted his goals and dreams.',
 'how much is a second part of a fraction?',
 'china has wealthy natural resources',
 "unless he wants me to go, or i won 't go.",
 'we really like him, where he never shines.',
 'this book cannot be taken home, but can be copied.',
 'he often expresses his own opinions.',
 'he suffered a loan.',
 'she was so cold that she hit her teeth and shook her whole body.',
 'computer mining is a great asset to human nations.',
 "the president's remarks at the labor union's meeting was very great.",
 'the solicitor brought information to the court.',
 'the thief searched all the room.',
 "there's a good place every man who has been going to tianzhen says there's a good place",
 'repeated exercises poisoned his joints.',
 'however, i must have someone.',
 "he responded to the opponent's asking.",
 "the boss hasn 't decided.",
 'a car accident blocked traffic',
 'the rent went up with the decision of a house-owner and a house tenant.',
 'golf makes me feel relaxed',
 'there was a block of soap on the sink.',
 'what a lot of nonsense remarks do you have?',
 'the baby can distinguish good habits.',
 'each position is divided according to the priority list.',
 'the leaves dropped from a tree.',
 '" he said angrily, " he said. "',
 'go to the first foreign country, you must understand the customs of the land.',
 "he's doing a mad job to finish his work in time.",
 'i declined his proposal',
 'the young lady gazed her uncle across the street.',
 "you must obey the guide's advice.",
 "he's not qualified for chemistry now he's taking a examination",
 'ladies please get together in the shades.',
 "i'm very glad to meet you",
 "he's working very late.",
 "i'm five centimeters taller than him.",
 'my brother got married to a nurse.',
 'when i was in high school i took a bus to the dormitory every day',
 "are their company's company doing any good job?",
 'where have you been in china?',
 'she dared not to tell the truth.',
 'what did you say in a moment?',
 'they decided to buy a lot of goods at price.',
 'the public park is located in the centre of the city.',
 "whether the wind will blow or rain, he 'll all work on time.",
 "she had a good night's sleep.",
 'they are only interested in their own',
 'thailand is a developed country or developed country.',
 "he's a lot fat than before.",
 'drink all the drinks to our successful cooperation',
 'your sympathy impressed me very much',
 'why do women i see all my feelings like to play with my feelings?',
 'he has just lost his wife.',
 'religious classes can form a combination of social classes.',
 'language is a tool of major association.',
 'our country has a carpet of carpets.',
 'let &apos;s go shopping in town',
 'this land is very easily estimated.',
 'the audience gave you a applause.',
 'do you intend that you do it?',
 'he hung a map to his head.',
 'she often gives audiences a dancing audience.',
 'his fault is to say nothing to do.',
 'the light travels directly.',
 'this company uses advertising to deceive consumers.',
 'the game is finished within schedule.',
 'generally confine the baggage to 20 kilograms.',
 'my mother told me that crossed the road to be careful.',
 "thailand's education needs reform.",
 'he has edited the misspelled article.',
 'he spent five minutes describing his opinions.',
 'her manners are very frank.',
 "i'm mad with you, i love you, a feeling like that makes me mad.",
 'i hurried home after school.',
 "he's nowhere he's probably gone to work.",
 'he greeted guests at a luxury french restaurant.',
 'he always makes a dangerous attitude toward them.',
 "be careful! there's a honey on your arm.",
 'is anyone staying in your neighborhood?',
 'this year &apos;s lamp lanterns are especially very enthusiastic',
 'she refused to respond to a personal inquiry.',
 'each of us received a game on a different board.',
 'however, he has never been interested in social situations.',
 'the company has reported a new staff reduction.',
 'i bought a set of apartments for investments',
 'the princess was confined in the castle waiting for her.',
 'all of our engineers are free to find faults.',
 'this city wants to invest in industry.',
 "china's unlike cultural heritage is a cultural heritage.",
 'computer invention is a great asset to humanity.',
 'parents and children should exchange ideas.',
 'our past ages form us in the present.',
 'the young woman is stuck at the edge of the river.',
 'he has been deluged from classical music since childhood.',
 'his speech performance was very inspiring.',
 'this dog is biting its toys.',
 "i'm looking for a job with fixed holidays every year",
 'you &apos;re the kind of person they want to hire',
 "our children's children are especially easily taught.",
 "it's just a twin.",
 'the company closed in germany for over ten branches.',
 'the sky observer discovered a new star.',
 'his sphere of thinking is the main idea of american.',
 'his dream is to be a olympic champion',
 'her hair is soft and smooth.',
 'there was a gleam of flame in his head, he dreamed that it was a brass buddha buddhism.',
 'this is the victory of honor, we have won all of the obstacles.',
 "the notebook's birth means a lot of comfort to computer users.",
 "at school, their children's children's children always follow the rules.",
 'the size of american economy is 6 times larger than britain.',
 'wipe a piece of cloth to wipe the counter.',
 "i've cleaned all the pans in the kitchen.",
 'chinese national chinese national day',
 'don &apos;t you do it a little',
 'my car insurance has expired recently',
 "he's good-natured",
 'he played with the child patiently.',
 'sometimes, they had to stand in the back, whereas they could not stand in interference.',
 "he doesn 't swim well.",
 "my boy is too young. i can 't drink.",
 'this kind of chocolate is delicious.',
 "today's twentieth day of december",
 'i like this plain dark dark skirt.',
 'they are welcome to every member',
 "i still don't understand",
 'would you like tea or coffee?',
 'this river divides the city in two ways.',
 'at a tax free shop please show your passport and air tickets',
 'i had to sweep the garden this afternoon.',
 'draw a point in every circle',
 'my glasses frame has already broken',
 'please give me a dictionary',
 'the performers are changing their clothes at the changing room.',
 'he always attends a department meeting.',
 'he researched the conservation methods of the ocean conservation.',
 'kate used a handkerchief to wipe the sweat on his head and wipe your hands.',
 'carrots are useful for the body.',
 'where did they look like meeting each other',
 "what did you say our product didn't come to the mark",
 'he would like to keep good relations with the right person.',
 'there are 10 packets of tea bag in this box.',
 'he took a thick book out of the book.',
 "i've never seen him any more",
 'the nurse is poisoning the wounded soldiers.',
 'how much does this dinner cost',
 "i wonder if she didn 't tell the truth.",
 'i &apos;d like to stretch the stretches at the park',
 'the boy is very vital.',
 "when you do anything, you're very funny.",
 "this afternoon's evening's meeting, they had a seafood.",
 'my father works in the construction industry',
 'sometimes, appetite sometimes brings havoc.',
 "it's not a show on the stage, why do you have to dress this dark face?",
 'she is his legal wife.',

In [ ]:
def space(preds) :
  lis = []
  for sentence in preds :
    if 'A' <= word[0] <= 'z' and word.lower() in sent_en:
      sent_en.replace(word.lower(),word)
    else :
      pass
    sent_en = sent_en[0].upper()+sent_en[1:]
    lis.append(sent_en)
  return lis

In [ ]:
textfile = open("/content/T5_th2en", "w")

for element in english_preds:

    textfile.write(element + "\n")

textfile.close()

In [ ]:
def post_process(pred):
  post_eng_preds = []
  for sentence in pred:
    post_eng_pred = sentence.replace("&apos;", "'")
    post_eng_preds.append(post_eng_pred)

  return post_eng_preds

In [ ]:
english_preds_new = post_process(english_preds)

In [ ]:
textfile = open("/content/T5_th2en_post", "w")

for element in english_preds_new:

    textfile.write(element + "\n")

textfile.close()