<a href="https://colab.research.google.com/github/prpNn0p/machinetranslation/blob/main/simpletransformers_mt_en_th.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install simpletransformers

In [ ]:
pip install -U --no-cache-dir gdown --pre

In [ ]:
!gdown --id 18J1a6YEIUFWUHtW9T6uS0h7gBJOZqxOS

In [ ]:
%mv /content/Official_Dataset_Machine\ Translation.zip /content/Official_Dataset_Machine_Translation.zip

In [ ]:
!unzip -qq /content/Official_Dataset_Machine_Translation.zip

In [ ]:
import os
import pandas as pd

# Functions

In [ ]:
def extract_data(file):
  f = open(file)
  x = f.read()

  output = x.split("\n")
  return output

In [ ]:
def convert_df_to_format(input_df):
  data = []
  for row, series in input_df.iterrows():
    data.append(["translate thai to english", series['th_text'], series['en_text']])
    # data.append(["translate english to thai", series['en_text'], series['th_text']])
  output_df = pd.DataFrame(data, columns=["prefix", "input_text", "target_text"])
  return output_df

# Train

## Train Datasets

In [ ]:
path_en = '/content/TrainSet/LST_ENTH680K/lowercase/lang.en'
path_th = '/content/TrainSet/LST_ENTH680K/lowercase/lang.th'
lower_case_df = pd.DataFrame(extract_data(path_en), columns = ['en_text'])
lower_case_df['th_text'] = extract_data(path_th)
lower_case_df = lower_case_df[:681539]
lower_case_df

,en_text,th_text
0,thank you but i don't have enough time,ขอบคุณ แต่ ฉัน ไม่ มี เวลา พอ
1,"oh, you know, when i get up i usually do my st...","โอ้ , คุณ รู้ , เมื่อ ฉัน ตื่น ฉัน จะ ออกไป เด..."
2,the duty of a policeman is to safeguard people .,หน้าที่ ของ ตำรวจ คือ การ ปกป้อง ประชาชน
3,it's female vanity.,มัน เป็นความ โอหัง ของ เพศ หญิง .
4,please keep a sharp lookout .,โปรด คอย ดู อย่า เผลอ
...,...,...
681534,"when wijai talked to me on the phone , his voi...",ตอน วิจัย พูด โทรศัพท์ กับ ดิฉัน เสียง เขา แตก...
681535,the bus terminal is on the west side of the ci...,สถานี รถ โดยสาร ทาง ตะวันตก ของ เมือง
681536,encapsulate,ลักษณะ ภาย นอก
681537,"death frightens me , specifically my own death .",ความ ตาย ทำ ให้ ผม กลัว โดย เฉพาะอย่างยิ่ง การ...
681538,i weigh sixty kilograms.,ฉัน หนัก หก สิบ กิโลกรัม .

In [ ]:
frames = [lower_case_df] #Ubuntu_df , qed_df, tanzil_df, tatoeba_df,  Bible_df, GNOME_df, JW300_df, opensub_df
all_df = pd.concat(frames)

In [ ]:
# Test convert function
all_formatted = convert_df_to_format(all_df)
all_formatted

,prefix,input_text,target_text
0,translate thai to english,ขอบคุณ แต่ ฉัน ไม่ มี เวลา พอ,thank you but i don't have enough time
1,translate thai to english,"โอ้ , คุณ รู้ , เมื่อ ฉัน ตื่น ฉัน จะ ออกไป เด...","oh, you know, when i get up i usually do my st..."
2,translate thai to english,หน้าที่ ของ ตำรวจ คือ การ ปกป้อง ประชาชน,the duty of a policeman is to safeguard people .
3,translate thai to english,มัน เป็นความ โอหัง ของ เพศ หญิง .,it's female vanity.
4,translate thai to english,โปรด คอย ดู อย่า เผลอ,please keep a sharp lookout .
...,...,...,...
681534,translate thai to english,ตอน วิจัย พูด โทรศัพท์ กับ ดิฉัน เสียง เขา แตก...,"when wijai talked to me on the phone , his voi..."
681535,translate thai to english,สถานี รถ โดยสาร ทาง ตะวันตก ของ เมือง,the bus terminal is on the west side of the ci...
681536,translate thai to english,ลักษณะ ภาย นอก,encapsulate
681537,translate thai to english,ความ ตาย ทำ ให้ ผม กลัว โดย เฉพาะอย่างยิ่ง การ...,"death frightens me , specifically my own death ."
681538,translate thai to english,ฉัน หนัก หก สิบ กิโลกรัม .,i weigh sixty kilograms.

## Train Model

In [ ]:
import logging
import pandas as pd
from simpletransformers.t5 import T5Model, T5Args


logging.basicConfig(level=logging.INFO)
transformers_logger = logging.getLogger("transformers")
transformers_logger.setLevel(logging.WARNING)

ModuleNotFoundError: ignored

In [ ]:
model_args = T5Args()
model_args.max_seq_length = 96
model_args.train_batch_size = 8
#model_args.eval_batch_size = 4
model_args.num_train_epochs = 5
model_args.evaluate_during_training = False
#model_args.evaluate_during_training_steps = 200
model_args.use_multiprocessing = False
model_args.fp16 = False
model_args.save_steps = -1
model_args.save_eval_checkpoints = False
model_args.no_cache = True
model_args.reprocess_input_data = True
model_args.overwrite_output_dir = True
model_args.preprocess_inputs = False
model_args.num_return_sequences = 1
#model_args.wandb_project = "MT5 Sinhala-English Translation"

model = T5Model("mt5", "/content/checkpoint-85193-epoch-1/", args=model_args)

In [ ]:
# Train the model
%%timeit
model.train_model(all_formatted)  #(train_df, eval_data=eval_df)

INFO:simpletransformers.t5.t5_utils: Creating features from dataset file at cache_dir/

  0%|          | 0/681539 [00:00<?, ?it/s]

/usr/local/lib/python3.7/dist-packages/transformers/tokenization_utils_base.py:3524: FutureWarning:
`prepare_seq2seq_batch` is deprecated and will be removed in version 5 of HuggingFace Transformers. Use the regular
`__call__` method to prepare your inputs and the tokenizer under the `as_target_tokenizer` context manager to prepare
your targets.

Here is a short example:

model_inputs = tokenizer(src_texts, ...)
with tokenizer.as_target_tokenizer():
    labels = tokenizer(tgt_texts, ...)
model_inputs["labels"] = labels["input_ids"]

See the documentation of your specific tokenizer for more details on the specific arguments to the tokenizer of choice.
For a more complete example, see the implementation of `prepare_seq2seq_batch`.

  warnings.warn(formatted_warning, FutureWarning)
INFO:simpletransformers.t5.t5_model: Training started

Epoch:   0%|          | 0/5 [00:00<?, ?it/s]

INFO:simpletransformers.t5.t5_model:   Starting fine-tuning.

Running Epoch 0 of 5:   0%|          | 0/85193 [00:00<?, ?it/s]

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

INFO:root:
Unfortunately, your original traceback can not be constructed.

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 3524, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipykernel_1044/3847668455.py", line 1, in <module>
    get_ipython().run_cell_magic('timeit', '', 'model.train_model(all_formatted)  #(train_df, eval_data=eval_df)\n')
  File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 2462, in run_cell_magic
    result = fn(*args, **kwargs)
  File "<decorator-gen-53>", line 2, in timeit
  File "/usr/local/lib/python3.7/dist-packages/IPython/core/magic.py", line 187, in <lambda>
    call = lambda f, *a, **k: f(*a, **k)
  File "/usr/local/lib/python3.7/dist-packages/IPython/core/magics/execution.py", line 1180, in timeit
    time_number = timer.timeit(number)
  File "/usr/local/lib/python3.7/dist-packages/IPython/core/magics/execution.py", line 169, in timeit
    timing = self.inner(it, self.timer)
  File "<magic-timeit>", line 1, in inner
  File "/usr/local/lib/python3.7/dist-packages/simpletransformers/t5/t5_model.py", line 230, in train_model
    **kwargs,
  File "/usr/local/lib/python3.7/dist-packages/simpletransformers/t5/t5_model.py", line 531, in train
    current_loss = loss.item()
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 2088, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'KeyboardInterrupt' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/IPython/core/ultratb.py", line 1101, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File "/usr/local/lib/python3.7/dist-packages/IPython/core/ultratb.py", line 248, in wrapped
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/IPython/core/ultratb.py", line 281, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
  File "/usr/lib/python3.7/inspect.py", line 1502, in getinnerframes
    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)
  File "/usr/lib/python3.7/inspect.py", line 1460, in getframeinfo
    filename = getsourcefile(frame) or getfile(frame)
  File "/usr/lib/python3.7/inspect.py", line 696, in getsourcefile
    if getattr(getmodule(object, filename), '__loader__', None) is not None:
  File "/usr/lib/python3.7/inspect.py", line 739, in getmodule
    f = getabsfile(module)
  File "/usr/lib/python3.7/inspect.py", line 708, in getabsfile
    _filename = getsourcefile(object) or getfile(object)
  File "/usr/lib/python3.7/inspect.py", line 693, in getsourcefile
    if os.path.exists(filename):
  File "/usr/lib/python3.7/genericpath.py", line 19, in exists
    os.stat(path)
KeyboardInterrupt

TypeError: ignored

In [ ]:
!zip -r /content/best_model_en_th_lst.zip /content/outputs/best_model/

In [ ]:
from google.colab import drive
drive.mount('/content/mydrive/')

## Download Trained Model

In [ ]:
!unzip -qq /content/en-th_T5_model.zip

In [ ]:
!gdown --id 104_LbQFgqNM7RRjwUFr1IfMxeXFHDGNe

/usr/local/lib/python3.7/dist-packages/gdown/cli.py:131: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  category=FutureWarning,
Downloading...
From: https://drive.google.com/uc?id=104_LbQFgqNM7RRjwUFr1IfMxeXFHDGNe
To: /content/pytorch_model.bin
100% 2.33G/2.33G [00:14<00:00, 158MB/s]

In [ ]:
!mv /content/pytorch_model.bin /content/checkpoint-85193-epoch-1/pytorch_model.bin

In [ ]:
!pip install sacrebleu

Requirement already satisfied: sacrebleu in /usr/local/lib/python3.7/dist-packages (2.0.0)
Requirement already satisfied: regex in /usr/local/lib/python3.7/dist-packages (from sacrebleu) (2019.12.20)
Requirement already satisfied: tabulate>=0.8.9 in /usr/local/lib/python3.7/dist-packages (from sacrebleu) (0.8.9)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.7/dist-packages (from sacrebleu) (1.21.5)
Requirement already satisfied: portalocker in /usr/local/lib/python3.7/dist-packages (from sacrebleu) (2.4.0)
Requirement already satisfied: colorama in /usr/local/lib/python3.7/dist-packages (from sacrebleu) (0.4.4)

In [ ]:
import logging
import sacrebleu
import pandas as pd
from simpletransformers.t5 import T5Model, T5Args


logging.basicConfig(level=logging.INFO)
transformers_logger = logging.getLogger("transformers")
transformers_logger.setLevel(logging.WARNING)


model_args = T5Args()
model_args.max_length = 96
model_args.length_penalty = 1
model_args.num_beams = 10

model = T5Model("mt5", "/content/checkpoint-85193-epoch-1/", args=model_args)

# Validation

In [ ]:
!gdown --id 18J1a6YEIUFWUHtW9T6uS0h7gBJOZqxOS

/usr/local/lib/python3.7/dist-packages/gdown/cli.py:131: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  category=FutureWarning,
Downloading...
From: https://drive.google.com/uc?id=18J1a6YEIUFWUHtW9T6uS0h7gBJOZqxOS
To: /content/Official_TrainningDataset_Machine Translation.zip
100% 238M/238M [00:09<00:00, 24.9MB/s]

In [ ]:
%mv /content/Official_TrainningDataset_Machine\ Translation.zip /content/Official_Dataset_Machine_Translation.zip

In [ ]:
!unzip -qq /content/Official_Dataset_Machine_Translation.zip

In [ ]:
path_en = '/content/ValidationSet/Valid1+2/dev.en'
path_th = '/content/ValidationSet/Valid1+2/dev.th'
valid1_df = pd.DataFrame(extract_data(path_en), columns = ['en_text'])
valid1_df['th_text'] = extract_data(path_th)
valid1_df

,en_text,th_text
0,It has been confirmed that eight thoroughbred ...,ได้ เป็น ที่ ยืนยัน แน่นอน แล้ว ว่า ม้า แข่ง พ...
1,"Randwick has been locked down, and is expected...",สนาม แข่ง ม้า แร ็นด์ วิค ถูก ปิด และ คาด ว่า ...
2,It is expected that the virulent flu will affe...,คาด ว่า ไข้ หวัด ใหญ่ ร้ายแรง นี้ จะ กระทบ ต่อ...
3,NSW Minister for Primary Industries said the f...,รัฐมนตรี อุตสาหกรรม พื้นฐาน นอง รัฐNSW กล่าว ว...
4,The cases are the first infections of race hor...,เหตุการณ์ นี้ คือ การ ติด เชื้อ ครั้ง แรก ใน ม...
...,...,...
1014,They are reported to have verified her identit...,มี รายงาน แจ้ง ว่า พวก เขา ทราบ ตัว ตน ของ เธอ...
1015,TMZ.com reports that police were checking to s...,TMZ.com รายงาน ว่า ทาง ตำรวจ ได้ ตรวจสอบ ใบ อน...
1016,Spears was not charged with anything and despi...,Spears ไม่ ถูก ปรับ ใน ข้อ หา ใด ๆ และ แม้ ว่า...
1017,"""Britney Spears was part of the group, but was...",SaraFaden โฆษก หญิง ของ กรมตำรวจ LosAngeles กล...
1018,,

In [ ]:
path_en = '/content/ValidationSet/Valid1+2/dev2.en'
path_th = '/content/ValidationSet/Valid1+2/dev2.th'
valid2_df = pd.DataFrame(extract_data(path_en), columns = ['en_text'])
valid2_df['th_text'] = extract_data(path_th)
valid2_df

,en_text,th_text
0,Did you get that thesis from the Dude?,คุณได้ข้อเสนอนี้ จากเพื่อนคนนั้นเหรอ?
1,Police! Get your hands up!,มันเป็นช่วงนาทีที่ ดึงคุณออกจากตัวคุณเอง
2,"We should eat. You hungry, buddy? Yeah.",กินกันเถอะ หิวแล้วใช่มั้ย
3,I'd watch myself if I were you. (Coughs) Ok.,ถ้าฉันเป็นนาย จะคอยระวังตัวไว้ โอเค ที่นี่ล่ะ
4,Anyhow ... it appears you left a favorable imp...,ยังไงก็ตามดูเหมือนว่าคุณทำให้ที่ประชุมวันนี้ ป...
...,...,...
1996,We must close the gate.,เราจะต้องปิดประตู.
1997,You said I was free to come and go.,คุณพูดเองว่าฉันมีสิทธิ์ที่จะไปไหนมาไหนก็ได้
1998,"Well, we're on pins and needles.",เหน็บกินแล้วนะ
1999,"Kjetil, we have to get up. We have to get up.",เชทิล ตื่นเถอะ
2000,,

In [ ]:
frames = [valid1_df]  # valid2_df # valid1_df
valid_df = pd.concat(frames, ignore_index=True)
valid_df = valid_df[:1018]
valid_df

,en_text,th_text
0,It has been confirmed that eight thoroughbred ...,ได้ เป็น ที่ ยืนยัน แน่นอน แล้ว ว่า ม้า แข่ง พ...
1,"Randwick has been locked down, and is expected...",สนาม แข่ง ม้า แร ็นด์ วิค ถูก ปิด และ คาด ว่า ...
2,It is expected that the virulent flu will affe...,คาด ว่า ไข้ หวัด ใหญ่ ร้ายแรง นี้ จะ กระทบ ต่อ...
3,NSW Minister for Primary Industries said the f...,รัฐมนตรี อุตสาหกรรม พื้นฐาน นอง รัฐNSW กล่าว ว...
4,The cases are the first infections of race hor...,เหตุการณ์ นี้ คือ การ ติด เชื้อ ครั้ง แรก ใน ม...
...,...,...
1013,Police also say that at least one of cars foll...,ตำรวจ ยัง เสริม ว่า มี รถ อย่าง น้อย หนึ่ง คัน...
1014,They are reported to have verified her identit...,มี รายงาน แจ้ง ว่า พวก เขา ทราบ ตัว ตน ของ เธอ...
1015,TMZ.com reports that police were checking to s...,TMZ.com รายงาน ว่า ทาง ตำรวจ ได้ ตรวจสอบ ใบ อน...
1016,Spears was not charged with anything and despi...,Spears ไม่ ถูก ปรับ ใน ข้อ หา ใด ๆ และ แม้ ว่า...
1017,"""Britney Spears was part of the group, but was...",SaraFaden โฆษก หญิง ของ กรมตำรวจ LosAngeles กล...

In [ ]:
thai_truth = valid_df['th_text'].tolist()
to_thai = valid_df['en_text'].tolist()

In [ ]:
thai_truth

['ได้ เป็น ที่ ยืนยัน แน่นอน แล้ว ว่า ม้า แข่ง พันธุ์ ดี แปด ตัว ที่ สนาม แข่งแรนด์วิค ใน เมืงซิดนีย์ ได้ ติด เชื้อ ไข้ หวัด ใหญ่ ม้า',
 'สนาม แข่ง ม้า แร ็นด์ วิค ถูก ปิด และ คาด ว่า จะ ยังคง ปิด อยู่ ต่อ ไป อีก ถึง 2 เดือน',
 'คาด ว่า ไข้ หวัด ใหญ่ ร้ายแรง นี้ จะ กระทบ ต่อ ม้า ส่วน ใหญ่ จำนวน 700 ตัว ใน คอก ม้า ที่ ที่ แรนด์วิค',
 'รัฐมนตรี อุตสาหกรรม พื้นฐาน นอง รัฐNSW กล่าว ว่า จะ กัก บริเวณ ไว้ 30 วัน หลัง จาก ที่ ได้ พบ สัญญาณ สุดท้าย ของ ไข้ หวัด',
 'เหตุการณ์ นี้ คือ การ ติด เชื้อ ครั้ง แรก ใน ม้า แข่ง ทั้ง ที่ ได้ มี การ ติด เชื้อ ใน ม้า สำหรับ กิจกรรม สันทนาการ อื่น ๆ หลาย สิบ ตัว ทั่ว รัฐNWS และ รัฐควีนส์แลนด์',
 'ไข้ หวัด นี้ มี โอกาส ติด เชื้อ โดย ทาง สัมผัส ได้ สูง มาก แต่ ไม่ สามารถ แพร่สามนุษย์',
 'การ ปิด แข่ง ม้า ของ ประเทศ ทำ ให้ ต้อง สิ้นเปลือง ค่า ใช้จ่าย ของ อุตสาหกรรม หลาย สิบ ล้าน ดอลลาร์ ทุก วัน',
 'ประธาน กรรมการ บริหาร ของ ม้า แข่ง ประจำ รัฐNSWPeterV \' Landys กล่าว ว่า การ แข่ง ม้า ถูก ขัดขวาง ตั้งแต่ มี การ ห้าม เคลื่อนย้าย ม้า เมื่อ สุด สัปดาห์ ที่ ผ่าน มา ขณะ นี้ จึง เป็น วัน ที่ " น่า เศร้า และ มืดมน " สำหรับ อุตสาหกรรม แข่ง ม้า ใน รัฐNSW',
 'คาด ว่า จะ ยังคง มี การ แข่ง ม้า ทั่ว ทุก รัฐ ของ ออสเตรเลีย ยกเว้น รัฐNSW และ รัฐควีนส์แลนด์ ใน สุด สัปดาห์ นี้',
 'ใน ขณะ ที่ เทศกาล ม้า แข่ง คาร์นิวัล ใน ฤดู ใบ ไม้ ผลิ ของ ซิดนีย์ ได้ ถูก ยกเลิก ไป นั้น แต่ ที่ เมลล์ เมลเบิร์น คาด ว่า จะ เริ่ม สุด สัปดาห์ นี้ ด้วย การ แข่งชิง ถ้วย คาว ฟิลด์คัพ',
 'การ แข่ง ครั้ง นี้ จะ ดำเนิน การ พร้อม ด้วย การ ระมัดระวัง พิเศษ ใน สถานที่ เพื่อ พยายาม รักษา สภาวะ การ ปลอด ไวรัส ใน พื้นที่',
 'การ ติดต่อ พบปะ ระหว่าง คน ทำ งาน เกี่ยว กับ ม้า และ บุคคล สาธารณะ ทั่วไป จะ ถูก ห้า ท รวม ทั้ง จ ๊อคกี้ DarrenBeadman และ HughBowman ผู้ ซึ่ง มี ภูมิลำเนาย ู่ ใน ซิดนีย์ และ เทรนเนอร์ หลาย คน ที่ อยู่ ใน รัฐ อื่น รวม ทั้ง Bart Cummings ก็ ไม่ ได้ รับ อนุญาต ใน เป็น ส่วน หนึ่ง',
 'รัฐมนตรี เกษตรกรรม ของ รัฐบาล กลาง คุณPeterMacGauran ได้ กล่าว ว่า เทศกาล คาร์นิวัลฤดู ใบ ไม้ ผลิ ใน เมลเบิร์น จะ ยังคง " เหมือน เดิม โดย ส่วน ให้ " ทั้ง ที่ ต้อง สูญเสีย การ แข่ง ม้า ยิ่งใหญ่ ที่สุด ใน ออสเตรเลีย ไป บ้าง ก็ตาม',
 'เมื่อ วัน ที่ 26 และ 27 ธันวาคม ได้ มี ผู้ เสีย ชีวิต อย่าง น้อย 11 คน ใน เหตุการณ์ การ ปะทะ ระหว่าง แก๊ง ค้า ยา เสพ ติด ใน พื้นที่ ละแวก เดียว กัน ใน ย่าน สลัม " morrodaMineira " ( ไมเนอร์ฮิลล์ ) ใน เขต คา ทุมบี ที่ อยู่ ใกล้ เมืองริโอเดจาเนโร ประเทศบราซิล',
 'พื้นที่ ดัง กล่าว อยู่ ใน ความ ควบคุม ของ แก๊ง คู่ อริ ComandoVermelho ( เร็ด คอมมานด์ ) ซึ่ง ไม่ ยอม ให้ แก๊ง อื่น มา ขาย ยา เสพ ติด ใน เขต นี้',
 'สมาชิก แก๊ง ComandoVermelho เริ่ม การ โจมตี สมาชิก คู่ อริ ของ กลุ่ม ADA เพื่อ ปกป้อง เขต ของ ตน',
 'การ ระเบิด ใน Chengdu ประเทศจีน เมื่อ ตอน เย็น วัน ศุกร์ เป็น ผล ให้ บาง ส่วน ของ โรง งาน Foxconn ที่ ดำเนินการ อยู่ ต้อง ปิด ลง โดย Foxconn เป็น โรง งาน ผลิต อุปกรณ์ อิเล็กทรอนิกส์ ที่ ใหญ่ ที่สุด ใน โลก แห่ง หนึ่ง และ เป็น ผู้ จัด ส่ง สินค้า เจ้าหลัก ให้ กับ บริษัท ต่างๆ เช่น Hewlett - PackardDell Sony AppleMotorola และ Nokia',
 'การ สอบสวน เบื้อง ต้น ใน ขณะ นี้ ชี้ ว่า การ ระเบิด เกิด ขึ้น จาก การ ระบาย อากาศ ที่ ไม่ ดี ซึ่ง เป็น ผล ให้ ฝุ่น ละออง ที่ ติด ไฟ ง่าย สะสม มาก',
 'การ ระเบิด เกิด ขึ้น เมื่อ เวลา 7 . 18 ใน ตอน เย็น ระหว่าง ช่วง เวลา ที่ คน งาน เปลี่ยน กะทำ งาน',
 'มี ผู้ เสีย ชีวิต อย่าง น้อย 3 คน และ บาดเจ็บ อย่าง น้อย 15 คน',
 'Foxconn ระงับ การ ผลิต เพื่อ ทำ การ ตรวจสอบ โดย กล่าว ว่า " ปฏิบัติการ ทั้งหมด ที่ โรง งาน ที่ ได้ รับ ผล กระทบ นี่ จะ ยังคง หยุด ระงับ อยู่ และ การ ผลิต จาก โรง งาน อื่น ๆ ทั้งหมด ที่ มี กระบวนการ ที่ คล้าย กัน จะ ถูก ระงับ งาน ด้วย จนกว่า จะ ได้ ผล ของ การ ตรวจสอบ "',
 '" กระบวน การ ผลิต อื่น ๆ ทั้งหมด ใน โรง งาน ของ เรา ใน จีน จะ ยังคง ทำ การ ผลิต ตาม ปกติ ต่อ ไป "',
 'เมื่อ วัน จันทร์ เจ้าหน้าที่ ของ เมือง ได้ ให้ ข้อมูล สาเหตุ ว่า เกิด จาก ฝุ่น ที่ จุด เผาไหม้ ได้ ใน อากาศ ที่ โรง งาน ขัดเงา',
 'กลุ่ม สิทธิ แรงงาน ที่ มี ฐาน อยู่ ใน ฮ่องกง ที่ มี ชื่อ ว่า Students &ScholarsAgainstCorporateMisbehavior กล่าว ว่า พวก เขา ได้ รายงาน ปัญหา ฝุ่น ละออง อะลูมิเนียม ไว้ เมื่อ เดือน มีนาคม ซึ่ง พวก เขา ได้ รี วิว เรื่องราว สภาพ การ ทำ งาน ใน Foxconn ไว้',
 'หลัง จาก การ ระเบิด พวก เขา ได้ ให้ ข้อมูล ว่า คน งาน บ่น ว่า " การ ระบาย อากาศ ของ แผนก ไม่ ดี เลย "',
 '" ใน กระบวน การ ผลิต มี ฝุ่น ละออง อะลูมิเนียม จำนวน มากลอย อยู่ ใน อากาศ มากมาย "',
 '" คน งาน หายใจ เอา ละออง ฝุ่น อะลูมิเนียม เข้า ไป เป็น ประจำ แม้ ว่า พวก เขา จะ สวม ผ้า ปิด จมูก ไว้ ด้วย ก็ตาม "',
 '" เมื่อ คน งาน ถอดถุง มือ ฝ้าย ออก ใน มือ ของ พวก เขา เต็ม ไป ด้วย ฝุ่น อะลูมิเนียม "',
 'Foxconn ตอบโต้ โดย กล่าว ว่า กลุ่ม ดัง กล่าว พยายาม ที่ จะ " ใช้ ประโยชน์ จาก อุบัติเหตุ ที่ น่า สลด นี้ " และ บิดเบือน ความ จริง เกี่ยว กับ " การ ให้ ความ สำคัญ ต่อ สุขภาพ และ ความ ปลอด ภัย ของ พนักงาน ของ Foxconn "',
 'กลุ่ม วิจัย HISiSuppli กล่าว ว่า เหตุ ระเบิด อาจ นำ ไป สู่ การ เสีย กำลัง การ ผลิตiPad 500 , 000 เครื่อง ใน ไตรมาส นี้ ของ ปี',
 'พวก เขา กล่าว ว่า ยัง มี โรง งาน ที่ ใหญ่ กว่า อยู่ ใน Shenzhen แต่ มัน ไม่ สามารถ ที่ จะ ทดแทน ความ เสียหาย ที่ เกิด ขึ้น นี้ ได้',
 'เกิด แผ่นดิน ไหว ขนาด 5 . 8 แมกนิจูด บน พื้นที่ ที่ มี การ เกิด แผ่นดิน ไหว น้อย มาก แต่ เมื่อ เกิด ขึ้น บาง ครั้ง แผ่นดิน ไหว จะ มี ขนาด ใหญ่',
 'สำนักงานสำรวจธรณีวิทยา ของ สหรัฐ ( USGS ) รายงาน ว่า เมื่อ เวลา 3 . 35 ( ตาม เวลา ตะวัน ออก ) ได้ เกิด แผ่นดิน ไหว ขนาด 5 . 8 แมกนิจูด ขึ้น ที่ แอนตาร์กติ กา บริเวณ ห่าง จาก สถานีแคเซย์ ไป ทาง ตะวัน ออก เฉียง ใต้ ค่อน ไป ทาง ใต้ 105 กิโลเมตร ( 65 ไมล์ ) หรือ ห่าง จาก ด้าน เหนือ ของ ขั้ว โลก ใต้ 2 , 565 กิโลเมตร ( 1 , 590 ไมล์ )',
 'มี รายงาน ว่า แผ่นดิน ไหว ดัง กล่าว มี ความ ลึก 7 . 5 กิโลเมตร ( 4 . 7 ไมล์ ) แต่ USGS ระบุ ว่า " ความ ลึก ดัง กล่าว ถูก จำกัด อย่าง เลวร้าย "',
 'เกี่ยว กับ เรื่อง ที่ ว่า เขต ที่ ปกคลุม ด้วย น้ำ แข็ง ได้ รับ ความ เสียหาย บ้าง หรือ ไม่ นั้น USGS กล่าว ว่า " ความ เสียหาย น่า จะ อยู่ ใน ระดับ น้อย ถึง ปานกลาง "',
 'แอนตาร์กติ กา เคย ประสบ เหตุ แผ่นดิน ไหว ขนาด ใหญ่ สุด คือ 8 . 1 แมกนิจูด เมื่อ วัน ที่ 25 มี นาคม 1998 ใน บริเวณ ใกล้ กับ เกาะ บัลเลนี ใน แอนตาร์กติกา',
 'สำนักข่าวรัสเซีย ได้ กล่าว ว่า VladimirVoronin ประธานาธิบดี ประเทศ Moldova ได้ กล่าวหา บรรดา เจ้าหน้าที่ Transnistria เมื่อ วัน เสาร์ ว่า ให้ อุปทาน อาวุธ รัสเซีย แก่ อิรัก ใน ระหว่าง การ ปกครอง ของ SaddamHussein',
 '" Chisinau มี เอกสาร ทางการ จาก สำนัก เลขานุการ ของ SaddamHussein ซึ่ง แสดง ว่า Transnistria ได้ ให้ อุปทาน ทั้ง อาวุธ และ สายงาน การ ผลิต อาวุธ แก่ อิรัก " Voronin บอก แก่ กลุ่ม นัก วารสาร ชาว รัสเซีย และ เพิ่มเติม ว่า การ ลง ทุน ใน กรณี นี้ กำลัง ดำเนินการ อยู่',
 '" การ ควบคุม ของ รัสเซีย เหนือ ดินแดน นี้ นั้น ชัดเจน และ พวก เรา ต้อง ขอ คำ อธิบาย จาก บุคคล เหล่า นั้น ที่ ไม่ ปรารถนา แก้ไข ข้อ ขัดแย้ง นี้ " Voronin กล่าว เพิ่มเติม',
 'เมื่อ ถูก ถาม ว่า รัสเซีย ต้อง ทำ อะไร เพื่อ ที่ จะ ช่วย แก้ไข ความ ขัดแย้ง นี้ ประธานาธิบดี ประเทศ Moldova กล่าว ว่า มัน จะ ต้อง เอา อาวุธยุทโธปกรณ์ จาก ดินแดน นั้น',
 '" เรา พิจารณา ว่า โรง อาวุธ นี้ เป็น การ ครอบงำ ทาง การ เมือง ที่ สนับสนุน การ ปกครอง ของ Transnistria " ประธานาธิบดี เน้น ย้ำ',
 'Voronin เพิ่มเติม ว่า ประเทศ Moldova สามารถ พิสูจน์ ได้ ว่า เมือง Tiraspol จำหน่าย อาวุธ ให้ แก่ อิรัก',
 '" เอกสาร จาก กอง เอกสาร ของ Hussein ที่ สามารถ ยืนยัน เรื่อง นี้ กำลัง ถูก ตรวจสอบ อยู่ ขณะ นี้ โดย บรรดา ผู้ บริหาร ของ Moldova " เขา กล่าว',
 'Voronin ฟ้องร้อง Moscow ให้ จัดการ กับ ความ ขัดแย้ง ส่วน ภูมิภาค นี้ อาวุธ รัสเซีย เป็น " การ ครอบคลุม ทาง การ เมือง เพื่อ ที่ จะ ปกป้องการ ปกครอง Transnistrian "',
 'ผู้ นำ Moldova กล่าว ว่า เขา ได้ ส่ง เอกสาร ชุด หนึ่ง ไป ยัง รัสเซีย เกี่ยว กับ การ กระทำ ของ 13 องค์กร ทาง การ ทหาร ของ Transnistria',
 'ใน ทาง ตรงกันข้าม VasileTarlev นายก รัฐมนตรี ประเทศ Moldova กล่าวหา ว่า วัน พฤหัสบดี กอง ทหาร รัสเซีย ใน Transnistria ให้ อุปทาน อาวุธ แก่ ดินแดน Chechen รัฐมนตรี กระทรวงกลาโหม ของ รัสเซีย SergeiIvanov กล่าว ตอบ กลับ ว่า เขา " สาบาน ด้วย หัว ของ เขา " ต่อ ฐาน ทัพ รัสเซีย ใน Moldova และ มั่นใจ ว่า " ไม่ มี อาวุธ ใด ถูก ส่ง มา จาก Transnistria "',
 'FabioCapello ได้ กลาย มา เป็น บุคคล ที่ คาด ว่า กัน ว่า จะ รับ ช่วง ต่อ การ เป็น หัวหน้า ผู้ ฝึก สอน ทีม ฟุตบอล อังกฤษ จาก SteveMc Claren หลัง จาก ที่ Jos é Mourinho ปฎิเสธ การ รับ งาน ดัง กล่าว ด้วย ตน เอง',
 'อดีต ผู้ จัดการ ทีม เซลซี บุคคล ที่ ถูก กล่าวขาน กัน อย่าง กว้างขวาง ว่า จะ ได้ ตำแหน่ง นี้ ไป ครอง แต่ หลัง จาก ที่ เขา ให้ การ ยอม รับ เมื่อ หนึ่ง วัน ก่อนหน้า ว่า เขา ไม่ สนใจ ใน ตำแหน่ง นี้ อีก ต่อ ไป Capello จึง ได้ กลาย มา เป็น บุคคล ที่ ผู้คน คาดหวัง ว่า จะ ได้ รับ ตำแหน่ง',
 'ตาม คำ กล่าว ของ แหล่ง ข่าว ที่ ใกล้ชิด กับ Capello ชาว อิตาเลียน ผู้ ซึ่ง ก่อนหน้า นี้ เป็น ผู้ จัด การ ทีม เรอัลมาดริด , เอซีมิลาน , ยูเวนตุส , และ โรมา จะ มอง ว่า การ รับ ตำแหน่ง นี้ ใน อังกฤษ เป็น จุด สูง สุด ของ การ งาน ของ ตน และ ยินดี ที่ จะ เข้า เจรจา เรื่อง ตำแหน่ง',
 "ผู ู้ ที่ อาจ จะ เข้า มา ทำ หน้าที่ ใน ตำแหน่ง นี้ คน อื่น ๆ ได้แก่ Marcello Lippi ชาว อิตาเลียน , JurgenKlinsmann อดีต ผู้ ฝึก สอน ชาว เยอรมัน , และ MartinO ' Neill ผู้ จัดการ ทีม แอสตันวิลลา",
 'เขา กล่าว ว่า ราคา 100 ดอลลาร์ ต่อ บาร์เรล เป็น ราคา ที่ " ยุติธรรม " แล้ว และ จำ ได้ ว่า ใน สมัย ที่ เขา ได้ ขึ้น ดำรง ตำแหน่ง ประธานาธิบดีเวเนซุเอลา เมื่อ ปี 1999 นั้น ราคา น้ำมัน ได้ ขึ้น ไป ราว 10 ดอลลาร์',
 'ราคา น้ำมัน ดิบ ได้ ขยับ ขึ้น ถึง 100 ดอลลาร์ เมื่อ สัปดาห์ ก่อน ก่อน ที่ จะ ปรับตัว ลด ลง อีก ครั้ง',
 'ผู้ สังเกต การณ์ บาง ส่วน คิด ว่า มี ความ เป็น ไป ได้ ที่ ราคา น้ำมัน จะ พุ่ง เกิน ระดับ 100 ดอลลาร์',
 'ระหว่าง การ ซื้อขายแลกเปลี่ยน หลัง การ ประชุม สุด ยอด 2 วัน ซึ่ง คาด ว่า ส่ง ผล ให้ " คำ ประกาศ กรุงริยาด " ราคา น้ำมัน ได้ ปรับ ตัว สูง ขึ้น 80 เซนต์ ใน ตลาด นิวยอร์ก และ 66 เซนต์ ใน กรุงลอนดอน',
 'สหประชาชาติ ( UN ) ได้ เรียกร้อง ใน วัน ศุกร์ ให้ รัฐบาล ปากีสถาน ทำ การ สืบสวน กรณี ฆาตกรรม และ ลักพา ตัว โดย เฉพาะ อย่าง ยิ่ง ที่ เกิด กับ เหล่า ผู้ สื่อ ข่าว',
 'RupertColville โฆษก ประจำ สำนักข้า หลวงใหญ่ เพื่อ สิทธิมนุษยชนแห่งสหประชาชาติ แถลง ว่า " เพียง แค่ ใน ช่วง แปด วัน ที่ ผ่าน มา นี้ เรา ได้ รับ รายงาน การ ฆาตกรรม MunirShakir ผู้ สื่อ ข่าว คน หนึ่ง ใน บาลูจิสถาน เมื่อ วัน ที่ 14 สิงหาคม 2011 และ การ หาย ตัว ไป ของ RehmatullahDaparkhel ผู้ สื่อ ข่าว อีก คน หนึ่ง เมื่อ สาม วัน ก่อนหน้า ใน วาซิริสถาน เหนือ เมื่อ วัน ที่ 11 สิงหาคม "',
 'ตาม คำ กล่าว ของ คณะกรรมการเพื่อการ ปกป้อง ผู้ สื่อ ข่าว ผู้ สื่อ ข่าว 9 คน ได้ ถูก สังหาร ใน ปากีสถาน ใน ปี นี้ และ อย่าง น้อย 16 คน ได้ ถูก สังหาร ใน ปี 2010',
 'นายโคลวิล กล่าว ว่า ไม่ มี การ สืบสวน คดี ฆาตกรรม ใด ใน จำนวน นี้ ได้ ผล เป็น ที่ น่า พีงพอใจ',
 'นายโคลวิล กล่าว ว่า สหประชาขาติ ปรารถนา จะ เห็น รัฐบาล ปากีสถาน ทำ การ ทบทวน เหตุการณ์ ทั้งหมด',
 'เขา กล่าว ว่า " เรา เรียกร้อง ให้ ทุก ฝ่าย ที่ มี ความ รับผิดชอบ หยุด การ ละเมิด สิทธิ มนุษยชน ใน แง่ นี้ ใน ทันที และ เรา ร้องขอ ให้ รัฐบาล ปากีสถาน ดำเนินการ ใน ทันที เพื่อ สืบสวน คดี ต่างๆ เหล่า นี้ โดยสืบ เป็น รายคดี "',
 'องค์การนิรโทษกรรมสากล ยัง ได้ ร้องขอ ให้ รัฐบาล ปากีสถาน รับรอง ความ ปลอด ภัย และ ปกป้อง ผู้ สื่อ ข่าว และ ผู้ ที่ ทำ งาน เป็น สื่อ ใน ประเทศ',
 'พวก เขา ยัง ได้ เรียกร้อง ให้ ทางการ ปากีสถาน ทำ การ สืบสวน กรณี การ ทำร้าย บรรดา ผู้ สื่อ ข่าว และ ดำเนิน คดี กับ ผู้ ก่อ เหตุ ตาม มาตรฐาน ด้าน สิทธิ มนุษยชน ที่ ได้ รับ การ รับรอง โดย นานา ชาติ',
 'Colville กล่าว ว่า การ ทำร้าย บรรดา ผู้ สื่อ ข่าว ที่ เกิด ขึ้น ใน ช่วง ที่ ผ่าน มา นี้ ไม่ ใช่ เรื่อง ผิด ปกติ ใน ปากีสถาน และ กลุ่ม ผู้ สื่อ ข่าว มากมาย มอง ว่า ปากีสถาน เป็น หนึ่ง ใน ประเทศ ที่ อันตราย ที่สุด ใน การ ทำ งาน',
 'Shakir ถูก ยิง เสีย ชีวิต หลัง จาก ที่ ไป ทำ ข่าว เรื่อง การ ประท้วง ที่ จัด โดย กลุ่ม แบ่งแยก ดินแดน บาโลช กลุ่ม หนึ่ง',
 'IrshadMatsoi หัวหน้า ฝ่าย ประจำ สำนักข่าวออนไลน์ NewsNetwork ที่ Shakir เคย ทำ งาน อยู่ ได้ กล่าว ว่า การ ฆาตกรรม มี ความ เกี่ยวพัน กับ งาน ของ ผู้ สื่อ ข่าว',
 'Matsoi กล่าว ว่า งาน ผู้ สื่อ ข่าว ใน บาลูจิส ถาน กำลัง กลาย เป็น " อาชีพ ที่ เสี่ยง ต่อ การ สูญพันธุ์ "',
 'กลุ่ม ผู้ สื่อ ข่าว ไร้ พรมแดน ( RWB ) ได้ เรียกร้อง ให้ มี การ ลง โทษ ผู้คน ที่ ก่อ เหตุ ฆาตกรรม',
 'ตาม รายงาน ของ RWBบรรดา ผู้ สื่อ ข่าว รู้สึก ว่า ไม่ สามารถ รายงาน ข่าว ได้ อย่าง อิสระ ใน บาลูจิสถาน ซึ่ง นำ ไป สู่ การ เซ็นเซอร์ เนื้อหา ข่าว ด้วย ตน เอง ใน พื้นที่',
 'ยัง ไม่ ทราบถ ื่น ที่ อยู่ ของ Daparkhel ที่ ถูก ลักพา ตัว ไป เมื่อ วัน ที่ 11 สิงหาคม',
 'องค์กร เพื่อ เสรีภาพ ของ สื่อ ทั่ว โลก กล่าว ว่า รัฐบาล ปากีสถาน จำ ต้อง ทำ ทุก สิ่ง ที่ สามารถ ทำ ได้ เพื่อ ตาม หา ตัว เขา ใน ทันที',
 'องค์กร กล่าว ว่า " นี่ เป็น สิ่ง ที่ ยอม รับ ไม่ ได้ ที่ นัก ข่าว ท้องถิ่น จำ ต้อง ทำ หน้าที่ ของ ตำรวจ และ สืบสวน เรื่อง ด้วย ตน เอง ด้วย การ ใช้ แหล่ง ข้อมูล หรือ เส้นสาย ของ ตน เอง "',
 'คณะกรรมการเพื่อ สิทธิมนุษยชน แห่งปากีสถาน ( HRPC ) ได้ ประณาม เหตุการณ์ ทั้ง สอง',
 'HRPC กล่าว เมื่อ วัน จันทร์ ที่ แล้ว ว่า " ได้ มี กระแส ความ รู้สึก ไม่ ปลอด ภัย เกิด ขึ้น ใน หมู่ คน ทำ งาน ด้าน สื่อ ที่ ได้ ตีความ ความหมาย ของ การ ทำร้าย ผู้ สื่อ ข่าว แต่ละ คน เป็น คำ เตือน ให้ พวก เขา " ปฏิบัติ ตัว ให้ ดี " มาก ขึ้น เรื่อย ๆ "',
 'HRPC ยัง ได้ กล่าว ว่า ใน คดี ความ รุนแรง ที่ กระทำ ต่อ ผู้ สื่อ ข่าว ที่ เกิด ขึ้น ใน ช่วง ไม่ กี่ ปี ก่อนหน้า นี้ เกือบ ทั้งหมด ไม่ มี การ ระบุ ตัว หรือ ลง โทษ ผู้ ก่อ เหตุ',
 'คณะกรรมการ กล่าว ว่า " HRPC เรียกร้อง ให้ รัฐบาล ปากีสถาน ตอบสนอง ต่อ เหตุ นี้ ผ่าน ทาง การ เคลื่อนไหว ที่ มี ประสิทธิผล และ ไม่ ได้ มี แต่ เพียง คำ พูด ใน ช่วง ไม่ กี่ วัน ถัด จาก นี้ และ ให้ ส่งสาร ที่ มี เนื้อหา ชัดเจน ต่อ ผู้ ก่อ เหตุ ร้าย เหล่า นี้ ว่า รัฐบาล จะ ไม่ เป็น เพียง ผู้ ที่ ยืน มอง ดู เหตุการณ์ เฉย ๆ อีก ต่อ ไป ใน ขณะ ที่ ผู้ สื่อ ข่าว ถูก สังหาร และ ถูก จับ ตัว ไป "',
 'ตาม รายงาน ของ หน่วย สำรวจ ธรณีวิทยา ของ สหรัฐ ได้ เกิด แผ่นดิน ไหว ที่ มี ความ รุนแรง ระดับ 6 . 5 ที่ เกาะสุลาเวซี ของ อินโดนีเซีย',
 'การ สั่น สะเทือน เป็น เวลา นาน 2 นาที ได้ สร้าง กระแส ความ หวาดกลัว ให้ แก่ ชุมชน ใกล้ชาย ฝั่ง ทะเล หลาย แห่ง บน เกาะนี้',
 'ตาม คำ กล่าว ของ คณะ เจ้าหน้าที่ ยัง ไม่ มี รายงาน ผู้ ได้ รับ บาดเจ็บ แต่ ระดับ น้ำ ทะเล ได้ เพิ่ม สูง ขึ้น โดย สูง ถึง 4 เมตร ใน บาง พื้นที่',
 'แม้ ว่า รายละเอียด ของ เหตุ แผ่นดิน ไหว ใน ครั้ง นี้ ยัง ไม่ เป็น ที่ แน่ชัด หน่วย สำรวจ ธรณีวิทยา ของ สหรัฐ ได้ กล่าว ว่า การ สั่นสะเทือน ที่ เกิด ขึ้น ไม่ นาน หลัง เวลา 8 : 00 น. ของ เวลา ท้องถิ่น ( เวลา 0 : 00 น. ตาม เวลา UTC ) เกิด ขึ้น ที่ ความ ลึก 10 กิโลเมตร ( 6 ไมล์ ) ใต้ พื้น ทะเล',
 'เจ้าหน้าที่ อุตุนิยามวิทยา ท้องถิ่น ได้ รายงาน ต่อ สำนักข่าวแอซโซซิเอตเพรส ว่า แผ่นดิน ไหว ดัง กล่าว ได้ เกิด ขึ้น ที่ ระดับ ความ ลึก 37 กิโลเมตร ( 23 ไมล์ ) ใต้ ทะเลฟลอเรส',
 'นายSaddamHussein ได้ ให้การ ว่า " เขา บริสุทธิ์ " ใน การ พิจารณา คดี al - Dujail เมื่อ วัน พุธ',
 'ศาล ได้ พัก การ พิจารณา คดี 6 สัปดาห์ โดย ระหว่าง นั้น จะ ทำ การ จัด เตรียม การ คุ้มครอง ของ เขา',
 'ระหว่าง การ พิจารณา Hussein ได้ โต้แย้ง ว่า ผู้ พิพากษา ไม่ ได้ ถูก แต่งตั้ง โดย เขา ดัง นั้น จึง ไม่ ชอบ ด้วย กฎหมาย',
 'คณะ ผู้ พิพากษา ศาลยุติธรรม ชาว อิรัก ห้า ท่าน ซึ่ง มี ผู้ พิพากษา RizgarMohammedAmin เป็น ประธาน ได้ รับ มอบ อำนาจ ให้ พิพากษา ลง โทษ ประหาร ชีวิต เขา',
 'ระยะ นี้ ปรากฏ ว่า เบรินดาสโตรนัชสมาชิก รัฐสภา แคนาดา มี ความ สัมพันธ์ กับ ทาย โดมี อดีต นัก ฮอก กี้ ทีม ชาติ',
 'เธอ ปฏิเสธ ที่ จะ ตอบ คำ ถาม โดย ตรง เกี่ยว กับ ชีวิต ส่วน ตัว ของ',
 'ครั้ง นี้ นับ เป็น ครั้ง แรก หลัง มี ความ สัมพันธ์ กับ ทาย โดมี ที่ เธอ นั่ง ลง คุย กับ จอร์จสตรอมบูโรพูโลส แห่ง CBC ใน รายการ TheHour ซึ่ง เป็น รายการ โชว์ ของ เขา เพื่อ ตอบ คำ ถาม เกี่ยว กับ เรื่อง ความ สัมพันธ์ ดัง กล่าว , เรื่อง การ เมือง และ เรื่อง อื่น ๆ ใน ช่วง การ สนทนา เก้า นาที เมื่อ วัน ที่ 9 ตุลาคม',
 'การ สัมภาษณ์ ครั้ง นี้ ไม่ มี การ เปิดเผย บันทึก อย่าง เป็น ทางการ ใด ๆ แต่ สามารถ ดู ได้ จาก วีดิโอ ( ชม ได้ จาก แหล่ง ข่าว CBC ข้าง ล่าง นี้ )',
 'ตาม ที่ องค์กร สิทธิ มนุษยชน และสหประชาชาติ รายงาน ใน ใบ ประกาศ โดย UnitedNationsDevelopmentFundfor Women การ ลง นาม ใน ข้อ กฏหมาย ของ ประธานาธิบดี อัฟกานิสถาน HamidKarzai เมื่อ เดือน ที่ ผ่าน มา ทำ ให้ สิทธิ ของ สตรี ใน อัฟกานิสถานถดถอย',
 'รัฐบาล อัฟกานิสถาน ไม่ ได้ มอบ สำเนา ของ ShiaFamily Law แก่ UN หรือ องค์กร อื่น ๆ ที่ ได้ ร้องขอ โดย ให้ เหตุผล ว่า " ขัดข้อง ทาง เทคนิค " อย่าง ไร ก็ตาม UN และ นัก การ เมือง ที่ อยู่ ฝ่าย ค้าน ได้ กล่าว ว่า ข้อ กฏหมาย ดัง กล่าว มี การ จำกัด สิทธิ ของ สตรี เช่น การ ให้ สามี ของ ตน มี สิทธิ เหนือ กว่า ตน ใน ศาล ; ต้อง ได้ รับ การ อนุญาต จาก สามี เมื่อ ต้องการ ออก จาก บ้าน , เข้า รับ การ ศึกษา หรือ การ ทำ งาน หรือ เมื่อ ไป พบ แพทย์ ; และ มอบ สิทธิ การ เลี้ยงดู บุตร อันดับ หนึ่ง ให้ แก่ ญาติ เพศ ชาย',
 'ผู้ บาดเจ็บ 3 ราย ได้ รับ การ เข้า รักษาพยาบาล ใน โรง พยาบาล หลัง เกิด เหตุ ระเบิด ที่ บริษัทเซาท์เวส อินดัสเทรียล แก๊ซคอเปอร์เรชั่น โรง งาน ผลิต แก๊ส แห่ง หนึ่ง ที่ ดัลลัส ใน รัฐ เท็กซัส',
 'ถัง ออกซิเจน ฮีเลียม และ อะเซทิลีน ได้ เริ่ม ระเบิด ขึ้น หลัง จาก เกิด การ ทำ งาน ที่ ผิด ปกติ ของ ตัว เชื่อม ต่อ ที่ ใช้ ใน การ เชื่อม ต่อ กับ ถัง ของ อะเซทิลีน ใน ระหว่าง กระบวนการ ขนถ่าย แก๊ซ',
 'การ ระเบิด ทำ ให้ สะเก็ด เพลิง กระจาย ไป ใน อากาศ อาคาร และ ทาง พิเศษ ต่างๆ',
 'ควัน ดำ ที่ พุ่ง ออก มา จาก โรง งาน สามารถ มอง เห็น ได้ ไกล หลาย ไมล์ จาก ตัว โรง งาน',
 'เหตุ เพลิง ไหม้ ได้ เริ่ม เกิด ขึ้น ใน เวลา 9 : 30 น. ตาม เวลา ท้องถิ่น CDT ( UTC- 5 ) ที่ ท่า ลำเลียง สินค้า ตาม คำ กล่าว ของ ร้อย โทโจเอลลาเวนเดอร์ จาก สถานี ดับ เพลิง ดัลลัส จาก นั้น ได้ ลุกลาม ไป ยัง รถ พ่วง ซึ่ง บรรทุก แก๊ส ใน ปริมาณ ถึง 100 , 000 ลูกบาศก์ ฟุต ( ประมาณ 28 , 300 ลูกบาศก์ เมตร )',
 'เจ้าหน้าที่ ได้ ทำ การ อพยพ ผู้คน ใน พื้นที่ ภาย ใน รัศมี กว้าง ครึ่ง ไมล์ ( ประมาณ 800 เมตร )',
 'พื้นที่ บาง ส่วน ของ ทาง หลวง เชื่อม รัฐ หมายเลข 35 และ 30 ได้ ถูก ปิด การ จราจร ลง',
 'สะเก็ด เพลิง ทำ ให้ เกิด การ ติด ไฟ ไป ยัง กอง หญ้า เล็ก ๆ บน ข้าง ถนน',
 'มี รายงาน ว่า ถัง บรรจุ แก๊ส ได้ กระเด็น ไป ไกล ถึง 4 ช่วง ตึก',
 'เจ้าหน้าที่ หน่วย งาน คุ้มครอง สิ่ง แวดล้อม รวม ถึง เจ้าหน้าที่ ด้าน สิ่ง แวดล้อม ใน ท้องถิ่น และ ส่วน รัฐ ได้ ลง ความ เห็น ว่า ระดับ คุณภาพ ของ อากาศ อยู่ ใน ระดับ ที่ ยอม รับ ได้ หลัง เกิด เหตุการณ์ ระเบิด',
 'เจ้าหน้าที่ ด้าน วัตถุ อันตราย ได้ ปิด กั้น น้ำ ที่ ใช้ ใน การ ดับ เพลิง ไม่ ให้ ไหล เข้า สู่ ทาง ระบาย น้ำ ฝน ของ ดัลลัส',
 'เอดดี้ปาร์กเกอร์ จาก บริษัท Airgas ซึ่ง มี สำนัก งาน ตั้ง อยู่ ติด กับ นิคม อุตสาหกรรม ภาค ตะวัน ตก เฉียง ใต้ กล่าว ว่า " ผม เพิ่ง แนะนำ ให้ เพื่อน ร่วม งาน ของ ผม ออก มา "',
 '" หลัง จาก นั้น พวก เรา ได้ หัน หลัง วิ่ง ออก จาก ที่ เกิด เหตุ และ ได้ยิน เสียง ระเบิด ครั้งแล้ว ครั้ง เล่า "',
 '" จาก ข้อ เท็จจริง ที่ ไม่ มี ผู้ เสีย ชีวิต จาก เหตุ ระเบิด ครั้ง นี้ ดู เหมือน ว่า หน่วย ดับ เพลิง และ กู้ ภัย ฉุกเฉิน ของ พวก เรา ได้ ปฎิบัติ งาน อย่าง มี ประสิทธิภาพ "',
 '" แต่ เรา ต้อง ให้ หน่วย ดับ เพลิง ตรวจสอบ ถึง สาเหตุ ว่า ทำไม เหตุการณ์ เช่น นี้ ถึง เกิด ขึ้น ได้ ใน บริเวณ นั้น " สตีฟซัลลาซอร์ สมาชิก สภา เมือง กล่าว',
 'ผู้ บาดเจ็บ สอง คน แรน ดอลบิบบ์ วัย 52 ปี และ แดเนียลแมคเมอร์ฟี่ วัย 56 ปี ได้ ถูก นำ ตัว ส่ง โรงพยาบาลพาร์คแลนด์เมมโมเรียล เพื่อ เข้า รับ การ รักษา จาก แผล ไฟ ไหม้ ที่ ร่างกาย ส่วน บน',
 'ผู้ ได้ รับ บาดเจ็บ ราย ที่ สาม ซึ่ง เป็น คน ขับ รถ บรรทุก ไม่ ทราบ ชื่อ ได้ เข้า รับ การ รักษา และ ออก จาก ศูนย์การแพทย์เมโทดิสท์ ดัลลัส แล้ว',
 'เขา ได้ รับ บาดเจ็บ ที่ หลัง ใน ขณะ ที่ เขา ได้ กระโดด ออก จาก ที่ บรรทุก ของ รถ บรรทุก ของ เขา',
 'เด็ก ชายโมฮัมหมัดอาห์เหม็ด ลูก ชาย วัย 12 ปี ของ ดร.อาเฟียซิดดิกี นัก ประสาทวิทยา ผู้ ซึ่ง จบ การ ศึกษา จาก มหาวิทยาลัยเอ็มไอที ได้ ถูก ส่ง ไป ให้ นางเฟาเซียซิดดิกี ผู้ เป็น ป้า ของ เขา ใน เมืองอิสลามา บัด หลัง จาก ได้ อยู่ ใน สถานกักขัง ของ กอง ทัพ สหรัฐอเมริกา ที่ ตั้ง อยู่ ใน ประเทศอัฟกานิสถาน มา หลาย ปี',
 'ดร.อาเฟียซิด ดี กี กำลัง เผชิญหน้า กับ การ ถูก ดำเนิน คดี ด้วย ข้อ หา พยายาม ฆ่า นาย ทหาร ของ สหรัฐอเมริกา ใน ประเทศอัฟกานิสถาน',
 'ดร.ซิดดิกี และ บุตร ทั้ง สาม คน ของ เธอ ได้ หาย ตัว ไป หลัง ออก จาก บ้าน ของ พ่อแม่ เธอ ใน เมืองคาราจี ใน วัน ที่ 30 มีนาคม 2003',
 'เธอ ได้ แต่งงาน กับ หลาน ชาย ของ คาลิด ซีกห์โมฮัมเหม็ด ผู้ ซึ่ง ถูก กล่าวหา ว่า เป็น ผู้ บงการ การ โจมตี ใน วัน ที่ 11 กันยายน',
 'สามี ของ เธอ ถูก จับ ใน ปี 2003 และ ปัจจุบัน ถูก กักขัง อยู่ ที่ ศูนย์ กักกัน อ่าวกวนทานาโม',
 'ใน ปี 2004 ดร.อาเฟีย ได้ ถูก ชี้ โดย เอฟบีไอ ว่า เป็น " สาย ลับ และ ผู้ สนันสนุน กลุ่มอัลกออิดะห์ ที่ แสดง ชัดเจน ว่า นำ ภัย มา สู่ อเมริกา "',
 'เด็ก ชายโมฮัมหมัดอาเหม็ด อายุ เพียง 6 ปี เมื่อ เขา แม่ และ พี่ ชาย พี่ สาว ของ เขา ถูก ลักพา ตัว ไป จาก เมืองคาราจี ใน ปี 2003 และ หลัง จาก นั้น ได้ ถูก ส่ง ให้ เจ้าหน้าที่ ของ สหรัฐอเมริกา',
 'ดร.ฟาเซีย ได้ บอก นัก ข่าว หลัง จาก ที่ เด็ก ชาย ได้ ถูก มอบ ให้ เธอ โดย เจ้าหน้าที่ ของ กระทรวงกลาโหม และ หน่วย ข่าว กรอง',
 'เด็ก ชายโมฮัมหมัดอาเหม็ด ได้ มา ถึง สนามบินนานาชาติ เบนาซีร์ ใน เมืองอิสลามา บัด โดย ออก จาก เมืองคาบ ูล ด้วย เที่ยว บิน ของ สายการ บินพีไอเอ และ ถูก ส่ง ไป ที่ บ้าน พัก ของ ป้าเขา',
 'ประธาน ร่วม คณะกรรมธิการ สิทธิ มนุษยชน ปากีสถาน นายอิกบัลไฮเดอร์ กล่าว ว่า ลูก สาว ของ ดร.อาเฟีย ก็ อยู่ ที่ อัฟกานิสถาน เช่น กัน',

In [ ]:
thai_preds = model.predict(to_thai)

Generating outputs:   0%|          | 0/128 [00:00<?, ?it/s]

/usr/local/lib/python3.7/dist-packages/transformers/tokenization_utils_base.py:3524: FutureWarning:
`prepare_seq2seq_batch` is deprecated and will be removed in version 5 of HuggingFace Transformers. Use the regular
`__call__` method to prepare your inputs and the tokenizer under the `as_target_tokenizer` context manager to prepare
your targets.

Here is a short example:

model_inputs = tokenizer(src_texts, ...)
with tokenizer.as_target_tokenizer():
    labels = tokenizer(tgt_texts, ...)
model_inputs["labels"] = labels["input_ids"]

See the documentation of your specific tokenizer for more details on the specific arguments to the tokenizer of choice.
For a more complete example, see the implementation of `prepare_seq2seq_batch`.

  warnings.warn(formatted_warning, FutureWarning)

Decoding outputs:   0%|          | 0/1018 [00:00<?, ?it/s]

In [ ]:
thai_preds

['มี การ ยืนยัน ว่า ม้า วิ่ง แข่ง ที่ ได้ รับ การ อบรม อย่าง ละเอียด แปด ตัว ที่ สนาม แข่ง วิ่ง แข่ง ที่ วิ่ง แข่ง วิ่ง แข่ง ที่ สนาม แข่ง วิ่ง แข่ง ที่ สนาม แข่ง วิ่ง แข่ง ที่ สนาม แข่ง วิ่ง แข่ง ที่ สนาม แข่ง วิ่ง แข่ง ที่ วิ่ง มา วิ่ง แข่ง ที่ สนาม แข่ง',
 'คาดหวัง ว่า รัน ด ์ วิค ถูก ล็อก ไว้, และ ถูก คาดหวัง ที่ จะ อยู่ จนถึง สอง เดือน.',
 'คาดหวัง ว่า ไข้ พุพอง จะ ส่งผล กระทบ ส่วนใหญ่ ของ ม้า 7 0 0 ตัว ที่ ยืน อยู่ ที่ รัน วิค.',
 'รัฐมนตรี ว่าการ เกษตรศาสตร์ กล่าว ว่า สิ่ง อํานวย ความ สะดวก จะ ถูก กักตัว จนถึง สามสิบ วัน หลัง จาก สัญญาณ สุดท้าย ของ ไข้หวัด.',
 'กรณี นี้ คือ การ ติด เชื้อ ครั้ง แรก ของ ม้า แข่ง ม้า, ถึงแม้ ว่าจะ ติด เชื้อ ม้า หลาย สิบ ตัว ของ ม้า สาธารณะ ข้าม เอ็น ส ์ แลนด์.',
 'ไข้หวัด เป็น พาหะ ติด เชื้อ อย่าง สูง แต่ ไม่ สามารถ ถ่ายทอด ไปยัง มนุษย์ ได้.',
 'ทุกวัน นี้ การ ปิด การ แข่งขัน วิ่ง แข่ง ของ ประเทศ กําลัง ส่งผล ให้ อุตสาหกรรม สิบล้าน ดอลล่าร์ ทุกวัน.',
 'หัวหน้า ของ หัวหน้า ของ การ แข่ง ม้า N S, พี เ ตอ ร ์ V in g s กล่าว ขณะ ที่ การ แข่งขัน ของ ม้า ใน วันหยุด สุดสัปดาห์ ที่แล้ว, พี เ ต อร ์ วิธ เดอะ กรีฑา, พี เ ต อร ์ เวน ี ซ กล่าว ขณะ ที่ การ แข่งขัน',
 'คาดหวัง ว่าการ แข่ง วิ่ง ของ ออสเตรเลีย ทั้งหมด ยกเว้น เอ็น ส เวย์ และ วูด ส ์ แลนด์ ใน วันหยุด สุดสัปดาห์.',
 'ขณะ ที่ งาน แข่ง วิ่ง ฤดู ใบไม้ ผลิ ของ ซิดนีย์ ถูก ยกเลิก, ไมเคิล คาดหวัง ที่ จะ เตะ วันหยุด สุดสัปดาห์ นี้ กับ แคว ฟ ิ ้ ล คัพ.',
 'รางวัล จะ ถูก ดําเนินการ ด้วย ความ ระมัดระวัง พิเศษ เพื่อที่ จะ รักษา สถานะ ของ ไวรัส.',
 'ระหว่าง สาธารณชน ทั่วไป และ การ ทํางาน กับ ม้า เหล่า นั้น จะ ถูก ห้าม และ ฮิ ว ค ์ ฮ อก แมน และ ฮิ ว ค ์ เบส เ ต อร ์ และ ฮิ ว กก ิ ้ ง ฮ อก แมน และ ฮิ ว ค ์ ฮ อก แมน และ',
 'รัฐมนตรี ว่าการ เกษตรศาสตร์ ของ ประเทศสหรัฐอเมริกา กล่าว ว่า ฤดู ใบไม้ ผลิ ที่ ยิ่งใหญ่ ของ เกษตรกรรม, พี เ ตอ ร ์ เมอ ร ์ พูด ว่า ฤดู ใบไม้ ผลิ ของ เกษตรกรรม, พี เ ตอ ร ์ เมอ ร ์ ฟ ิ ว เน ี ย น พูด',
 'อย่างน้อย สิบเอ็ด คน ถูก ฆ่า อย่างน้อย สิบ หก ธันวาคม และ ยี่สิบ เจ็ด ใน ระแวก ของ ผู้ ค้า ยาเสพติด.',
 'ภูมิภาค ถูก ควบคุม โดย กลุ่ม คู่แข่ง คอมมิวนิสต์ คอม นา โด เวอร์ เมอ ร ์ เมอ ร ์ เมอ ร ์ เมอ ร ์ เมอ ร ์ เมอ ร ์ เมอ ร ์ เมอ ร ์ เมอ ร ์ เมอ ร ์ เมอ ร ์ เมอ ร ์ เมอ ร ์ เ ม ล ์',
 'สมาชิก ร่วม แข่งขัน ของ พวก เขา เริ่ม โจมตี สมาชิก คู่แข่ง ของ อาเซียน เพื่อ ปกป้อง เทือกเขา ของ พวก เขา.',
 'การ ระเบิด ใน ชิง เต่า, ประเทศจีน ทําให้เกิด การ ยุติการ ผลิต ไฟฟ้า ที่ ใหญ่ ที่สุด ของ โลก, จีน ทําให้เกิด การ ปิดตัว บางส่วน ของ บริษัท เทคโนโลยี ที่ ยิ่งใหญ่ ที่สุด ของ โลก เช่น ฮิ ว ล ์ - แพ ค เก อร ์, เด ส ก ิ ว ล ์',
 'การ สํารวจ ครั้ง แรก ใน ตอน นี้ แนะนํา ว่าการ ระเบิด เกิด จาก การ ระบาย อากาศ ที่ แย่, ซึ่ง ทําให้เกิด ความ เข้มข้น สูง ของ ฝุ่น เชื้อ เพลิง.',
 'เกิด เพลิง ไหม้ ขึ้น เวลา เจ็ด โมง สิบ เจ็ด โมง, ประมาณ เจ็ด โมง สิบ เจ็ด โมง เย็น, ประมาณ เจ็ด โมง สิบ เจ็ด โมง เย็น, ประมาณ เจ็ด โมง สิบ เจ็ด โมง เย็น, ประมาณ เจ็ด โมง สิบ เจ็ด โมง เย็น',
 'อย่างน้อย สาม คน ถูก ฆ่า, อย่างน้อย สิบ ห้า คน ได้ รับ บาดเจ็บ.',
 'กล่าว ว่า " ปฏิบัติการ ทั้งหมด ใน คณะกรรมาธิการ ที่ กระทบกระเทือน ยังคง หยุดชะงัก และ การ ผลิต อีก อย่าง ที่ ดําเนินการ ประมวล ผล การ ประมวล ผล การ ประมวล ผล. "',
 'แผนก การ ผลิต อื่น อื่น อื่น อื่น ใน ประเทศจีน ดําเนินการ อย่าง ปกติ.',
 'เจ้าหน้าที่ เมือง ให้ สาเหตุ ของ มลพิษ ใน อากาศ ที่ โรง งาน ขัด เงา.',
 'พวก เขา รายงาน ว่า พวก เขา รายงาน ปัญหา ฝุ่น อินทรีย์ ใน เดือน มีนาคม เมื่อ พวก เขา ตรวจสอบ เงื่อนไข การ ทํางาน ที่ ฟ อร ์ ชอน.',
 'พวก เขา วิจารณ์ ว่า คนงาน กําลัง พูด ว่า " การ ระบาย อากาศ ของ แผนก แย่. ". "',
 'ใน การ ประมวล ผล, มี ฝุ่น อะลูมิเนียม หลาย ชนิด ลอย อยู่ ใน อากาศ. "',
 'นัก ทํางาน มัก หายใจ เข้าไป ใน ฝุ่น อะลูมิเนียม เสมอ แม้ว่า พวก เขา วาง บน หน้ากาก. "',
 '" เมื่อ คนงาน ถอด ถุงมือ ผ้า ฝ้าย, มือ ของ พวก เขา ถูก ปกคลุม ด้วย ฝุ่น อะลูมิเนียม "',
 'ฟ อร ์ ค โคน ตอบ ว่า กลุ่ม กําลัง พยายาม ที่ จะ รักษา ความ มั่นคง ของ อุบัติเหตุ ทาง โศกเศร้า และ ความ มั่นคง ของ พนักงาน ของ เรา.',
 'กล่าว กัน ว่าการ เพิ่มขึ้น ของ กลุ่ม การ วิจัย IC H IS อาจจ ะ ทําให้เกิด ความ เสียหาย ของ การ ผลิต กระดาษ แอปเปิ้ล หลาย แสน ใบ ในระหว่าง ช่วง ครึ่ง ปี นี้.',
 'พวก เขา บอ กว่า มี สิ่ง อํานวย ความ สะดวก ที่ ใหญ่ กว่า ใน จีน แต่ มัน ไม่ สามารถ ชดเชย การ ชดเชย ความ เสียหาย ที่ อาจ เกิดขึ้น ได้.',
 'บางครั้ง ก็ ใหญ่.',
 'เกี่ยว กับ การ สํารวจ ทาง ธรณีวิทยา สหรัฐอเมริกา ( สหรัฐอเมริกา ) ห้า สิบ ห้า กิโลเมตร, ตะวันออกเฉียงใต้ ของ สถานี แค ช, ตะวันออกเฉียงใต้, ตะวันออกเฉียงใต้, ตะวันออกเฉียงใต้ ของ แค ช เตช ั ่ น ( 1 5 5 ไมล์ ) ตะวันออกเฉียงใต้ ของ',
 'รายงาน ว่าความ ลึก 7. 5 กิโลเมตร, ( 4. 7 ไมล์ ), แต่ สหรัฐอเมริกา กล่าว ว่า มัน ถูก ทําลาย อย่าง แย่.',
 'สหรัฐอเมริกา บอ กว่า มี อารยธรรม ที่ มีอยู่ บน หมวก น้ํา แข็ง แช่เย็น, สหรัฐอเมริกา กล่าว ว่าความ เสียหาย อาจจ ะ ลดลง เล็กน้อย.',
 'แผ่นดินไหว ที่ ใหญ่ ที่สุด ของ ประเทศแอนตาร์กติกา คือ แผ่นดินไหว ที่ ใหญ่ ที่สุด ที่ เกิดขึ้น ใน วันที่ สิบ ห้า มีนาคม ปี หนึ่ง พัน เก้า ร้อย เก้าสิบ แปด ซึ่ง เกิดขึ้น ใน วันที่ ยี่สิบ ห้า มีนาคม ปี หนึ่ง พัน เก้า ร้อย เก้าสิบ แปด ซึ่ง เกิดขึ้น ใน วันที่ ยี่สิบ เจ็ด มีนาคม ซึ่ง เกิดขึ้น ใน วันที่',
 'สํานัก ข่าว ภาษา รัสเซีย กล่าว ว่า ประธานาธิบดี เมอ ร ์ น วิลเลียม วิลเลียม แวน ิ ว เน ี ย น ใน วันอาทิตย์ ที่ จัดหา อาวุธ ของ รัสเซีย ให้ กับ สหรัฐอเมริกา ระหว่าง การ ปกครอง ของ สหรัฐอเมริกา ระหว่าง การ ปกครอง ของ สหรัฐอเมริกา, หน่วยงาน ข่าว รัสเซีย กล่าว.',
 'วอน ิ ว เน ี ย น พูด กับ กลุ่ม ของ นัก หนังสือพิมพ์ ชาว รัสเซีย, ซึ่ง แสดง ให้ เห็น ว่าการ ผลิต อาวุธ ทั้งหมด ของ สหรัฐอเมริกา, และ การ ผลิต อาวุธ ทั้งหมด ของ สหรัฐอเมริกา, และ การ ผลิต อาวุธ ทั้งหมด ของ สหรัฐอเมริกา, และ การ ผลิต อาวุธ ทั้งหมด ของ สหรัฐอเมริกา, และ การ',
 'การ ควบคุม ที่ดิน นี้ เห็น ได้ ชัด และ เรา ต้อง เรียก ผู้ ที่ ไม่ ปรารถนา จะ แก้ไข ข้อ ขัดแย้ง นี้, วาวอน ิ น.',
 'มี การ ถาม ว่า รัสเซีย ต้อง ทํา อะไร เพื่อ แก้ไข ความ ขัดแย้ง, ประธานาธิบดี เมลเบิร์น พูด ว่า มัน ต้อง ใช้ ปืนใหญ่ จาก ประเทศ นั้น.',
 'ประธานาธิบดี เน้น.',
 'เพิ่ม มัลติมีเดีย เพิ่มเติม ไป สู่ เมลโดนีเซีย สามารถ พิสูจน์ ว่า ไท รา ส ป ์ ขาย อาวุธ ไป อิตาลี ได้.',
 'เขา พูด ว่า.',
 'ศาสนิกชน กล่าว กับ มอสโก เพื่อ แก้ไข ความ ขัดแย้ง ของ ภูมิภาค นี้, กล่าว ว่า อาวุธ ของ รัสเซีย คือ การ ปกป้อง การ ปกครอง ทางการ เมือง.',
 'ผู้นํา เมอ ร ์ น เน ี ย น แจ้ง ว่า เขา ได้ ส่ง เอกสาร ไป รัสเซีย เกี่ยว กับ กิจกรรม ของ บริษัท ทหาร 1 3.',
 'กล่าว ว่า อีก อย่าง หนึ่ง, รัฐมนตรี ว่าการ ป้องกัน ชาว รัสเซีย กล่าว ว่า " ไม่ มี อาวุธ ใน ภูมิภาค ของ จีน ", และ ยืนยัน ว่า, " ไม่ มี อาวุธ ของ ชาว เยอรมัน ใน ภูมิภาค เมลเบิร์น, กล่าว ว่า, ไมเกรน, กล่าว ว่า, มิส เ ต อร',
 'ปรากฏว่า เป็น ที่ โปรดปราน ใหม่ ที่ จะ ประสบ ส เ ต อร ์ เมอ ร ์ เน อร ์ ใน ฐานะ ครู ฝึก กีฬา ฟุตบอล ชาว อังกฤษ ของ ทีม ฟุตบอล อังกฤษ หลัง จาก โจ ซาม ิ โน ฟ ิ ล ์ ฟ ิ ล เด อร ์ ใหม่ ของ ทีม ฟุตบอล ชาว อังกฤษ',
 'ผู้จัดการ เชลซี คน เก่า ได้ รับ การ พิจารณา อย่าง กว้างขวาง ใน งาน นี้ แต่ หลัง จาก เขา ยอมรับ เมื่อวาน นี้ ว่า เขา ไม่ สนใจ งาน นี้ อีก แล้ว, คา ล โล ได้ กลาย เป็น ที่ นิยม ใหม่.',
 'ภาษา อิตาลี ที่ จัดการ มา แล้ว, แ อ ค เ ต อร ์, แ อ ค ลิน, แ อ ค เ ต อร ์, แ อ ค ลิน, แ อ ค เ ต อร ์, แ อ ค ลิน, แ อ ส เ ต อร ์, แ อ ค',
 'ผู้จัดการ วิลเลียม เมอ ร ์ เมอ ร ์ เมอ ร ์ อิตาลี, อดีต ครู ฝึก กีฬา เมอ ร ์ เมอ ร ์ ลี ป ิ, อดีต ครู ฝึก กีฬา เมอ ร ์ เมอ ร ์ เมอ ร ์ เมอ ร ์ เมอ ร ์ เมอ ร ์ เมอ ร ์ ล',
 'ราคา สิบ ดอลลาร์ ต่อ ถัง เป็น " แฟร์ " และ จําได้ ว่า เมื่อ เขา เป็น ประธานาธิบดี ของ เวียดนาม ใน ปี หนึ่ง พัน เก้า ร้อย เก้าสิบ ดอลล่าร์, ราคา สูง ขึ้น ประมาณ สิบ ดอลล่าร์.',
 'ราคา น้ํามันดิบ ดิบ สูง ขึ้น ถึง หนึ่ง ร้อย ดอลล่าร์ เมื่อ สัปดาห์ ที่แล้ว ก่อน ลดลง อีก ครั้ง.',
 'นัก สังเกต การณ์ บาง คน คิด ว่า มัน เป็นไปได้ ว่า สิ่ง กีดขวาง อาจจ ะ แตก.',
 'คาดหวัง ว่าการ ค้าขาย ของ ริก ฮ ์, ราคา ของ โภชนาการ โ รส แปด สิบ ดอลลาร์ ใน ตลาด นิวยอร์ก และ หก สิบ หก ใน ลอนดอน.',
 'สหประชาชาติ ( UN ) เมื่อ วันศุกร์ ที่แล้ว เรียกว่า รัฐบาล ของ ปากีสถาน เพื่อ ค้นคว้า การ สังเวย และ การ ศึกษา มากมาย, โดยเฉพาะ นัก หนังสือพิมพ์.',
 'กล่าว กัน ว่า นัก หนังสือพิมพ์ หนึ่ง คน, มิส เ ต อร ์ ช ั ค ริเวอร์, ใน วันที่ สิบเอ็ด สิงหาคม ปี หนึ่ง พัน เก้า ร้อย เจ็ด สิบเอ็ด สิงหาคม, เ ร ท เ ต อร ์ แค ล ลี ่ เรา ได้ รับ รายงาน เกี่ยว กับ การ ฆ่า ของ',
 'ขึ้นอยู่กับ คณะกรรมการ เพื่อ ปกป้อง นัก หนังสือพิมพ์, เก้า นัก หนังสือพิมพ์, เก้า คน ถูก ฆ่า ใน ปากีสถาน ใน ปี นี้, และ อย่างน้อย สิบ หก ถูก ฆ่า ใน ปากีสถาน ใน ปี นี้, และ อย่างน้อย สิบ หก ถูก ฆ่า ใน ปากีสถาน ใน ปี นี้, และ อย่างน้อย สิบ หก ถูก ฆ่า ใน ปา',
 'คอล วิล ล ์ พูด ว่า.',
 'บอ ล วิล ล ์ พูด ว่า สหประชาชาติ ต้องการ ที่ จะ ดู การ ทบทวน ของ รัฐบาล ทั้งหมด.',
 'เขา กล่าว ว่า.',
 'สหประชาชาติ นิรโทษวิทยา ได้ กระตุ้น ให้ รัฐบาล ของ ปากีสถาน รับรอง การ ปกป้อง ของ นัก หนังสือพิมพ์ และ คนงาน สื่อ ใน ประเทศ.',
 'พวก เขา โทร มายัง หน่วยงาน ชาว ปากีสถาน เพื่อ ค้นคว้า การ โจมตี ของ นัก หนังสือพิมพ์ และ พยายาม พวก ที่ มี ความ รู้ ระดับ สากล ของ สิทธิมนุษยชาติ.',
 'การ โจมตี ของ นัก หนังสือพิมพ์ เมื่อ เร็วๆนี้ ไม่ เป็น ปกติ ใน ปากีสถาน และ กลุ่ม นัก หนังสือพิมพ์ จํานวน มาก เกี่ยว กับ ประเทศ เป็น สถานที่ ที่ อันตราย ที่สุด ที่ จะ ทํางาน.',
 'การ โต้แย้ง ที่ ประท้วง ถูก ยิง ตาย หลัง จาก ครอบคลุม การ ประท้วง ที่ จัด ขึ้น โดย องค์กร แยก กัน.',
 'หัวหน้า สํานัก ข่าว ออนไลน์ ที่ เชค ริ ทํางาน, กล่าว ว่า การ ฆ่า ถูก เกี่ยวข้อง กับ งาน ของ นัก หนังสือพิมพ์.',
 'กล่าว ว่า วารสารศาสตร์ ใน โบ ลิ ชิ ส ตัน กําลัง กลาย เป็น อาชีพ ที่ เป็น อันตราย, มาร์ ท ิ พูด.',
 'นัก รายงานข่าว ไร้ พรมแดน ปราศจาก พรมแดน ( R G B ) อุทธรณ์ เพื่อ ลง โทษ ของ ผู้ รับผิดชอบ ใน การ ฆาตรกรรม.',
 'ตาม R W B, นัก หนังสือพิมพ์ ไม่ รู้สึก อิสระ ที่ จะ รายงาน ใน โบสซิสต์, ซึ่ง นํา ไป สู่ การ ปกครอง ตน เอง ใน ภูมิภาค.',
 'ยังคง ไม่ รู้ ว่าที่ ไหน ของ แ ด ร ค เก ล, เด็ก ที่ถูก ลักลอบ ไป วันที่ สิบเอ็ด สิงหาคม ยังคง เป็น ที่ รู้จัก.',
 'องค์กร ประชาสัมพันธ์ ทั่วโลก กล่าว ว่า รัฐบาล ต้อง ทํา ทุกสิ่งทุกอย่าง ที่ พวก เขา สามารถ หา เขา ทันที.',
 'องค์กร กล่าว ว่า " มัน ไม่ เป็น ที่ ยอมรับ ที่ว่า นัก หนังสือพิมพ์ ท้องถิ่น ต้อง ทํางาน ของ ตํารวจ และ สอบสวน เกี่ยว กับ การ ใช้ การ ติดต่อ ของ พวก เขา.',
 'คณะกรรมาธิการ สิทธิ มนุษยธรรม ของ ปากีสถาน ( H CA C P ) ตัดสิน เหตุการณ์.',
 '" มี ความ รู้สึก ที่ เพิ่มขึ้น เรื่อยๆ ของ ความ ไม่ มั่นคง ระหว่าง นัก สื่อข่าว ซึ่ง พูด กัน ว่า " มี ความ มั่นคง มาก ขึ้น เรื่อยๆ เกี่ยว กับ พฤติกรรม ของ นัก สื่อข่าว ว่า " มี ความ มั่นคง เพิ่มขึ้น เรื่อยๆ. " ฮิ ช ช ์ พูด เมื่อ จันทร์ ที่แล้ว. "\'มี ความ รู้สึก ที่ เพิ่มขึ้น',
 'ส่วนใหญ่ ของ ความ รุนแรง ต่อต้าน นัก หนังสือพิมพ์ ใน สอง สาม ปี ที่ ผ่าน มา, พวก ที่ รับผิดชอบ ไม่ ถูก ระบุ หรือ ถูก ลง โทษ.',
 'คณะกรรมาธิการ กล่าว ว่า.',
 'การ สํารวจ ทาง ธรณีวิทยา สหรัฐอเมริกา.',
 'ชุมชน ชาย ทะเล จํานวน มาก บน เกาะ.',
 'ตาม ที่ เจ้าหน้าที่ รายงาน, ไม่ มี การ บาดเจ็บ, แต่ ระดับ น้ําทะเล สูง ขึ้น สี่ เมตร ใน พื้นที่.',
 'รายละเอียด ที่ แม่นยํา ของ แผ่นดินไหว ยัง ไม่ ชัดเจน, การ สํารวจ ทาง ธรณีวิทยา ของ สหรัฐอเมริกา ( 1 0 0 0, 0 0 0 เมตร ) คือ 1 0 0 กิโลเมตร ใต้ ทะเล.',
 'เจ้าหน้าที่ อุตุนิยมวิทยา ประจํา ท้องถิ่น ได้ รายงาน ไปยัง สํานัก ข่าว สื่อข่าว ที่ เกี่ยวข้อง แผ่นดินไหว ที่ เกิดขึ้น เป็น สามสิบ เจ็ด กิโลเมตร ใต้ดิน ของ ฟลอริด้า.',
 'ข้อ กล่าว ว่า " ไม่ มี ความ ผิด " ใน การ เปิด การ ไต่สวน ของ การ ไต่สวน ของ การ ไต่สวน ของ การ ไต่สวน ใน สัปดาห์ หน้า.',
 'การ โต้แย้ง ของ เขา ถูก เลื่อน ออกไป เป็น เวลา หก สัปดาห์ ในระหว่างที่ ศาล ปิด ช่วง เวลา หก สัปดาห์ ระหว่างที่ การ ป้องกัน ของ เขา จะ ถูก เตรียม.',
 'ดัง นั้น ผู้ พิพากษา ไม่ ได้ รับ การ แต่งตั้ง เป็น ผู้ พิพากษา, ฮิ ว ส ์ โต้แย้ง ว่า ผู้ พิพากษา ไม่ ได้ รับ การ แต่งตั้ง โดย เขา, ฮิ ว ชี ส โต้แย้ง ว่า ผู้ พิพากษา ถูก แต่งตั้ง, ฮิ ว ส ์ โต้แย้ง ว่า ผู้ พิพากษา',
 'ตัดสิน ลง โทษ ของ ผู้ พิพากษา ชาว อิรัก ห้า คน ที่ ควบคุม โดย ริก เก อร ์ ห้า คน มุสลิม อิหร่าน, กับ โทษ ประหาร ชีวิต ที่ กําหนด ไว้ ใน พวก เขา, จะ ตัดสิน ลง โทษ ของ เขา.',
 'เมื่อ ไม่ นาน มา นี้ เอ็ม แคนาดา เมอ ร ์ ลิน ดา ส เ ต อร ์ ที่ มี ความ สัมพันธ์ กับ ไท ดม ิ, อดีต ผู้ เล่น เอ็น ช ์.',
 'เธอ ปฏิเสธ ที่ จะ ตอบ คําถาม ตรงๆ เกี่ยว กับ ชีวิต ส่วน ตัว ของ เธอ.',
 'ตอน นี้ เป็น ครั้ง แรก ที่ เกี่ยว กับ ธุรกิจ ของ เธอ, กับ ไท โดม ิ, และ หัวข้อ อื่น อื่น ระหว่าง การ สนทนา เก้า ตุลาคม.',
 'ไม่ มี สําเนา ของ การ สัมภาษณ์ นี้ ว่าง อย่าง เป็นทางการ แต่, วีดีโอ ( ดู แฟ้ม ) สามารถ พิจารณา ได้.',
 'ลิขสิทธิ์ ของ ผู้หญิง ใน ประเทศ นั้น, ตาม กฎหมาย ของ ประธานาธิบดี ฮิ ว ด ์ ฮิ ว ซ ์ และ รายงาน ของ สหประชาชาติ สําหรับ ผู้หญิง.',
 'อย่าง ไร ก็ตาม, พวก นัก เมือง ชาว ต่าง เมือง ของ พวก เขา พูด ว่า กฎหมาย ของ สหประชาชาติ หรือ กลุ่ม นอก อื่น อื่น อื่น, ต้องการ การ ศึกษา หรือ การ จ้าง งาน, อย่าง ไร ก็ตาม, สหประชาชาติ ได้ รับ สิทธิ พิเศษ ของ ผู้หญิง, ต้องการ การ ศึกษา หรือ การ จ้าง งาน',
 'เท ร ์ ซ, เท ร ์ ช ั ่ น ซ ์, สหรัฐอเมริกา.',
 'การ ประมวล ผล ของ ออกซิเจน ออกซิเจน, เฮลิเมอร์ และ อินทรีย์ เริ่ม ระเบิด หลัง จาก ตัว เชื่อม ที่ ใช้ เข้า ร่วม กับ แบคทีเรีย ระหว่าง โพ ร เซ ส ฟ ิ ช ั ่ น ระหว่าง โพ ร เซ ส ฟ ิ ว ต ์ ของ ออกซิเจน, เฮลิเมอร์,',
 'การ ระเบิด ส่ง ซากปรักหักพัง ไปยัง อากาศ และ บน ตึก และ ทาง ด่วน.',
 'ควัน ดํา ซึ่ง สามารถ มองเห็น ได้ เป็น ระยะทาง หลาย ไมล์ จาก ความ สะดวก.',
 'แผนก ไฟ ไหม้ ของ เด ส ก ์ วอล เด อร ์, และ จาก นั้น เริ่ม การ บรรจุ น้ํามัน ประมาณ เก้า ร้อย เก้าสิบ ฟุต ของ ก๊าซ.',
 'กว้าง ประมาณ แปด ร้อย เมตร.',
 'ข้อ ตกลง ระหว่าง สหรัฐอเมริกา 3 5 และ สหรัฐอเมริกา 3 0 ถูก ปิดกั้น.',
 'เศษ ขยะ ฟลอริด้า ฟักทอง ทําให้เกิด ไฟ ไหม้ เล็กๆ ใกล้ ถนน.',
 'รายงาน ว่า ได้ ลง จอด ไกล ไป สี่ ช่วง ตึก.',
 'เจ้าหน้าที่ รักษา สิ่งแวดล้อม ของ หน่วยงาน อนุรักษ์ สิ่งแวดล้อม, รวม ทั้ง เจ้าหน้าที่ สิ่งแวดล้อม และ สภาพแวดล้อม, ได้ สังเกต ระดับ อากาศ ที่ เหมาะสม ดัง นั้น.',
 'ลูกเรือ วัตถุดิบ อันตราย หลาย ชนิด มี น้ํา ที่ ใช้ ใน กอง ไฟ จาก การ เข้าไป ใน กอง ไฟ ของ แ ท ร ็ ก ซ ์.',
 'อี ดี้ เก อร ์ ของ ฉัน พูด ว่า " ฉัน เพิ่ง แนะนํา ให้ ทีม ของ ฉัน ออกไป ข้างนอก ", " ฉัน เพิ่ง แนะนํา ให้ ทีม ของ ฉัน ออกไป ", " ฉัน เพิ่ง แนะนํา ให้ ทีม ของ ฉัน ออกไป ", " ฉัน แค่ แนะนํา ให้ ทีม ของ ฉัน ออกไป, " อี ดดี เก อร ์',
 'พวกเรา หัน และ วิ่ง และ วิ่ง และ วิ่ง และ วิ่ง ไป และ วิ่ง และ วิ่ง ต่อไป และ แค่ ได้ยิน เสียงดัง ระเบิด.',
 '" ยอมรับ ความ เป็นจริง ที่ว่า ไม่ มี สิ่ง เลวร้าย ใดๆ, มัน ดูเหมือนว่า แผนก ไฟ ไหม้ ของ เรา และ ผู้ สื่อข่าว ฉุกเฉิน ได้ ทํางาน ที่ ดี มาก.',
 '" แต่ถ้า เรา ต้องการ ให้ แผนก ดับ เพลิง ดู ว่า ทําไม มัน เกิดขึ้น ที่นั่น ใน บริเวณ นั้น, " ผู้จัดการ เทศบาล กล่าว ว่า ส เ ต อร ์ ".',
 'มี ผู้ บาดเจ็บ สอง คน, ราด ั ล เบ ิ ร ์, หนึ่ง พัน เก้า ร้อย หก สิบ ห้า ถูก พา ไป โรง พยาบาล พาร์ ท ั ล เบ ิ ร ์, หนึ่ง พัน เก้า ร้อย หก สิบ ห้า ถูก นํา ไปยัง โรง พยาบาล พาร์ ท',
 'อันดับ ที่ สาม, คน ขับ รถ บรรทุก ที่ ไม่ มี ใคร รู้จัก, ถูก ปฏิบัติ และ ถูก ปล่อยตัว ที่ ศูนย์กลาง ทางการ แพทย์ ของ แ ดม ส ์.',
 'เขา เจ็บ หลัง เมื่อ เขา กระโดด จาก รถ แท็กซี่ ของ รถ บรรทุก ของ เขา.',
 'ลูกชาย ที่ อายุ 1 2 ปี ของ นัก วิทยาศาสตร์ จิตวิทยา ประสาท และ ปริญญา โท จิตวิทยา และ ปริญญา โท ศาสตราจารย์ อัล ฟ ิ ช ั ่ น และ ปริญญา โท ของ จิตวิทยา จิตวิทยา จิตวิทยา ของ เขา และ ปริญญา โท ของ จิตวิทยา จิตวิทยา จิตวิทยา และ ปริญญา โท ของ',
 'ความ พยายาม ที่ จะ ฆ่า ทหาร อเมริกัน ใน ประเทศอินโดนีเซีย.',
 'ครั้งที่ 3 0, 2 0 3 3, 2 0 0 3, 2 3 0 3, 2 3 0 3, 2 3 0 3, 2 3 0 3, 2 3 0 3, 2 3 0 3, 2 3 0 3, 2 3 0 3, 2 3 0 3, 2 3 0 3, 2 3 0 3, 2 3 0 3, 2 0 3 3',
 'เธอ แต่งงาน กับ หลาน ชาย ของ เค ล ์ ด เชค ชี มุสลิม, หัวหน้า คน ที่ถูก กล่าวหา ว่า โจมตี ใน วันที่ 1 9 กันยายน.',
 'ขณะนี้ สามี ของ เธอ ถูก จับได้ ใน ปี หนึ่ง พัน เก้า ร้อย เก้าสิบ สาม และ ถูก จัด อยู่ ที่ ศูนย์ กักตัว กวางตุ้ง เบ ย ์.',
 'ใน ปี หนึ่ง พัน เก้า ร้อย เก้าสิบ สี่, ดร. ฮ ั ฟ ่ า ถูก พิสูจน์ โดย เจ เอบีซี ใน ปี หนึ่ง พัน เก้า ร้อย เก้าสิบ สี่, ด ร.ศ. 1 9 4 0, ด็อกเตอร์ - คี ย ์ ใน ปี หนึ่ง พัน เก้า ร้อย เก้าสิบ สี่',
 'มุสลิม ฮ ั ดม า ฮ ์ เพียง หก เมื่อ เขา และ แม่, น้อง สาว ของ เขา, น้อง สาว ของ เขา และ น้อง สาว ของ เขา, น้อง สาว ของ เขา, น้อง สาว ของ เขา และ น้อง สาว ของ เขา, น้อง สาว ของ เขา, น้อง สาว ของ',
 'นัก หนังสือพิมพ์ บอก นัก หนังสือพิมพ์ หลังจากที่ เด็กชาย ถูก มอบ ให้ เธอ โดย เจ้าหน้าที่ แผนก ภาย ใน และ สํานัก ข่าว.',
 'มุสลิม ฮ ั ดม า ห ์ มา ถึงที่ สนามบิน นานาชาติ เบนซิน ใน อิสราเอล ใน อิสราเอล จาก คาบูลี ใน เที่ยวบิน พี ไอ เอช และ ถูก พา ไป ที่ บ้าน ของ ป้า ของ เขา.',
 'คณะกรรมาธิการ สิทธิ มนุษยธรรม ของ ชาว ปากีสถาน ของ ประธานาธิบดี ชาว ปากีสถาน ฮิ ว เบ ิ ร ์ พูด ว่า ลูก สาว ของ ด็อกเตอร์ เอ ฟ า ฮ ั ย ์ พูด ว่า ลูก สาว ของ ด็อกเตอร์ เอ ฟ า ฮ ั',
 'เขา เสียใจ ที่ แม้ แต่ จะมี ประชาชาติ 4 คน, สหรัฐอเมริกา, กล่าว ว่า " นี่ เป็นความ ผิด อย่าง รุนแรง ของ กฎหมาย สหรัฐอเมริกา และ รัฐธรรมนูญ ".',
 'ครอบครัว ของ เขา กลับ บ้าน ของ เขา ใน คา รา จิ จาก ที่ ที่ เขา หายตัว ไป ห้า ปี, กับ ครอบครัว ของ เขา.',
 'ครอบครัว ของ ปากีสถาน หวัง ว่า เด็ก ที่ หายไป อีก สอง คน จะ กลับ บ้าน เร็วๆนี้, โดย การ ดําเนินการ ทาง บวก จาก รัฐบาล ของ ปากีสถาน.',
 'ครอบครัว ชาว ปาเลสไตน์ สอง คนที ่ อาศัยอยู่ ใน ตะวันออกเฉียงใต้ ตั้งแต่ ปี หนึ่ง พัน เก้า ร้อย หก สิบ หก, ถูก ไล่ออก จาก บ้าน ของ พวก เขา ตั้งแต่ ปี หนึ่ง พัน เก้า ร้อย หก สิบ หก ซึ่ง อาศัยอยู่ ใน ตะวันออกเฉียงใต้ ตั้งแต่ ปี หนึ่ง พัน เก้า ร้อย หก สิบ',
 'การ วิพากษ์วิจารณ์ เกิดขึ้น หลัง จาก การ เพิ่ม ความ กดดัน ระหว่าง ประเทศ กับ อิสราเอล เพื่อ หยุด กิจกรรม ข้อ ตกลง และ จบ การ ออก นอก บ้าน.',
 'ช่วง เวลา หก โมง เช้า และ ทิ้ง ครอบครัว และ นัก อนุรักษ์ ภัย ระหว่าง ประเทศ ที่ กําลัง อาศัยอยู่ ใน บ้าน.',
 'รายงาน ของ พวก เขา ว่า ครอบครัว ถูก กระทบกระเทือน เพราะ พวก เขา พยายาม ที่ จะ กลับ บ้าน ของ พวก เขา.',
 'รายงาน ว่า ครอบครัว ชาว ยิว ย้าย เข้า สู่ บ้าน หลัง จาก ครอบครัว ชาว ปาเลสไตน์ ถูก ไล่ออก.',
 'กล่าว ว่า ชาว ยิว ชาว อิสราเอล ชาว อิสราเอล ชาว อิสราเอล ชาว อิสราเอล เบลเยี่ยม ชาว อิสราเอล และ กล่าว ว่า ชาว ยิปซี มี สิทธิ ที่ จะ อาศัยอยู่ ที่ใดที่หนึ่ง ใน เมือง.',
 'ถึงแม้ เจมส์ เป็น ที่ รู้จัก ระหว่าง ประเทศ, ชาว อิสราเอล ยังคง เป็น ชาว อพยพ ชาว อเมริกัน, ชาว อิสราเอล ยังคง สร้าง อพาร์ตเมนต์ ของ ชาว อเมริกัน, ชาว อิสราเอล ยังคง สร้าง อพาร์ตเมนต์ ของ ชาว อเมริกัน, ชาว อิสราเอล',
 'ตะวันออก เจมส์.',
 'การ ปกป้อง พิเศษ ของ สหรัฐอเมริกา, โรมัน เซลเซียส, โรเบิร์ต เซอร์วิส, โรเบิร์ต เซอร์วิส, โรเบิร์ต เซอร์วิส, โรเบิร์ต เซอร์วิส เซลส์, โรเบิร์ต โรเบิร์ต เซอร์วิส, โรเบิร์ต เซอร์วิส เซลส์, โรเบิร์',
 'การ สร้าง ของ รัฐ ปาเลสไตน์, รวม ทั้ง สหรัฐอเมริกา, รวม ถึง สหรัฐอเมริกา, รวม ถึง สหรัฐอเมริกา, เพื่อ หยุด การ ก่อสร้าง ของ รัฐ ปาเลสไตน์, และ อนุญาต ให้ สร้าง ขึ้น ของ รัฐ ปาเลสไตน์.',
 'สิงหาคม ที่ เก้า สิงหาคม, ผล ของ การ สืบสวน ของ ตํารวจ ซึ่ง จบ ลง ด้วย การ ชน กัน ของ เด็ก วัย ห้า คน ซึ่ง จบ ลง ด้วย การ ชน กัน ของ ตํารวจ ซึ่ง จบ ลง ด้วย การ ชน กัน ของ ตํารวจ ซึ่ง จบ ลง ด้วย การ วิ่ง หนี ของ ตํารวจ ซึ่ง จบ ลง ด้วย การ วิ่ง',
 'ผล ของ การ ชน กัน ชน.',
 'เด็ก เจ็ด คนที ่ ถูก ฆ่า เมื่อ ผู้ ต้อง สงสัย ซึ่ง, หลัง จาก ปฏิเสธ ที่ จะ หยุด ตํารวจ, รีบ หนี ไปยัง รถ บรรทุก เจ ซี ราน ิ ้ ง และ เด็ก ห้า คน.',
 'พวก เขา กําลัง จะไป ดู เกม ฟุตบอล สําหรับ เด็ก วัยรุ่น เมื่อ ชน กัน.',
 'พวก เด็กๆ สี่ คน ถูก ไล่ออก จาก รถ บรรทุก และ ตาย ที่ ฉาก.',
 'กลุ่ม ผู้ ใหญ่ สอง คน และ เด็ก คน หนึ่ง ถูก พา ไป ที่ ศูนย์ รักษาการแพทย์ ชุมชน ที่ ตั้ง อยู่ ใน ฟ ราย ส ์.',
 'ยานพาหนะ ทั้ง สอง ชน กัน กับ ต้น มะนาว ที่ ชานเมือง ใกล้ สี่แยก ของ ถนน สี่ สิบ สี่ และ ถนน หนึ่ง ร้อย เก้าสิบ ใน ไดนาวา.',
 'มี ผู้ ต้อง สงสัย สาม คน, รวม ทั้ง ผู้ ต้อง สงสัย, อยู่ ใน รถ ยนต์ สอง พัน เก้า ร้อย เก้าสิบ ห้า และ ตาย ที่ ฉาก.',
 'ลักษณะ เฉพาะ ของ พวก เขา ยัง ไม่ เป็น ที่ รู้จัก ใน ฐานะ ของ พวก เขา เลย.',
 'เด็ก อื่น ถูก เรียกว่า ไซ เน ่ น ซา เล ด หนึ่ง ไมเคิล อายุ หนึ่ง ไมเคิล สาม อายุ สี่ และ โจ เช ลิน อายุ เจ็ด ปี เจ็ด.',
 'ผู้ ใหญ่ สอง คน, คาร์ลอส แซ ล เจ อร ์, ยี่สิบ เจ็ด และ เจน นี่, ยี่สิบ เจ็ด และ เจมส์, ยี่สิบ เจ็ด และ เจมส์, ยี่สิบ เจ็ด และ เจมส์, ยี่สิบ เจ็ด และ เจมส์, ยี่สิบ เจ็ด',
 'รายงาน แฟกซ์.',
 'ผล ที่ เป็นทางการ ของ การ เลือกตั้ง ครั้ง แรก ของ การ เลือกตั้ง ทั่วไป ของ สหรัฐอเมริกา ใน ปี สอง พัน เก้า ร้อย เก้าสิบ เจ็ด การ เลือกตั้ง ที่ เป็นทางการ ของ สหรัฐอเมริกา ใน ปัจจุบัน แสดง ว่า พรรคอนุรักษ์นิยม ชาว อเมริกัน ได้ รับ การ เลือกตั้ง ใหม่.',
 'ผู้นํา พรรคอนุรักษ์นิยม โดย เดล ตัน เมอ ร ์ ท จะ ใช้เวลา สี่ ปี ข้างหน้า ใน รัฐบาล ส่วนใหญ่.',
 'แ มค ช ั ่ น คือ นายกรัฐมนตรี แรก ที่ จะมี การ สนับสนุน - หลัง ตั้งแต่ ไมเคิล แฮม เบ ิ ร ์ น, ซึ่ง ดํารง ตําแหน่ง ตั้งแต่ ปี หนึ่ง พัน เก้า ร้อย เก้าสิบ เจ็ด สิบ เจ็ด สิบ เจ็ด สิบ เจ็ด สิบ เจ็ด สิบ เจ็ด',
 'มรดก ของ รัฐบาล ของ เฮ ล เบ ิ ร ์ รวม ถึง พระราชวัง ของ พระราชวัง ฮิ ว ล ์ เวย์ และ สะพาน สีชมพู ไปยัง ทะเลสาบ ไน แ มง ตัน, นิวยอร์ก.',
 'อายุ 8 8.',
 'วัน นี้ งาน ศพ ของ เขา ถูก จัด ขึ้นที่ งาน ศพ ของ เขา ถูก จัด ขึ้นที่ อ่าว คา จิ.',
 'ความ เคารพนับถือ ของ พวก เขา, การ สวด ภาวนา และ การ เผาผลาญ ศาสนา และ การ เผาไหม้ เป็น ฝูงชน และ ข้างนอก โบสถ์ ได้ รับ ความ เคารพนับถือ.',
 'การ หลบหนี ของ เจ้าหน้าที่ ตํารวจ จํานวน มาก มอง ไป ที่ ฉาก ต่างๆ ใน ฐานะ ที่ เป็น ผู้ เสียชีวิต.',

In [ ]:
# def post_process(pred):
#   post_th_pred = []
#   for sentence in pred:
#     post_th_pred = string.replace("&apos;", "'")

#   return post_th_pred

In [ ]:
# english_preds_new = post_process(english_preds)

In [ ]:
eng_th_bleu = sacrebleu.corpus_bleu(thai_preds, thai_truth)
print("English to Thai: ", eng_th_bleu.score)

English to Thai:  0.1010877860789219

# Submission Testset

In [ ]:
!gdown --id 1khuxHPjTTR5d2tL356i8qd-M8JFK2gFu

/usr/local/lib/python3.7/dist-packages/gdown/cli.py:131: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  category=FutureWarning,
Downloading...
From: https://drive.google.com/uc?id=1khuxHPjTTR5d2tL356i8qd-M8JFK2gFu
To: /content/testset_v1_3fnd5.zip
100% 106k/106k [00:00<00:00, 15.6MB/s]

In [ ]:
!unzip -qq /content/testset_v1_3fnd5.zip

replace TestSet_ForSuperAI_Release01/test.en? [y]es, [n]o, [A]ll, [N]one, [r]ename: N

In [ ]:
path_en = '/content/TestSet_ForSuperAI_Release01/test.en'
# path_th = '/content/TestSet_ForSuperAI_Release01/test.th'
test_df = pd.DataFrame(extract_data(path_en), columns = ['en_text'])
# test_df['th_text'] = extract_data(path_th)
test_df = test_df[:1520]
test_df

                                                en_text
0                                        What! on fire!
1                                   what is your hobby?
2                          This is a tragic love story.
3                                    Is this road safe?
4              Please turn in your assignments on time.
...                                                 ...
1515  He criticised the outgoing head of the U.N.'s ...
1516  "In the past, the United States government sto...
1517  ExxonMobil wishes to assure members of the pub...
1518  The inquest was opened at the request of famil...
1519  Despite beginning out-patient treatment next w...

[1520 rows x 1 columns]

In [ ]:
# thai_truth = valid_df['th_text'].tolist()
to_thai = test_df['en_text'].tolist()

In [ ]:
thai_preds = model.predict(to_thai)

Generating outputs:   0%|          | 0/190 [00:00<?, ?it/s]

/usr/local/lib/python3.7/dist-packages/transformers/tokenization_utils_base.py:3524: FutureWarning:
`prepare_seq2seq_batch` is deprecated and will be removed in version 5 of HuggingFace Transformers. Use the regular
`__call__` method to prepare your inputs and the tokenizer under the `as_target_tokenizer` context manager to prepare
your targets.

Here is a short example:

model_inputs = tokenizer(src_texts, ...)
with tokenizer.as_target_tokenizer():
    labels = tokenizer(tgt_texts, ...)
model_inputs["labels"] = labels["input_ids"]

See the documentation of your specific tokenizer for more details on the specific arguments to the tokenizer of choice.
For a more complete example, see the implementation of `prepare_seq2seq_batch`.

  warnings.warn(formatted_warning, FutureWarning)

Decoding outputs:   0%|          | 0/1520 [00:00<?, ?it/s]

In [ ]:
thai_preds

['เกิด อะไร ขึ้น บน ไฟ ไหม้?',
 'งาน อดิเรก ของ คุณ คือ อะไร?',
 'นี่ เป็น เรื่อง รัก ที่ เศร้าสร้อย.',
 'ถนน นี้ ปลอดภัย ไหม?',
 'กรุณา โอน งาน ของ คุณ ตรง เวลา.',
 'ช่าง น่า เสียดาย อะไร อย่างนี้?',
 'แม่ เอา ตุ๊กตา ใหม่ ให้ ฉัน, และ ฉัน ชอบ มัน.',
 'สามี ของ ฉัน ทํา ให้ ฉัน สบายใจ เสมอ.',
 'เขา สนิท กับ พ่อ ของ เขา มาก.',
 'ปักกิ่ง เป็น เมืองหลวง ของ จีน.',
 'ขอบคุณ ที่ ช่วย ฉัน. บี - ยินดี ต้อนรับ.',
 'ฉัน ไม่ ชอบ ว่ายน้ํา.',
 'ใบ หน้า ของ เขา เป็น สีขาว เหมือน กระดาษ.',
 'เรา ต้องการ ความ ช่วยเหลือ ที่ เชี่ยวชาญ.',
 'เรา มา แข่งขัน กัน ดู ว่า ใคร วิ่ง ไป ที่ ต้น ใหญ่ ก่อน.',
 'อย่า ทํา ให้ ฉัน ยุ่งยาก.',
 'เข็มกลัด สูง กว่า นี้ บ้าง ไหม?',
 'เขา เอา กุหลาบ สีแดง ให้ ฉัน หนึ่ง ช่อ.',
 'เที่ยวบิน ทีจี สาม ศูนย์ มา ถึง เวลา กี่ โมง?',
 'เรา จะ พบ คุณ พรุ่ง นี้ เวลา แปดโมง ครึ่ง ที่ ประตู โรงเรียน.',
 'ไม่ มี ใคร ใน สํานัก งาน.',
 'กระเป๋า ของ เขา ติด อยู่ บน โต๊ะ.',
 'ฉัน ไม่ ต้องการ กิน, ฉัน อิ่ม.',
 'คุณ ถูก หลอกลวง.',
 'ฤดู ร้อน ใน กวางตุ้ง ค่อนข้าง ร้อน.',
 'ฉัน ชอบ ดู เกม วอลเลย์บอล ของ ผู้หญิง ญี่ปุ่น.',
 'เมื่อ เร็วๆนี้ มี อะไร เปลี่ยนแปลง ใน ปักกิ่ง บ้าง ไหม?',
 'ถนน หนาวเย็น, ซึ่ง หมายความว่า อุณหภูมิ ต่ํา กว่า ศูนย์.',
 'ฉัน เป็น คน เดียว ที่ บ้าน, ไม่ มี ใคร อีก.',
 'ฉัน ใส่ นม ใน ตู้เย็น.',
 'พ่อ ของ ฉัน ดูแล ครอบครัว ทั้งหมด เสมอ.',
 'ฉัน อุ้ม เด็ก และ ปล่อย ให้ เขา นอน หลับ.',
 'เธอ มี ความ รับผิดชอบ ต่อ การ ครอบคลุม ข่าว กีฬา.',
 'หนังสือ เล่ม นี้ หนา สาม เท่า หนังสือ เล่ม นั้น.',
 'เขา ไม่ สามารถ วาง มัน ลง กับ แล็ป ท็อป นั่น ได้.',
 'ฉัน อ่าน หนังสือ เล่ม นี้ มากกว่า สิบ ครั้ง.',
 'เขา พูด ออก มา มาก.',
 'ผล การ สอบ ภาค กลาง ของ ครู ของ เขา ดี มาก, และ เขา ได้ รับ การ ยกย่อง จาก ครู ของ เขา.',
 'ฉัน เป็น หวัด และ ไอ และ ปวด หัว.',
 'เขา ไม่ เพียง แต่ ร้อง เพลง ดี เท่านั้น, แต่ ยัง ประกอบ ดนตรี ด้วย.',
 'เขา รัก โรงเรียน ใหม่, แต่ มัน ไกล เกิน ไป จาก บ้าน.',
 'ไม่ว่า ผู้หญิง โกหก เรา อย่าง ไร, เรา ไม่ สนใจ.',
 'กระดาษ นี้ ประกอบด้วย สาม ส่วน.',
 'โต๊ะ อยู่ ตรงกลาง ห้อง.',
 'ครู สอน บ้านพัก ของ โรงเรียน ประถม ของ ฉัน เป็น มิตร.',
 'เขา พูด ภาษา อังกฤษ ได้ ดี.',
 'พัสดุ ของ ฉัน อยู่ ที่ ไหน?',
 'สิ่ง ที่ ฉัน โปรดปราน คือ ไส้กรอก.',
 'มา นี่ เด็ก ผู้หญิง มา นี่ เถอะ.',
 'เรา ยัง เป็นกลาง.',
 'เมื่อ มากกว่า ห้า ร้อย ปี ที่ ผ่าน มา เมือง ยังคง สงวน โบสถ์ จาก เมือง นี้ อีก มากกว่า ห้า ร้อย ปี มา แล้ว',
 'รายงาน เสร็จ ทัน เวลา.',
 'เธอ ไป โรงเรียน พร้อมกับ กระเป๋า นักเรียน.',
 'เขา จดจํา โคลง.',
 'สี เย็น เหมาะ กับ พื้น หลัง มาก ที่สุด.',
 'รูปถ่าย เหล่า นี้ ถูก นํา ไป ขณะ ที่ นักเรียน ปริญญา โท กําลัง ทําการ ทดลอง.',
 'เขา เป็น สิ่ง ที่ น่า รําคาญ อย่าง ยิ่ง.',
 'สัตว์ จํานวน มาก กําลัง ถอนตัว, เช่น ปู.',
 'ใน การ ทดสอบ ครั้งนี้ บี : คุณ ทําได้ ดี ใน การ ทดสอบ ครั้งนี้, บี : บี : กัน?',
 'เธอ หลีกเลี่ยง การ พูด กับ คน แปลกหน้า.',
 'เขา ต้อง ไป.',
 'ผู้ สื่อข่าว พูด เรื่อง ของ เขา กับ บรรณาธิการ.',
 'เรา หยุด.',
 'โดยปกติ คําถาม ถูก นํา มา ใช้ เป็น หัวเรื่อง ที่ ไม่ มี การ ตรง ต่อ เวลา.',
 'นี่ ไม่ ใช่ ปัญหา ใหญ่.',
 'พฤติกรรม ที่ โรงเรียน, เขา ประพฤติ ตน อย่าง กระตือรือร้น.',
 'ไวรัส ถูก กําจัด โดย ซอฟต์แวร์ ป้องกัน ไวรัส.',
 'แก้ว นี้ แตก อย่าง ที่สุด.',
 'เขา ไม่ ต้อง รู้.',
 'คุณ ไม่ จําเป็นต้อง เป็น ผู้ดี มากกว่า เขา.',
 'ไม่เป็นไร ถ้า คุณ กลับมา ใน ใบ รายชื่อ, พยายาม ที่ จะ ปรับปรุง ตําแหน่ง ของ คุณ ใน ครั้ง หน้า.',
 'แม่ เอา ตุ๊กตา ผ้า ราด ให้ ฉัน.',
 'เด็ก ตัว นี้ ซุกซน มาก.',
 'คุณ เสียใจ อะไร? เธอ ผิว หนา มาก.',
 'ขอบคุณ ที่ บอก เรา ไม่เช่นนั้น เรา จะ หลงทาง.',
 'การ จัดหา หนังสือ ของ เรา สั้น มาก.',
 'ตอน นี้ คุณ รู้จัก ขั้นตอน ทั่วไป, แล้ว เห็น ไหม ถ้า คุณ สามารถ ย้าย ร่างกาย ของ คุณ.',
 'จาน เย็น.',
 'อาหาร ไทย ดี ที่สุด.',
 'คุณ กิน ไหม?',
 'โต๊ะ ยาว สอง เมตร.',
 'เกิด อะไร ขึ้น?',
 'ฉัน สวม รองเท้า ขนาด สามสิบ สาม.',
 'เขา ตี น้อง ชาย ของ เขา หลาย ครั้ง.',
 'ขอโทษ, ฉัน ผิด.',
 'ชาย คน นี้ มี พรสวรรค์ มาก',
 'คุณ กําลัง จะไป ประชุม ใช่ไหม?',
 'ตึก สูง สิบ แปด ชั้น สูง.',
 'คุณ สามารถ หา อัน อื่น ให้ ฉัน อีก อัน หนึ่ง.',
 'เธอ กําลัง สวม เสื้อเชิ้ต สีชมพู.',
 'สวนสาธารณะ ตั้ง อยู่ ตรงกลาง ของ เมือง.',
 'การ มา เยือน ของ เธอ ทํา ให้ ฉัน ประหลาดใจ.',
 'ฉัน ไม่ ต้องการ อะไร ใน โลก นี้ ยกเว้น คุณ.',
 'เขา สามารถ สะกด คํา ง่ายๆ ใน อายุ ของ สอง คน ได้.',
 'ฉัน เช็ด โต๊ะ ด้วย ผ้า เช็ดตัว ชื้น.',
 'เสื้อ โค๊ต นี้ ทํา ด้วย วัสดุ อะไร?',
 'เรา ไป เยี่ยมชม พิพิธภัณฑ์ ของ พระราชวัง.',
 'อาหารเย็น เกือบ เสร็จ แล้ว.',
 'สัญลักษณ์ ของ จีน.',
 'เขา เล่น ฟุตบอล บน สนาม ฟุตบอล.',
 'คุณ ทั้ง สอง โต้แย้ง เกี่ยว กับ อะไร?',
 'พวก เขา ขึ้น รถ บัส สอง ชั้น.',
 'พวก เขา เติบโต มาก.',
 'อํานาจ ทํา ให้ เขา เป็น คน ชั่วร้าย.',
 'เขา ตก จาก เก้าอี้ ของ เขา ด้วย ความ ประหลาดใจ.',
 'แมรี่ กําลัง จะไป ทํางาน ธุรกิจ เดือน หน้า.',
 'เขา เกิด และ เติบโต ขึ้น ใน ลอนดอน.',
 'ฉัน ต้องการ หายใจ ออก มา จาก หน้าต่าง.',
 'ฉัน ไม่ เคย สงสัย เธอ.',
 'เขา บริจาค ทรัพย์สมบัติ ของ เขา เพื่อ การ กุศล.',
 'นัก เขียน ที่ มีชื่อ เสียง สัมภาษณ์ นัก เขียน ที่ มีชื่อ เสียง.',
 'คุณ สามารถ เห็น ริบบิ้น ที่ ปราศจาก ประสบการณ์ ลม และ ฝน อย่าง ไร?',
 'เป้าหมาย ของ การ แข่งขัน ของ ฉัน คือ การ เน้น การ เข้า ร่วม, ไม่ ใช่ การ ชนะ หรือ การ แพ้.',
 'เกม ไร้ สาระ ของ ชาติ จบ ลง.',
 'เขา วิ่ง รอบ สนาม เด็ก เล่น ทุกวัน.',
 'ชุด นี้ มี หก เล่ม.',
 'การ ทดสอบ แสดง ให้ เห็น ว่า เขา มี สายตา แย่ ใน แง่ เดียว.',
 'กรุณา ใส่ ปลั๊ก ของ ทีวี ลง ใน ตะขอ.',
 'ฟ ราย ค ์ อยู่ ใน ลิ้นชัก ที่ สอง.',
 'ฉัน รับประกัน คุณภาพ ของ ผลิตภัณฑ์ ของ ฉัน.',
 'หลัง จาก โทร ทางไกล, คุณ สามารถ ถาม ผู้ ประกอบการ เกี่ยว กับ เวลา และ อัตรา โทรศัพท์ ของ คุณ.',
 'ศาสตราจารย์ จะ รู้ ว่า รายงาน ถูก คัดลอก.',
 'เขา ต้อง ส่ง มัน ไปยัง โลก.',
 'พวก เขา ไม่ เคย ทะเลาะ กัน หน้า ลูก ๆ.',
 'พวกเรา กระโดด ขึ้น รถ คัน สุดท้าย ของ รถไฟ.',
 'เขา เงียบ อยู่ สัก ครู่, แล้ว พูด ต่อไป.',
 'เจ้านาย กิน แอปเปิ้ล สอง สาม ลูก และ ชั่ง น้ําหนัก พวก มัน, แค่ สอง ปอนด์.',
 'ฉัน ไป โรงเรียน โดย รถ บัส.',
 'เรา ทํางาน ทั้งหมด.',
 'กระดาน นี้ ไม่ สามารถ ทน น้ําหนัก 1 0 0 กิโลกรัม ได้.',
 'เขา ไม่ ได้ ดําเนินการ ตาม แผนการ.',
 'เรื่อง นี้ มี ความ จริง',
 'เขา บรรลุ ความ สําเร็จ ที่ ยิ่งใหญ่ มาก, ซึ่ง เป็น ที่ นิยม.',
 'สํานวน หลาย ภาษา มาจา ก เรื่องราว ทาง ประวัติศาสตร์.',
 'เขา ขอบคุณ เธอ อย่าง จริงใจ.',
 'ระดับ เสียง ของ รายการ ทีวี ยังคง เพิ่มขึ้น.',
 'ยาว สิบ หก เซนติเมตร.',
 'เมื่อ ฉัน ทํางาน เสร็จ, ฉัน ชง กาแฟ ใน ห้อง ครัว.',
 'เขา เตรียมตัว อย่างดี สําหรับ การ โต้วาที ของ วัน นี้.',
 'เขา พูด ซ้ํา นี้ กับ ฉัน ราว กับ ฉัน มี ปัญหา การ ได้ยิน.',
 'เขา เอา กล่อง ออก จาก ลิ้นชัก.',
 'รูปภาพ ประจํา ตัว น่าเกลียด มาก.',
 'หนังสือ เล่ม นั้น ถูก ตีพิมพ์.',
 'ผลิตภัณฑ์ ของ เรา ถูก ส่งออก ไปยัง สิบ ห้า ประเทศ.',
 'ประธานาธิบดี จะ เข้า ร่วม การ ประชุม ครั้ง หน้า.',
 'เท่ากัน สอง ที่ สอง',
 'เวลา นี้ คือ เวลา ที่ เรา จะ ลบ หน้าที่ ทาง ด้าน จิตใจ ของ คุณ.',
 'ปัญหา ควร จัดการ ทัน เวลา.',
 'ข้อมูล นี้ ถูก ล่าช้า ผ่าน ทาง ล่า นกพิราบ.',
 'ไม่ มี ใคร รู้ ที่มา ของ ตํานาน นี้.',
 'ผ้า นี้ สามารถ ใช้ สําหรับ ผ้า ม่าน ได้.',
 'เธอ แก้ไข ปัญหา นี้ อย่าง สร้างสรรค์.',
 'เด็ก เป่า เทียน บน ขนมเค้ก วัน เกิด.',
 'เลขานุการ ส่วน ตัว ของ นายกรัฐมนตรี ได้ ลาออก.',
 'มี แต่ รายละเอียด เล็กๆน้อยๆ ที่ จะ ทบทวน.',
 'หัวขโมย วิ่ง หนี ไป จาก ธนาคาร อย่าง รีบเร่ง.',
 'พวก เขา ตาม เบาะแส เหล่า นั้น และ หาคําตอบ.',
 'การ แสดง ที่ ใช้ ใน อเมริกาเหนือ เท่านั้น, แต่ ตอน นี้ มัน อยู่ ทุกแห่ง.',
 'ฉัน ต้องการ กิน ก๋วยเตี๋ยว ต้ม ใน น้ําส้ม.',
 'ค่า เล่าเรียน มัธยม ปลาย สูง สามารถ ไล่ นักเรียน ออก จาก งานเลี้ยง และ การ เรียน อย่าง หนัก ได้.',
 'ฉัน เก็บ เงิน ไว้ 1 0 0 0 ปอนด์ เป็น วัน ฝนตก.',
 'การ ดํารง ชีวิต ของ คน ต่าง ด้าว เชื่อ.',
 'มาตรการ เหล่า นี้ ทํา ให้ เศรษฐกิจ สูง ขึ้น อีก ครั้ง.',
 'โทรศัพท์ มือถือ ของ ฉัน อยู่ ที่ ไหน?',
 'ฉัน ตื่น ตอน หก โมง เช้า.',
 'พิธี แต่งงาน ของ พระราชพิธี จะ ถูก ถ่ายทอด ทาง โทรทัศน์.',
 'มี หลาย สิ่ง บน โต๊ะ มาก เกิน ไป.',
 'คุณ จําเป็นต้อง อ่าน บทความ นี้ อย่าง ระมัดระวัง.',
 'ขอโทษ, ฉัน สาย สิบ นาที.',
 'ภาพวาด ของ คุณ ขาย ราคา เท่า ไร?',
 'ทุกคน ชอบ หนัง เรื่อง นี้.',
 'คุณ มา ถึง โรง แรม เวลา กี่ โมง?',
 'เรา รอ ที่ เคาน์เตอร์ ครึ่ง ชั่วโมง.',
 'สวัสดี ทุกคน, กรุณา หมุน หนังสือ ไปยัง หน้า แรก.',
 'ฉัน ไม่ รู้ ว่า เขา ถูก หรือ ไม่.',
 'ฉัน ต้องการ พา ลูก ของ ฉัน ไป หา หมอ.',
 'เมื่อวาน นี้ ฉัน ยุ่ง อยู่ กับ การ ทํา ขนมเค้ก.',
 'เขา พยายาม ที่ จะ เรียน ภาษา ฝรั่งเศส.',
 'ความ ดัน เลือด ของ เขา ต่ํา ผิดปกติ อย่าง ผิดปกติ.',
 'ภรรยา ของ ฉัน ทํา กระเป๋า เป้ ของ เธอ หาย ใน รถไฟ ใต้ดิน.',
 'ลิฟต์ นี้ ถูก ออกแบบ เพื่อที่ จะ พา คน สิบ คน.',
 'เหมาะ กับ การ ดู พระอาทิตย์ ตก.',
 'ม้า เป็น พืช สมุนไพร.',
 'พวกเรา ไม่ ได้ เจอ กัน สักพัก, ใช่ หรือ ไม่?',
 'มัน ยาก แค่ ไหน ที่ จะ ประสบ ความ สําเร็จ?',
 'แม้ว่า เธอ เป็น นัก ร้อง ที่ มีชื่อ เสียง, เธอ แต่งตัว เหมือน เด็ก ผู้หญิง ธรรมดา.',
 'ไม่ มี ความ จําเป็น ที่ จะ พิมพ์ ไฟล์ นี้.',
 'แน่ใจ ว่า ฆ่า เชื้อ ด้วย ผ้า ฝ้าย ชนิด แอลกอฮอล์ ก่อน ฉีดยา.',
 'พ่อ ของ ฉัน เป็น นักการ ทูต และ ทํางาน ที่ สถานทูตไทย ใน จีน.',
 'เธอ สวม วิกฤต สี ที่ แตกต่าง ทุกวัน.',
 'ไม่ มี ทาง เลือก สําหรับ แม่.',
 'เขา เป็น ครู สําหรับ ชีวิต ของ เขา ครึ่งหนึ่ง.',
 'ฉัน ต้องการ ซื้อ มีด สําหรับ ตัด ผัก.',
 'ต้นไม้ นี้ ทุกแห่ง.',
 'เขา ภูมิใจ มาก กับ งาน ของ เขา.',
 'ฉัน ต้องการ กิน ผลไม้, เช่น แอปเปิ้ล, ใบ มะพร้าว, กล้วย และ อื่นๆ.',
 'ฉัน เกรง ว่า มัน จะ ยาก ที่ จะ รักษา มัน.',
 'กรุณา ฝาก ชื่อ และ ที่อยู่ ของ คุณ.',
 'เรื่อง นี้ ต้อง ถูก สอบสวน.',
 'ลิง เก่ง มาก.',
 'ท้อง ของ ฉัน กําลัง ร้อง.',
 'คุณ ไม่ มี ใคร ดี กับ ฉัน อย่าง คุณ',
 'บ้าน ของ คุณ ข้าม จาก ธนาคาร ใช่ไหม?',
 'ความ รัก ที่ ยั่งยืน ตลอดไป แสดง ให้ เห็น ดอก กุหลาบ 9 9.',
 'ในที่สุด เขา ก็ บรรลุ เป้าหมาย ของ เขา.',
 'อุตสาหกรรม นี้ ต้อง จัดการ กับ คน ทุก ประเภท.',
 'ฉัน เสียใจ ที่ ได้ ถาม, แต่, ฉัน สนใจ เรื่อง นี้ มาก.',
 'พวก เขา ใช้ เงิน จํานวน มาก เมื่อ พวก เขา เดินทาง.',
 'ตลาด ใหญ่ นี้ นํา สินค้า มา รวมตัว กัน จาก ทั่วโลก.',
 'ชาย ชรา นั่ง กระโดด ใต้ หมอน.',
 'แพทย์ ใน โรง พยาบาล นี้ ได้ รับ การ ปฏิบัติ ที่ ดี.',
 'ถ้า งาน ของ คุณ น่า เบื่อ เกิน ไป, ดัง นั้น กระโดด หนี.',
 'เขา ถูก ย้าย ไปยัง หน่วย ของ เรา.',
 'ภรรยา ของ เขา รับราชการ เป็น เลขานุการ ส่วน ตัว ของ เขา.',
 'ขอโทษ ที่ ใช้เวลา มาก เกิน ไป.',
 'ฉัน จําได้ ว่า เขา สวม ชุด สูท สีฟ้า อ่อน.',
 'ฉัน อยู่ ใน แนวทาง ของ ผู้จัดการ ของ เรา, ฉัน ต้อง ออกไป จาก ทาง.',
 'น่า เสียดาย, สาย ของ จักรยาน ของ ฉัน ถูก เจาะ.',
 'การ สูบ บุหรี่ ทําให้เกิด มะเร็ง หรือ เปล่า?',
 'เขา วาง แผนที่ ไว้ ข้าง บน.',
 'คุณ คิด ว่า เครื่องบิน จะ มา ถึง ทัน เวลา ไหม?',
 'เธอ ไม่ ชอบ เธอ มาก, แต่ เธอ มีเหตุผล มาก.',
 'เรา จะ มา ถึง โรง แรม เวลา สี่ นาฬิกา และ เช็คอิน.',
 'เธอ รอคอย การ กลับมา ของ สามี อย่าง กระตือรือร้น.',
 'การ เติบโต ของ ค่า จ้าง ที่ สูง กว่า เท่ากับ ภาษี ที่ สูง กว่า.',
 'พฤติกรรม ของ เขา ทํา ให้ ฉัน ผิดหวัง จริง ๆ.',
 'ฉัน จะ ทา เนย ขนมปัง ปิ้ง, ส่ง มัน ให้ ฉัน.',
 'ผลิตภัณฑ์ พื้นเมือง ดั้งเดิม ของ จีน คือ อะไร?',
 'พื้นที่ นี้ มี ประชากร หนาแน่น.',
 'ผู้หญิง ต้อง มี ตําแหน่ง ที่ เท่าเทียม กัน ใน สังคม.',
 'ฉัน กัด ริมฝีปาก ด้วย ความ เจ็บปวด และ ผงก ศรีษะ.',
 'วิธี ที่ ดี ที่สุด ที่ จะ จัดการ แบตเตอรี่ เก่าๆ คือ อะไร?',
 'การ ตกปลา เป็น งาน อดิเรก ที่ ฉัน โปรดปราน.',
 'มี นก ใน รัง อยู่ บน ต้น ของ ต้นไม้.',
 'วาง ปืน ลง บน หัว ของ นักโทษ และ ตะโกน ใส่ ตํารวจ, โยน ปืน ลง มา.',
 'ทันตแพทย์ เติม รู ใน ฟัน.',
 'เขา คลาน ไปมา บน พื้น, เล่น กับ ปู่ ของ เขา.',
 'เรา ไม่ สามารถ แก้ ปัญหา นี้ เอง ได้.',
 'ฉัน มี วันที่ น่า รําคาญ มาก.',
 'เธอ มี กอง กระดาษ เขียน อยู่ บน โต๊ะ ของ เขา.',
 'แม่ ดูแล ลูก ๆ สี่ คน ของ เธอ อย่าง ยุติธรรม.',
 'ใน แง่ ความ สามารถ ใน การ ทํางาน, เขา ไม่ ใช่ คู่ต่อสู้ ของ คุณ เลย.',
 'เมื่อ เลือก เด ต, เธอ เพียง แต่ ดู ลักษณะ ภาย นอก เท่านั้น.',
 'ผลผลิต รวม ของ สับปะรด ใน เมือง นี้ สูง กว่า หนึ่ง ล้าน ตัน.',
 'ขอบคุณ ที่ หา เขา ใน วัน นั้น และ พา เขา ไป โรง พยาบาล.',
 'ลูก สาว ของ ฉัน อายุ เท่า เดิม เหมือน ลูก สาว ของ ฉัน.',
 'เธอ ไม่ ได้ กิน สัก วัน และ ตา ของ เธอ มืดมัว เพราะ ความ หิว.',
 'การ สูบ บุหรี่ เป็น อันตราย มากกว่า ประโยชน์.',
 'เขา ตาย เพื่อ ช่วย เด็กๆ จาก การ จม น้ํา.',
 'เปิด ร้าน อาหาร ด้วยกัน เถอะ.',
 'นาฬิกา ข้อ มือ ของ ฉัน ช้า ไป ห้า นาที.',
 'ฉัน คิดถึง เขา มาก.',
 'เธอ มี ไข้ และ ทิ้ง ทุกอย่าง ที่ เธอ กิน.',
 'ฉัน พบ สูตร ลับ.',
 'ฉัน ควร วาง แว่น ของ ฉัน ที่ ไหน?',
 'คุณครู ไม่ สามารถ บอก ฝาแฝด แยก กัน ได้.',
 'พรุ่ง นี้ ฉัน จะ เริ่ม เรียน เพื่อ การ สอบ.',
 'เภสัชกร ให้ ยา แก่ ผู้ ป่วย.',
 'บริษัท นี้ มี โอกาส ที่ จะ เติบโต.',
 'ความ แม่นยํา ของ การ แปล เป็น สําคัญ.',
 'คุณ สนับสนุน หรือ ต่อต้าน เรา?',
 'คําถาม ของ คุณ เกิน ความ รู้ ของ ฉัน.',
 'เรา ควร วิเคราะห์ มุมมอง ทั้งหมด ของ ปัญหา.',
 'แขก ชาว อังกฤษ ที่ มา ประเทศจีน ใน ครั้งนี้ พัก ที่ สถานกงสุล.',
 'วันหยุด ฤดู ร้อน, และ แม่ ของ ฉัน พา ฉัน ไปยัง บ้าน ปู่ ของ ฉัน.',
 'ยี่สิบ ห้า เซนต์ สําหรับ หนังสือพิมพ์ ตอน เย็น.',
 'ปรับ ตําแหน่ง ของ กล้อง ให้ เหมาะ กับ ทิวทัศน์.',
 'หนังสือ เล่ม นี้ เหมาะ กับ ความ ต้องการ ของ เรา.',
 'ฉัน ต้องการ สําเนา ของ บัตร ประชาชน ของ คุณ.',
 'ส่วนใหญ่ เขา มี ความ รับผิดชอบ ใน การ จัดหา สินค้า และ การ ขนส่ง สินค้า ใน บริษัท.',
 'เมื่อ เร็วๆนี้ เขา ได้ ตีพิมพ์ บทความ หลาย ฉบับ.',
 'ทาง ตะวันออก ของ ประเทศ ของ เรา มี เศรษฐกิจ ที่ ได้ รับ การ พัฒนา.',
 'วัน นี้ ฉัน คิด ว่า ฉัน เล่น ได้ ไม่ ดี.',
 'ฉัน ไม่ ต้องการ เงิน ทอน, กรุณา เอา ใบเสร็จ ให้ ฉัน.',
 'เจ้าของ ถูก ปรับ สอง ร้อย หยวน สําหรับ การ จอดรถ ผิด กฎหมาย.',
 'ฉัน ทํา แพนเค้ก เก่ง มาก.',
 'อย่า รื้อ เรือ ไม่เช่นนั้น มัน จะ พลิกคว่ํา.',
 'แทนที่ จะ ใจเย็น ลง, เธอ กลาย เป็น ตื่นเต้น มาก ขึ้น เรื่อยๆ.',
 'ผู้ ป่วย มี ปฏิกิริยา ต่อต้าน เสพย์ติด กับ ยา.',
 'เขา หันหลัง ไป ข้างหน้า.',
 'สวนสนาม ของ เรา เป็น สี่ เหลี่ยม.',
 'เธอ แก้ไข ปัญหา อย่าง ง่ายดาย.',
 'เสียงดัง สามารถ กีดกัน คน อื่น จาก การ เรียน.',
 'ฉัน รู้สึก ราว กับ มี แมลงวัน บิน มา บน ฉัน.',
 'วัน นี้ ฝน ต้อง ตก.',
 'การ สูบ บุหรี่ เป็น สาเหตุ ของ อหิวาตกโรค.',
 'ค่า ธรรมเนียม ทั้งหมด น้อยกว่า หนึ่ง พัน เก้า ร้อย เหรียญ',
 'ชน กลุ่ม ชน ผิว ดํา เป็น ส่วนใหญ่ ถูก กระจาย ใน แอฟริกา.',
 'พวก เขา รวบรวม สาร ฟอก เลือด เพื่อ วิเคราะห์.',
 'ประสบ ความ สําเร็จ, คุณ ต้อง ทํางาน หนัก.',
 'รูปแบบ สถาปัตยกรรม ของ โรง แรม น่าสนใจ มาก.',
 'เรา จัดการ ความ เสี่ยง อย่าง ไร?',
 'ความ เศร้าโศก ใน ผลงาน ของ เขา ผสม ไป ด้วย การ เยินยอ และ ความ เศร้าโศก',
 'เธอ ปฏิเสธ ข้อ กล่าวหา.',
 'ภาพวาด นี้ ราคา เท่า ไร?',
 'เสื้อผ้า ชนิด นี้ เป็น ที่ นิยม.',
 'เรา ซื้อ รถ ด้วย เงิน ผ่อนส่ง ผ่อนส่ง.',
 'ฉัน ต้องการ สําเนา กุญแจ สําหรับ การ ใช้ ฉุกเฉิน.',
 'เขา ตกหลุม รัก ผู้หญิง คน หนึ่ง.',
 'อาหาร สุนัข อยู่ ที่ ไหน?',
 'บอก ฉัน ว่า เขา พูด อะไร?',
 'หมอ ฉีดยา ให้ ผู้ ป่วย ป่วย.',
 'แอปเปิ้ล หนึ่ง กิโลกรัม เท่า ไร?',
 'เพื่อน ของ ฉัน พูด ว่า บ้าน ที่นั่น แพง มาก.',
 'ฉัน เช็ด โต๊ะ ให้ สะอาด.',
 'บางครั้ง ก็ ไม่ สามารถ หลีกเลี่ยง ได้.',
 'เธอ เลิก กับ เขา',
 'ดวงดาว อะไร ที่ สว่าง กว่า ดวงอาทิตย์?',
 'เรื่อง เหล่า นี้ มี มา เป็น เวลา นาน แล้ว.',
 'เธอ ปิด ตัวเอง ใน สํานัก งาน ตลอด ทั้งวัน.',
 'การ ประชุม ครั้งนี้ ไม่ มี อะไร เกี่ยวข้อง กับ เขา.',
 'คุย กัน เกี่ยว กับ เรื่อง แต่งงาน ทั้งหมด.',
 'ไม่ ดื่ม น้ํา ผลไม้ หรือ โคล่า ก่อน การ ทดสอบ ปัสสาวะ.',
 'แอน เปลี่ยนใจ แล้ว ตัดสินใจ ที่ จะ อยู่ บ้าน.',
 'ทิศ ใต้ ชื้น และ ทิศ เหนือ แห้ง.',
 'คุณ รู้สึก เกี่ยว กับ เขา อย่าง ไร?',
 'ทุกวัน นี้ ริมฝีปาก ของ ฉัน แห้ง เสมอ.',
 'ฉัน กําลัง เรียน ชั้น เรียน ภาษา จีน ชั้น สูง.',
 'เสียงดัง ของ การ ระเบิด ถูก ได้ยิน มา หลาย กิโลเมตร.',
 'เจ้านาย ต้องการ ขึ้น เงินเดือน ให้ เรา.',
 'คุณ มีเ งิน เพียงพอ ไหม?',
 'เปล่าเปลี่ยว.',
 'เธอ กระตุ้น ให้ เด็กๆ มี ส่วน ร่วม ใน กิจกรรม ของ โรงเรียน.',
 'เธอ กระตือรือร้น มาก เกี่ยว กับ ลูกค้า ของ เธอ.',
 'เขา วางหู โทรศัพท์ ดัง ลั่น.',
 'การ ศึกษา เป็น กุญแจ สู่ การ เจริญเติบโต ของ ประเทศ และ การ เติบโต ใหม่ ของ ประเทศ.',
 'เรา จัดการ ความ เสี่ยง อย่าง ไร?',
 'การ เดินเท้า เปล่า สามารถ ทําร้าย ได้.',
 'ฉัน ต้องการ ฟัง วิทยุ ขณะ ขับ รถ.',
 'พวก เขา ใช้ การ หยุดพัก ระหว่าง การ ประชุม ไป เที่ยว รอบ เมือง.',
 'วันที่ 1 มิถุนายน เป็น วัน เด็ก นักเรียน นานาชาติ.',
 'ฉัน พบ ว่า ฉัน กําลัง หา อะไร อยู่.',
 'โพ ร เซ ส โหลด ใช้เวลา สอง ชั่วโมง.',
 'ไมค์ จําเป็นต้อง ปรับปรุง ทักษะ การ แปล ของ เขา.',
 'ฝา ถังขยะ ของ ฉัน ไม่ สามารถ ปิด ได้.',
 'หนังสือพิมพ์ นี้ อธิบาย แนวคิด ของ แนวคิด ของ " & quo t h o t ".',
 'ฉัน ซาบซึ้ง ทุกอย่าง ที่ คุณ ทํา.',
 'หนังสือ ที่ ดี มาก, อ่าน หนังสือ ดีๆ, และ จาก นั้น เขียน ความคิด ของ คุณ เอง. นี่ คือ การ เริ่มต้น ของ การ เขียน เรียงความ ที่ ดี.',
 'ทุกคน กําลัง รอ คุณ อยู่.',
 'มีด เล่ม นี้ คม พอที่ จะ ตัด ผ่าน เหล็กกล้า.',
 'เขา ชอบ ความ รู้สึก ของ การ ขับ รถ ลง บน ทางหลวง จริง ๆ.',
 'พวก เขา เขียน จดหมาย อําลา ให้ ฉัน.',
 'ฉัน อยู่ บ้านเกิด ของ ฉัน, ถ้า เรา เห็น นกพิราบ, เรา จะ โยน ก้อน หิน ไป ที่นั่น.',
 'กอง ทัพ ปฏิวัติ ปราบปราม ปราบปราม ปราบปราม กดขี่ จักรพรรดิการ.',
 'เขา จด บันทึก, จด บันทึก คําแนะ นํา ส่วน ตัว.',
 'บุคลิกภาพ ของ เขา ชี้ ออก มา ทาง ทาง อาชีพ ของ เขา.',
 'ยา จีน ดั้งเดิม',
 'ปัญหา ที่ สอง อาจจ ะ ร้ายแรง มากกว่า นี้.',
 'พวก เขา ประกาศ ความ จงรักภักดี ต่อ พระมหากษัตริย์.',
 'มี น้ํา พุ ใหม่ ใน สวน นี้.',
 'พวก มัน มาจา ก แอปเปิ้ล แคน เน อร ์.',
 'พวก กรรมกร กําลัง วาง พื้น.',
 'ฉัน กําลัง ทํา การบ้าน ของ ฉัน และ ฉัน ไม่ มี เวลา ที่ จะ เล่น กับ คุณ.',
 'ฟังก์ชัน อิเล็กทรอนิกส์ นี้ มี ฟังก์ชัน การ แสดง อุณหภูมิ ด้วย.',
 'เขา อุทิศ ชีวิต ให้ กับ วิทยาศาสตร์.',
 'เขา ขาด ทักษะ การ สื่อสาร.',
 'เธอ อาศัยอยู่ บ้าน ป้า ของ เธอ ตั้งแต่ เธอ เป็น เด็ก.',
 'เขา กระตือรือร้น ที่ จะ เรียน ภาษา จีน โบราณ.',
 'จีน มี ประเพณี โบราณ หลาย อย่าง.',
 'หุ้น ของ บริษัท สูง ขึ้น ถึง 1 4 0 บาท.',
 'เธอ กําหนดการ ออก กําลังกาย ของ เธอ ใน บ่าย วันเสาร์.',
 'ถ่านหิน เป็น เชื้อ เพลิง ที่ แข็ง.',
 'ฉัน ต้องการ ส่ง จดหมาย ลงทะเบียน นี้.',
 'ถนน สาย นั้น.',
 'เขา เป็น ผู้ พิพากษา ของ ที่นี่.',
 'เรา ดูแล อย่าง ละเอียดถี่ถ้วน.',
 'เขา เปลี่ยน ทิศทาง และ มุมมอง.',
 'น้ํา ไหล ออก มา จาก ท่อ ใน ห้องน้ํา ของ ฉัน, แต่ ไม่ มี อะไร ที่ ฉัน สามารถ หยุด มัน ได้.',
 'ผลไม้ กระป๋อง นี้ ถูก ทอ จาก ผลไม้ ฟักทอง.',
 'ขอบคุณ ที่ มา, และ ยินดี ที่ ได้ มา อีก ครั้ง ใน ครั้ง หน้า.',
 'บริษัท นี้ เชี่ยวชาญ ใน การ ผลิต ซีดี - ROM S.',
 'จัตุรัส มี มากกว่า นี้ และ มากกว่า นั้น มี นัก ร้อง อีก มาก ขึ้น และ มากกว่า นั้น ใน จัตุรัส.',
 'กําแพง ซีเมนต์ ถูก ใช้ อย่าง กว้างขวาง เนื่อง จาก ความ เร็ว การ ก่อสร้าง ที่ เร็ว ของ พวก เขา.',
 'กิจวัตร การ นอน ของ ฉัน ยุ่งเหยิง อย่าง สิ้นเชิง เพื่อที่ จะ แก้ไข ใน เร็วๆนี้.',
 'เขา ต้อง ปฏิบัติ ตาม กฎระเบียบ ของ กิจกรรม ของ เขา.',
 'สิ่ง ที่ โปรดปราน ของ เรา ที่ จะทํา เมื่อ เรา เป็น เด็ก คือ หิมะ ตก ภูเขา และ ดู ว่า มัน สามารถ เคลื่อน ที่ เร็ว แค่ ไหน.',
 'คุณ ควร เขียน ชื่อ ชาติ ของ คุณ ใน พื้นที่ นี้.',
 'ผลไม้ ผลไม้ ผลไม้ ผลไม้ สามารถ ชั่ง น้ําหนัก ได้ มากกว่า สิบ กิโลกรัม.',
 'คุณ แพ้ ยา อะไร บ้าง ไหม?',
 'เขา จะ แปล ภาษา อังกฤษ เป็น ภาษา อังกฤษ.',
 'คุณ ต้องการ ดื่ม เบียร์ หนึ่ง ขวด ไหม?',
 'เธอ พูด ภาษา อังกฤษ ได้ ดี.',
 'เขา บิน กลับ ไป ลอนดอน.',
 'คุณ สามารถ บอก ฉัน ได้ไหม ว่า ไป สถานี รถไฟ อย่าง ไร?',
 'เด็กๆ ชาว ต่าง ด้าว โต ขึ้น ใน ชนบท.',
 'คุณ สามารถ บอก หมายเลข โทรศัพท์ ของ คุณ แก่ ฉัน อีก ครั้ง ได้ไหม?',
 'เรา กลับ บ้าน เมื่อ มัน มืด กัน เถอะ.',
 'พวก เขา ดื่ม ไวน์ แดง จนถึง เที่ยงคืน.',
 'คําถาม นั้น ยาก ที่ จะ ตอบ.',
 'คุณ ควร บอก ฉัน ดี กว่า.',
 'เธอ กลัว ความ เจ็บปวด จาก การ คลอด บุตร.',
 'คํา สั่ง ถูก บันทึก บน กระดานดํา.',
 'ฉัน ชอบ การ จัด ดอกไม้ ของ คุณ.',
 'ฉัน ชอบ ภาพวาด นั้น มาก ขึ้น เรื่อยๆ.',
 'ขวด นม แตก, อย่า ดื่ม มัน.',
 'เขา เลิก นิสัย ไม่ ดี.',
 'เมือง มี สิ่งแวดล้อม ที่ สวยงาม.',
 'ฉัน ต้องการ สวม เสื้อ ยืด สีเหลือง.',
 'คุณ สามารถ มา พรุ่ง นี้ หรือ วันหลัง.',
 'ลูก สาว ของ ฉัน อาย มาก และ ลูก ๆ อื่นๆ มี ช่วง เวลา ที่ ยาก ที่ จะ พูดคุย กับ เธอ.',
 'มี เที่ยวบิน สาม เที่ยวบิน ไป ปักกิ่ง สัปดาห์ นั้น.',
 'ประโยชน์ ของ โทรศัพท์ มือถือ คือ อะไร?',
 'หมายเลข โทรศัพท์ ของ คุณ คือ อะไร?',
 'นัก แพทย์ ที่ มี คุณสมบัติ เท่านั้น ที่ ควร ทําการ ผ่าตัด สัตว์.',
 'ชุด กระโปรง พอดี ไหม?',
 'เมื่อวาน นี้ ฉัน ไป สวน สัตว์ และ เห็น ลิง.',
 'ตอน นี้ ถ้า คุณ ไม่ ทํางาน หนัก, คุณ จะ เสียใจ ภาย หลัง',
 'ทันใด นั้น ฉัน รู้สึก เจ็บ ที่หลัง ของ ฉัน ขณะ ที่ วิ่ง ไป ตาม แม่น้ํา.',
 'ทุกคน แลกเปลี่ยน ความคิด เห็น กัน.',
 'ใช้เวลา ยี่สิบ ห้า นาที ใน การ ทํา ซอส.',
 'เธอ เรียนจบ ชีวิต ใน วิทยาลัย',
 'ร่างกาย ฉัน ไม่ เหมาะ กับ กิจกรรม ชายหาด.',
 'เขา โยน ซุง เข้าไป ใน กอง ไฟ และ วาง มัน บน กอง ไฟ.',
 'ฉัน ต้อง แจ้ง สิ่ง นี้ ตาม ศุลกากร.',
 'ฉัน ได้ยิน เสียง ตะโกน ของ ตํารวจ ดัง โครม - หยุด?',
 'คลับ ฟุ่มเฟือย.',
 'สันติภาพ เป็น อาวุธ ที่ ดี ที่สุด สําหรับ การ พัฒนา.',
 'เด็ก วัยรุ่น กลัว ที่ จะ ดู ภาพยนตร์, ไม่ กล่าวถึง เด็กๆ.',
 'รองเท้า มี ราคา สมเหตุสมผล.',
 'โรงเรียน มัธยม ปลาย.',
 'อาจารย์ อยู่ ใน หัวใจ ของ ระบบ การ ศึกษา.',
 'มี ต้นไม้ ใหญ่ สอง ต้น นอน อยู่ บน ถนน, และ รถ หลาย คัน ถูก ติด อยู่ ใต้ ต้นไม้ ใหญ่, ไม่ สามารถ เคลื่อน ที่ ได้.',
 'ปัญหา สุขภาพ ทาง จิตใจ ถูก เพิกถอน มา เป็น เวลา นาน เกิน ไป.',
 'ฉัน เท น้ํา ผลไม้ ลง ใน เหยือก.',
 'ฉัน คิด ว่า นั่น เป็น เรื่อง ไร้ สาระ.',
 'แฟน หนุ่ม ของ ฉัน โกน หนวด ทุก เช้า.',

In [ ]:
textfile = open("/content/T5_en2th", "w")

for element in thai_preds:

    textfile.write(element + "\n")

textfile.close()

In [ ]:
eng_th_bleu = sacrebleu.corpus_bleu(thai_preds, thai_truth)
print("English to Thai: ", eng_th_bleu.score)

English to Thai:  0.1010877860789219